### ISSUE TITLE
ORAS Fossil Freeze issue

### ISSUE THREAD

**Issue by RevanXVIV** [Ajarmar/universal-pokemon-randomizer-zx#100]
Ok so I'm trying to reset for shiny fossil pokemon on an Alpha Sapphire Randomizer right now, but every time I go to my pokemon tab the game just black screens, meaning Fossil resets are useless now, I've even tried boxing the pokemon and then unboxing them and the game still black screens if they are in my party. This is an actual problem I've had using this randomizer previously, but never this bad. Please fix this.

**Comment by tom-overton** [comment]
Can you provide a log file of your randomization? And can you please tell me what fossil is causing this problem? I'm not sure what exactly I'm supposed to be looking for without it.

**Comment by RevanXVIV** [comment]
You mean a spoiler log? I can try. However this issue seems to happen with all fossils as I've gotten it from Jaw, Sail, and Dome fossils, as those are usually the ones I find rather early.
[seed 1.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5798379/seed.1.log)

**Comment by tom-overton** [comment]
Yeah, that log is exactly what I was looking for, thanks! And hmm, interesting. I'm guessing you mean this fix?

- Setting: Don't Revert Temporary Alt Formes
OR/AS: Now also doesn't revert Primal Groudon/Kyogre when they are caught.

If it's not too much of a bother, can you try making a seed where "Don't Revert Temporary Alt Formes" is turned *off* and let me know if fossils work? If it's really annoying, don't worry, I can look into it myself, but this would really speed up my investigation!

**Comment by RevanXVIV** [comment]
I'm doing a stream atm, but when I'm done with my current run I can make a new seed a check it out.

**Comment by RevanXVIV** [comment]
I think that the fossil freezing is just something not working properly with the resurrection process as opposed to it having something to do with the form reversion option. I only mentioned form reversion as it is the latest update.

**Comment by tom-overton** [comment]
Hmmm, I can't seem to replicate this black screen myself. Here's what I see on both 3DS and Citra:

https://user-images.githubusercontent.com/12245827/104303316-cbfe8680-547e-11eb-8646-283c334efe79.mp4

From your description, it sounded like you're seeing a black screen when you look at the Pokemon's stats. But here I'm looking at Noivern's stats just fine. I'm using the same seed and settings as the log you sent me, so there shouldn't be any differences between your seed and mine. You can even see in your own log that Tyrunt becomes Noivern.

I have a couple of clarifying questions that will help me narrow this down a bit more:
1. Are you playing on real 3DS hardware or Citra?
2. Did you output your seed as CXI or layeredFS?
3. Have you loaded a game update into the randomizer? Or are you just randomizing the base Alpha Sapphire game?

**Comment by RevanXVIV** [comment]
1) Both

2) Layered FS

3) I believe its just the base game

**Comment by RevanXVIV** [comment]
OH! Wait a minute! I think I'm having this issue because I'm using layered FS on Citra! Could that be the problem?

**Comment by tom-overton** [comment]
LayeredFS *should* work fine in Citra (it's actually how I recorded that video I posted), but there are ways it can blow up. Let's try to figure out if you're running into any of them:
1. Since you didn't randomize with a game update, you need to *also* make sure you don't have a game update installed in Citra. If you can see AS in the game list, the game icon will have its update number on it like this if you have a game update installed (this is OR but it works the exact same way with AS):
![image](https://user-images.githubusercontent.com/12245827/104377108-cc2c6f80-54da-11eb-940b-6217b6ff91bd.png)
If you have a game update installed, you'll need to delete it. We have [instructions on our wiki](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#managing-game-updates-in-citra), but unfortunately it's a little annoying on Citra.
2. Assuming you don't have a game update installed, let's see if layeredFS is causing a problem in some other way by making a seed using CXI output instead. First, delete your existing layeredFS for Alpha Sapphire (right click the game -> Open Mods Location -> delete or move everything in the folder that pops up), then make a new seed and output it as CXI (it will take a while if you're used to layeredFS output, so be patient). Then boot the new CXI in Citra and see if you have the same black screen issue.
3. Assuming that you *do* have the same black screen issue with a CXI, then CXI vs layeredFS doesn't matter at all. This may seem stupid, but at this point, just try resurrecting a fossil with a completely unrandomized version of Alpha Sapphire. I just want to make sure that it's the *randomizer* that's introducing the problem, not the original ROM.
4. Assuming that the original ROM works fine, then it is indeed the randomizer introducing the issue. I know you've said it's worked in the past, but can you try again with [v4.0.1](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.0.1) again? I just want to make 100% sure it's v4.0.2 that's causing the issue.

Hopefully at least *one* of these helps. Let me know what happens when you try these out. I'm quite curious about this bug because I can't replicate it myself at all.

**Comment by RevanXVIV** [comment]
My version doesn't have a number on it, however I no longer have the older version of the randomizer. So what I'll do is I'll grab a fossil, delete the randomizer, and see if it's the randomizer.

**Comment by RevanXVIV** [comment]
Update: Ok so it did NOT crash when turning off the randomizer, my next test is the CXI file

**Comment by RevanXVIV** [comment]
Update 2: Nope CXI blackscreened too. How do I update the game?

**Comment by RevanXVIV** [comment]
Update 3: Nope old rando 4.0.1 is also black screening

**Comment by RevanXVIV** [comment]
So from what I've gathered it's not the version, or the file types, so it seems to be the randomizer, at least from my point of view, as in vanilla it works just fine.

**Comment by tom-overton** [comment]
Thanks for testing all this! Don't worry about updating the game; if it didn't work in Alpha Sapphire v1.0, it's not going to work in v1.4. I just wanted to make sure the game version matched the randomized version. At this point, I'm curious if it's some sort of wild interaction with certain settings. Can you make a seed with *only* static Pokemon changed, like so?
![image](https://user-images.githubusercontent.com/12245827/104383034-064e3f00-54e4-11eb-89f5-271d986080a3.png)

If you've already done this, just let me know. I just want to eliminate all the variables here. If *just* changing static Pokemon still black screens, then it's *very* specific where I need to investigate. If it *doesn't* black screen, then clearly another setting is responsible for it.

**Comment by RevanXVIV** [comment]
Yeah I'm eating dinner right now but I'll make a static only seed after I'm done, I'll update you.

**Comment by RevanXVIV** [comment]
Update: Ok just tested static only, it blackscreened, so it seems to only happen when static pokemon are randomized.

**Comment by tom-overton** [comment]
OK, I have a few more ideas. Sorry for the constant barrage of questions! I'm assuming you outputted as layeredFS here.
1. Open your layeredFS, and you should immediately see code.bin. This is us overwriting the game's main executable. Delete that code.bin from the layeredFS (so that we're using the vanilla game executable) and try again. Do you still black screen?
2. If and only if deleting code.bin didn't help, head into the romfs folder and you should see a file called DllField.cro. This is actually where the static Pokemon are stored. Delete everything in the romfs folder *except* DllField.cro and try again. Do you still black screen?

**Comment by RevanXVIV** [comment]
Did what you said, and it still black screened. Any other ideas?

**Comment by RevanXVIV** [comment]
There is an odd workaround I've found in-game that fixes this issue, if you enter a battle and then run after reviving the fossil, everything goes back to normal. I don't know if this info is helpful, but thought I'd share it anyway, just in case.

**Comment by tom-overton** [comment]
No, at this point we've actually narrowed it down as far as we can. The problem is in DllField.cro, so now it's time for me to investigate. I request only one last thing for you, which is to send me:
1. A clean version of DllField.cro dumped straight from your unrandomized ROM
2. A randomized version of DllField.cro

For the second one, you can just send me what's in the layeredFS; just zip it up and call it "randomized.zip". For the first one, you can right-click your unrandomized ROM in Citra and select "Dump RomFS" like this:
![image](https://user-images.githubusercontent.com/12245827/104386309-bffbde80-54e9-11eb-9332-4d439977cfc3.png)

Wait a bit, and Citra will automatically dump the entire contents of the game. Eventually it will pop open a folder; in that folder, find DllField.cro and put it in a .zip file called "clean.zip". Upload them both here and I'll definitely take a look! After you've uploaded clean.zip, feel free to delete the romfs dump that Citra made to reclaim 1.8 GB of hard drive space.

**Comment by RevanXVIV** [comment]
Actually due to me recently finishing a custom shiny form hack, I have an unmodified DLLField.cro ready to go. I'll make a folder and zip them up together, I'll label which is which

**Comment by RevanXVIV** [comment]
[DllField files.zip](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5805419/DllField.files.zip)

Here are the files

**Comment by tom-overton** [comment]
Thanks! I'll take a look. Sorry for asking a million questions, but luckily we successfully narrowed it down to exactly one file, so this makes my job way easier.

**Comment by RevanXVIV** [comment]
Trust me I get it. I spent 3 weeks modifying and testing shiny sprites on Alpha Sapphire I can only imagine how complex a randomizer is.

**Comment by tom-overton** [comment]
This has to be one of the most baffling bugs I've ever worked on. I figured that *maybe*, for some unknown reason, *your* vanilla DllField.cro was different in some way from *my* vanilla DllField.cro, and the randomizer was corrupting yours in a way that it's not corrupting mine. But nope, your vanilla DllField.cro and my DllField.cro are 100% identical. So then I tried to use the randomized version you sent for myself, but I *didn't* black screen; everything worked fine on both Citra and 3DS. Then I randomized my own DllField.cro and compared it to your randomized one; I don't see any weird irregularities in yours. Everything just *looks* perfectly fine when I compare the two.

At this point, I decided to skip the randomizer entirely and hand-craft my own edit to DllField.cro using a hex editor. This changes the *absolute bare minimum* necessary to make the fossils different and *nothing* else. I simply edited the fossil's species IDs to be something else. All other static Pokemon are completely unchanged, and all other bytes in this file are completely unchanged. I confirmed that this works exactly how I expect on both Citra and 3DS, so I'd like you to try it too. Just put the DllField.cro in this zip file in the romfs folder of your layeredFS for Alpha Sapphire:
[test.zip](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5809156/test.zip)

You'll know it's working if you get a Pokemon between Bulbasaur and Metapod when you resurrect a fossil. If *this* still black screens, then I'm fairly stumped.

**Comment by RevanXVIV** [comment]
I think I might know what causes the crash:

1) I made 583 custom shiny forms and used this modified file in the randomizer to ensure I could get all the custom shinies

2) I increased the Shiny odds to 1.17% using PK3DS

3) I also used PK3DS to remove all the shiny locks


Is it possible any of these could be causing the problem?

**Comment by tom-overton** [comment]
No, it *can* be right. The two things can absolutely conflict in weird, unexpected ways. Try using a randomized DllField.cro with a *completely* vanilla game, not with your ROM hack

**Comment by RevanXVIV** [comment]
Thing is I just finished this hack about 4 days ago. I've been using this randomizer for about 3-ish months now and I've always had this issue using the tool. Perhaps I'm doing something wrong, but I'll try out a vanilla AS rom later after I stream. I'll let you know what I find.

**Comment by RevanXVIV** [comment]
Sorry for the late response, had a lot to do yesterday, however today I'm gonna be starting a new seed on stream using vanilla alpha sapphire as a base rom, so when I get to the fossils I'll let you know what happens.

**Comment by RevanXVIV** [comment]
Ok it took a little longer than I had hoped but I finally have a seed set up running off the vanilla Alpha Sapphire rom.

The custom mods I have are the custom textures in: Romfs/a/0/0/8

And a few custom songs in: Romfs/sounds

So what I'm gonna do if it black screens again when I try to revive a fossil is first remove the custom music, then remove the custom textures if the problem persists.

**Comment by RevanXVIV** [comment]
Ok I think I figured out what may be causing the black screen. I  used the modded CIA file by accident, then used the modded files, so the two mods may have conflicted with eachother, so I'm gonna try using a base rom, unmodified, alongside the mods to see if the mods are what's causing the issue.

**Comment by RevanXVIV** [comment]
Update: Ok using a vanilla file and using the randomizer as the mod doesn't seem to work, this seems to be an issue only when using my mods, so you may want to consider closing this topic.

**Comment by tom-overton** [comment]
OK sounds good. Thanks for testing all the many different things I asked!
