### ISSUE TITLE
Can't get Karrablast or Shelmet to evolve

### ISSUE THREAD

**Issue by CuddlyE** [Ajarmar/universal-pokemon-randomizer-zx#102]
I was playing smoothly through a randomiser of Omega Ruby. I had turned both Easier Evolutions and 'Change impossible Evolutions' (I double checked, and yes I had them both checked for the settings I used). After finding a Karrablast, boxing it until I found a Shelmet (luckily, not long after). I was disappointed to find that upon leveling up with the other in the party, neither evolved. I don't know if it only happens after a certain lvl that isn't listed on the Wiki section, or if I've encountered some kind of bug. But they just won't evolve. Not with them both leveling up at the same time in a double battle, not with one leveling up in a single battle with the other in the party. They just won't evolve...

**Comment by tom-overton** [comment]
This is expected behavior when using "Make Evolutions Easier," "Change Impossible Evolutions," and randomizing Wild Pokemon. We have a section that explains it [on the wiki](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Evolutions#make-evolutions-easier):

> **Only if Wild Pokemon are randomized:**
> - Pokemon that evolve by having another specific Pokemon in the party now evolve at level 35 instead. This affects Mantyke, and if "Change Impossible Evolutions" is used, Shelmet and Karrablast.

Now if you *didn't* randomize Wild Pokemon, then that's a bug, and feel free to reopen this. But from what it sounds like, you just need to get either of them to level 35 to evolve them.
