### ISSUE TITLE
Tail Tutorial does not seem to work in Alpha Sapphire

### ISSUE THREAD

**Issue by Frostplays-ZERO** [Ajarmar/universal-pokemon-randomizer-zx#12]
does the Tail Tutorial not work if none of the pokemon in the route have a tail?

**Comment by Ajarmar** [comment]
I assume this is the tutorial that happens on route 101 with Brendan/May near the start of the game? It seems likely that that's why it doesn't work, although I don't think this is important enough to fix because the game can progress regardless.

**Comment by Afterlyte** [comment]
I'd like to note that this isn't related to the program itself, as the same thing happens if you use another randomizer like pk3DS. The reason it happens is because it's specifically looking for a Poochyena in the wild encounter table, and if it can't find one (because it's randomized) it just doesn't show up. Thankfully it doesn't hinder the game at all.
