### ISSUE TITLE
How to?

### ISSUE THREAD

**Issue by Lstjudgment** [Ajarmar/universal-pokemon-randomizer-zx#123]
I am trying to create/update and execute this version of this randomizer through Eclipse for my own personal use, and I am struggling to recreate the PokeRandoZX.jar that the Launcher uses. Can you point me to where some basic instructions are, or explain how you create this part so I can test my update to break up the TM/HM type randomizer? (I only want to randomize the HM's not the TM's and the randomizer does not offer this option)

**Comment by tom-overton** [comment]
We have a wiki page for building the randomizer here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Building-Universal-Pokemon-Randomizer-ZX

I imagine that Eclipse might have difficulty in building the GUI, but I'm not sure; I've never used it.

**Comment by Lstjudgment** [comment]
Thank you for the link and quick response. I was looking for that wiki page and could not find it browsing through the web. Once I get what I want working,, if you would like me to share the update with you I have no issue doing that, Otherwise I will not update anything outside of my local machine.

**Comment by tom-overton** [comment]
If you want to submit a pull request to the randomizer, please submit a [Contibution Idea](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/new?assignees=&labels=Contribution+Idea&template=contribution-idea.md&title=%5BContribution+Idea%5D) so we can talk it over. Otherwise, feel free to edit the randomizer on your own personal machine however you like.
