### ISSUE TITLE
[Help] Unhandled exception saving ROM to disk

### ISSUE THREAD

**Issue by seraphean** [Ajarmar/universal-pokemon-randomizer-zx#132]
**Describe your problem clearly:** 
Unhandled exception saving ROM to disk
**System (please fill in the following information):**
 - Operating System: Windows 10 64x
 - Randomizer Version: 4.1.0
[error_2021-03-20-17-02-37.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6176418/error_2021-03-20-17-02-37.txt)

**Comment by tom-overton** [comment]
Thanks for supplying a log! I tried using that same seed + settings combo and it worked fine for me, as evidenced by this log: 
[test.nds.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6176679/test.nds.log)

In the "ROM Diagnostics" section, I noticed that your ROM does not match mine:
Yours:
```
arm9: 020CE446
overlay9_1: 133B10AB
```

Mine:
```
arm9: 63D4835C
overlay9_1: 73437352
```

Is this a romhack? If so, try using a completely unmodified version of SoulSilver and try again. Otherwise, try a different ROM and see if that works for you.

**Comment by seraphean** [comment]
> Is this a romhack? If so, try using a completely unmodified version of SoulSilver and try again. Otherwise, try a different ROM and see if that works for you.

It was AP patched with DS-Scene, I tried with an unpatched version and it randomized fine but the AP was still active when I played. Does it not work with AP patched roms?

**Comment by seraphean** [comment]
Found the issue, I trimmed the ROM which seems to cause the error. Patching the ROM without the trim worked fine
