### ISSUE TITLE
[Bug] i confirmed i have the correct java i tried opening thru windows powercell or what ever it said these files cannot be accesed

### ISSUE THREAD

**Issue by sketch79** [Ajarmar/universal-pokemon-randomizer-zx#144]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**System (please complete the following information):**
 - Operating System: 
 - Java Version:
 - Randomizer Version: 

**Additional context**

**Comment by Ajarmar** [comment]
Please explain the problem in more detail. What happens when you try to open `launcher.jar` by double-clicking it? Is there a `launcher-log.txt` created in the folder with the launcher after you try to launch it? Also, please copy-paste the result of running `java -version` (or provide a screenshot) so we can see that you're actually running the correct Java version.

**Comment by yugo0075** [comment]
I had a very similar problem and solved it (following Ajarmar advice, not taking credit here) by opening the windows powercell directly from the folder where the launcher was (you can do so by shift clicking inside the folder) and typing "java -jar launcher.jar".
Hopefully it can solve your problem too.

Good luck.

**Comment by Ajarmar** [comment]
We have switched to a new launcher in v4.2.0. Please try downloading [the latest randomizer version](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases) and see if it works for you. If you run into problems with the new launcher, go here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/221
