### ISSUE TITLE
starters

### ISSUE THREAD

**Issue by wakeful19** [Ajarmar/universal-pokemon-randomizer-zx#16]
for some reason starters on oras and x/y wont randomize

**Comment by tom-overton** [comment]
Can you please upload a log file to demonstrate that the starters aren't randomizing?

**Comment by wakeful19** [comment]
yeah hang on, the other trainers will randomize but the starteres and my wild pokemon will not
[ganga.cxi.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5295279/ganga.cxi.log)

**Comment by wakeful19** [comment]
it shows those choices as randomized starters, but when promted to choose it shows the original 3 and no routes are changed(this is on y)

**Comment by tom-overton** [comment]
Thanks for the log! I randomized Y using the same random seed and setting and I can confirm that the starters worked for me:
![image](https://user-images.githubusercontent.com/12245827/94499600-fb300700-01b1-11eb-9bb9-b7ec42cbc6b2.png)

In other words, the randomizer is working fine, but there's something misconfigured in your emulator. Can you check the following for me?
1. If you have your Y ROM in your Citra game list, it will have a different icon if the game is updated or not. Compare these two icons for an example: 
![image](https://user-images.githubusercontent.com/12245827/94499789-72659b00-01b2-11eb-91ac-5732692b96b8.png)
If you *didn't* load a game update into the randomizer, but you *do* have a game update installed for Pokemon Y, then you need to delete the game update. If you *did* load a game update into the randomizer, but you *don't* have a game update instaalled for Pokemon Y, then you need to install that update in Citra. [This wiki page will help you with both of these](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#managing-game-updates-in-citra).
2. Assuming that the previous thing didn't fix it, can you right-click Pokemon Y in the game list, select "Open Mods Location", and confirm that nothing is in there?

**Comment by wakeful19** [comment]
ill try it, i think i deleted the wrong thing and now it says data is corrupted, can you get by that? is there any way to completely uninstall and reinstall into citra?

**Comment by tom-overton** [comment]
If you delete the folder C:\Users\[your name]\AppData\Roaming\Citra\sdmc\Nintendo 3DS\00000000000000000000000000000000\00000000000000000000000000000000\title\0004000e (or whatever the equivalent is on your operating system), then that should delete every update in Citra, which solve any data corruption issues. Unfortunately, that means you'll have to reinstall every update all over again. Citra's update handling is pretty poor at the moment, sorry about that!

**Comment by bobalife808** [comment]
I'm having the same issue but I also don't have an icon in the game directory. Do you think if I found that file and deleted it, it might solve the randomization issue?

**Comment by wakeful19** [comment]
its not letting me delete it, says i need permission from desktop something, even though im an admin

**Comment by tom-overton** [comment]
You might have the update installed without having the original game in your game directory. If you find the update and delete it, then that will likely solve your randomization issue. If you'd rather delete a specific game update rather than deleting all of them, navigate to C:\Users\[your name]\AppData\Roaming\Citra\sdmc\Nintendo 3DS\00000000000000000000000000000000\00000000000000000000000000000000\title\0004000e and look for the following folders:
X: 00055D00
Y: 00055E00
Omega Ruby: 0011C400
Alpha Sapphire: 0011C500
Sun: 00164800
Moon: 00175E00
Ultra Sun: 001B5000
Ultra Moon: 001B5100

**Comment by bobalife808** [comment]
Any idea what that folder equivalent would be on a Mac? That's how I run Citra. Really appreciate the help btw! Hopefully we can figure out how to solve the issue. I'm super excited to be able to randomize the 3ds games

**Comment by bobalife808** [comment]
Also I do have a CIA file of the update but am unsure if it is applied to my game. My game runs and like wakeful, everything I wanted randomized is except for starter and wild Pokemon. Do I need an updated copy of the game to run it properly or is it easier to find and delete the update?

**Comment by tom-overton** [comment]
Ah, good question. According to [this wiki](https://citra-emu.org/wiki/user-directory/) it would be ~/.local/share/citra-emu/sdmc/Nintendo 3DS/00000000000000000000000000000000/00000000000000000000000000000000/title/0004000e, where ~ is your home directory. If that doesn't work, then right-click on any game in your game list and select "Open Mods Location", then keep going up until you're in a folder called "citra-emu"

As for your second question: you can load the CIA of the game update into the randomizer to produce something that is compatible with an updated game. You can see [this wiki page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#3ds-game-updates) for more information. Due to the way 3DS game updates work, though, we can only output the randomized game as a layeredFS directory, not a CXI.

**Comment by bobalife808** [comment]
Okay great! Actually I've been running my game as a CXI file so maybe that's the issue. I'm going to try rerandomizing as a LayeredFS and follow the directions on how to run it and let you know. Thanks for the help!

**Comment by tom-overton** [comment]
Sorry about all the confusion. What's probably happening here is that the game update is overwriting our randomized files, hence why only some things don't work (they're the only things being overwritten). You have to be careful about making sure the randomized game you generate has a matching version in Citra or on your 3DS. I just pushed up c3844d45ae6d3c78e9ddb693578bff3a6c26973f today that will make what version of the game you randomized more explicit, so that will hopefully make things a little easier to understand in the next release. Unfortunately, Citra's game update management is basically nonexistent, so you'll have to manually delete files yourself.

**Comment by bobalife808** [comment]
No worries! Thanks for the update! Would I have to redownload the randomizer program with this change?

**Comment by tom-overton** [comment]
You would, but it's not something that's actually released yet. Whenever the next version of the randomizer comes out, it will include this change. However, I thought of an easier way to tell what version of the game you're running. Just look at the title screen. If you see a version on the bottom screen like this, then your game is updated, and you either need to (a) delete the update in Citra, or (b) load the corresponding game update CIA in the randomizer:
![image](https://user-images.githubusercontent.com/12245827/94504302-50254a80-01bd-11eb-9417-ea0cf7c4f932.png)

If you *don't* see that, then you just need to make sure that you *aren't* loading a game update in the randomizer. You should see something like this; if you see "(Ver. X.X)" next to it, then select Settings -> Unload Game Update
![image](https://user-images.githubusercontent.com/12245827/94504450-a85c4c80-01bd-11eb-92b2-8d610beb2916.png)

**Comment by bobalife808** [comment]
I'm trying to apply my new LayeredFS patch file to my game and following the instructions. Is there an issue with my game file if I'm unable to create a game directory shortcut for it?

**Comment by tom-overton** [comment]
Can you clarify what you mean by "unable to create a game directory shortcut for it"?

**Comment by bobalife808** [comment]
I actually figured it out! Apologies for the question! Thanks a ton for the help!

**Comment by wakeful19** [comment]
it says my saved data is corrupted, idk how to get around that.. any help?

**Comment by wakeful19** [comment]
i tried deleting the whole game through what you said, and i redownloaded and updated it and it still says saved data is corrupted

**Comment by tom-overton** [comment]
Oh, I get what you mean now. Unfortunately, I'm not sure why that's happening; my best guess is that because you deleted your game update, your save file is now incompatible. Try deleting the save file using Up + X + B on the title screen. Sorry for any loss of progress!

**Comment by wakeful19** [comment]
okay idk why i didnt think of that i used to do it all the time. You said you pushed something to hopefuly make the randomizer work better?
I still dont know why my game isnt randomizing my pokemon or the wild encounters but it randomizes trainers

**Comment by tom-overton** [comment]
No, I pushed something that will make it more obvious what version of the game you loaded into the randomizer. The reason why wild encounters and starter Pokemon are not being randomized is probably because of a version mismatch, since it seems like bobalife managed to solve his issues by making sure the versions matched.

[Take a look at this reply again](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/16#issuecomment-700382383) and make sure that the version on the title screen matches the version you see in the randomizer. If they match, then everything should work fine.

**Comment by wakeful19** [comment]
what im assumiong is my rom isnt updated like citra then

**Comment by wakeful19** [comment]
figured it out thank you!

**Comment by tom-overton** [comment]
You're welcome! I'm glad it worked for you!
