### ISSUE TITLE
[Contribution Idea] Randomizing held items

### ISSUE THREAD

**Issue by spaceonaut** [Ajarmar/universal-pokemon-randomizer-zx#161]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** 
This setting is intended to give trainer's pokemon more berries as held items. Similar to how one can add more pokemon for boss trainers, important trainers or all trainers, this setting would affect the same group of trainers.

MVP: All pokemon (in the selected trainer group) have a random berry legal in that gen.

More complex idea (possibly called "Smarter berry usage" or something):
- If a pokemon has one (or more?) 4x weakness, it is holding a berry that lessens that damage type (or one of the types chosen randomly).
- Otherwise, it is holding a random berry (legal in that gen) that restores HP, cures status, or reduces a super-effective type that pokemon has.

**What problem would your contribution solve? Please describe:** 
I've been enjoying a playthrough of Soul Silver with this randomizer. I think it would be more interesting if the opponents had more held items. Berries don't see a lot of use really, so it might make for some fun - a surprise extra 30 HP healed from a Sitrus berry, a Yache berry keeping an opponent's Salamence alive, a paralyzed poke instantly getting back to full health.

**Additional context:**

**Comment by spaceonaut** [comment]
I started looking at some specifics for this, starting with Gen4. For gen4 trainers, it appears there are 3 types of trainers - vanilla trainers, whose pokemon do not have any items and has the vanilla moves for that level; upgraded trainers, who have no held item, but can have custom moves (e.g. TMs); elite trainers, who can have held items and custom moves.

As such, I can't give every pokemon a berry :(

However, maybe a more general, interesting featurewould be to give items to all trainers' pokes that can have items, with some of the logic I detailed above being used to pick them semi-intelligently.

**Comment by Ajarmar** [comment]
I think the idea of randomizing trainer held items is pretty good, but I don't see any reason to restrict it to only berries. I think a general set of settings for trainer held item randomization would be better, perhaps with a setting for "only consumable items".

> I started looking at some specifics for this, starting with Gen4. For gen4 trainers, it appears there are 3 types of trainers - vanilla trainers, whose pokemon do not have any items and has the vanilla moves for that level; upgraded trainers, who have no held item, but can have custom moves (e.g. TMs); elite trainers, who can have held items and custom moves.
>
> As such, I can't give every pokemon a berry :(

This can be changed - the variable controlling this is stored as `poketype` in the `Trainer` class in the randomizer, which works as a bitfield (i.e. if `poketype & 2 == 1`, the Pokemon can have an item). However, it might not be viable to change this in generations below Gen 4 since changing it may require increasing the size of the "Trainer Pokemon" struct in the ROM. (In Gen 4 onwards I don't think it should be a problem because trainers are stored in a more structured archive from that point on, which you more easily can change the size of.)

The set of settings I'd suggest is:

- Choosing which trainers should be affected (split by Boss/Important/Regular like you suggested)
- A setting that restricts it to only consumable items
- A setting that restricts it to only the trainer's highest level Pokemon, instead of every Pokemon

What do you think?

**Comment by spaceonaut** [comment]
That's good to hear you can modify the TrainerData memory segment. I guess I read too much into the fact that [poketypes aren't changed](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/blob/869d392824aefd035e169bb737ba7ad2504e0707/src/com/dabomstew/pkrandom/romhandlers/Gen4RomHandler.java#L2178) currently, but in hindsight because we can add additional pokemon, it should have been obvious we can add more memory.

I like those options you suggested. Maybe also one option to differentiate between "truly random" and "smart, but random". e.g. making it not possible to put a hard stone on a pokemon with no rock moves or a Yache berry on a pokemon that is not weak to ice.

**Comment by spaceonaut** [comment]
Actually, what I had been trying before was a simple brainfart between &= and |=
I'll prototype something and send a PR for the "completely random" items before trying to do anything "smart".
🙃

**Comment by spaceonaut** [comment]
Of note: Gen2 does not seem like this would be interesting. Only a handful of trainers can have items (all the POKéFANs) and trying to give items to other trainers causes issues that are probably related to TrainerData getting too big. We'll leave it out for now.
