### ISSUE TITLE
[Help] Open ROM button is missing

### ISSUE THREAD

**Issue by Cbrand45** [Ajarmar/universal-pokemon-randomizer-zx#172]
When I launch the randomizer, the "Open ROM" button, that is normally in the top right, isn't there and the top of the screen is kind of squished. I'm on a MacBook, using version 4.1.0 and my java is up to date.
<img width="1015" alt="Screen Shot 2021-04-24 at 5 44 13 PM" src="https://user-images.githubusercontent.com/83142135/115973666-ca843600-a524-11eb-8edc-fe58dba80279.png">

**Comment by tom-overton** [comment]
This is addressed in issue #35, which will be fixed in the next randomizer release. Unfortunately, there's nothing you can do until that release other than adjusting your Mac's display settings; head to System Preferences -> Displays and mess with this setting:

![Screen Shot 2020-10-15 at 2 25 32 PM](https://user-images.githubusercontent.com/12245827/96187890-9cc59100-0ef2-11eb-9755-b262cad23fd8.png)

For more information, see the linked bug.

**Comment by Cbrand45** [comment]
Thank you!
