### ISSUE TITLE
.jar

### ISSUE THREAD

**Issue by TheBlaziking** [Ajarmar/universal-pokemon-randomizer-zx#18]
When I extract the files to another folder it doesn't change to the right file, it stays a WinRAR file even though it was named .jar in the original download
![Screenshot_10](https://user-images.githubusercontent.com/53891883/94615524-eddc5080-0275-11eb-8a10-652c06558d7f.jpg)

**Comment by Ajarmar** [comment]
Those are still .jar files - a .jar file is a type of archive. It seems like you have 8zip set as your default program for .jar files, but in order to run them, you need to run them with Java. I recommend doing the following:

1. If you don't have Java installed, go to https://java.com/ and download it. Make sure to get at least Java 8, 64-bit version. When you install Java, it might set itself as the default program for .jar files.
2. If Java did not set itself as the default program for .jar files, or if you already had Java installed, right-click on a .jar file and choose "Open with...". Java should appear as one of the programs in the list. Choose Java, check the "Always use the selected program to open this kind of file" checkbox, and press OK.

This will set Java as the default program for .jar files. After this you should be able to just double-click on .jar files to run them.

**Comment by TheBlaziking** [comment]
When I try going to java to open it it just pops up a black box for a split second. When I try to double clicke it it just goes into the inner files folder
![Screenshot_11](https://user-images.githubusercontent.com/53891883/94618536-51b44880-0279-11eb-913a-8adb044362d4.jpg)
.

**Comment by TheBlaziking** [comment]
I changed it to open with java but the blank screen for a split second still happens

**Comment by TheBlaziking** [comment]
To other's who might have this issue download jarfix it seems to have helped me at least open the program.
