### ISSUE TITLE
starter items don't get randomized

### ISSUE THREAD

**Issue by kiliwily** [Ajarmar/universal-pokemon-randomizer-zx#20]
The starter items don't get randomized even if i set it up. This happens only with the german emerald rom. It works perfectly fine for the english emerald rom and the german and the english firered roms. I haven't tested it with other languages/roms.

**Comment by kiliwily** [comment]
I saw in the offset list of the randomizer that the offset for the starter items is missing for the german emerald rom.
The offset is 0xB1196.

**Comment by tom-overton** [comment]
Thanks for the offset! I can confirm that the German version of Emerald now works exactly like the US version in regards to starter held items. However, we as developers don't really test the non-US versions of the games, and we're fairly sure that support for non-US ROMs is pretty shoddy overall. In fact, this particular bug originates from Dabomstew's original implementation of the randomizer before we forked it, because we've never touched *anything* in regards to starter held items until now. Ideally, things *should* work on non-US ROMs, but realistically there are probably a lot of issues like this, *especially* with the pre-Gen 4 games.
