### ISSUE TITLE
[Bug] Failed Save with Platinum 

### ISSUE THREAD

**Issue by DragonARandom** [Ajarmar/universal-pokemon-randomizer-zx#224]
When saving a randomized Platinum, it will come up with an error. I would change a few things, but the same error would show up. Does not happen with other roms. 
[error_2021-06-17-16-52-59.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6673418/error_2021-06-17-16-52-59.txt)

**Comment by tom-overton** [comment]
Is this some sort of ROM hack? I noticed some things in the ROM Diagnostics that do not match mine.
Yours
```
arm9: C9B3B4D9
```

Mine
```
arm9: 4D104949
```

**Comment by DragonARandom** [comment]
It should not be, the only rom hack I have every done was Radical Red.

**Comment by tom-overton** [comment]
Hmm, strange. Well, your exact seed and settings combination works for me. Here's the log that it generates:
[test.nds.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6673586/test.nds.log)

The issue is that when we attempt to randomize static Pokemon, we try to randomize the fossil Pokemon as part of that. When we try to read the fossil table from your ROM, it's not where we expect it to be (or it's corrupt in some way) which causes the failure you're seeing. If possible, please try a different Platinum ROM and see if it works for you. Regardless of whether this ROM is corrupt or not, it's certainly not what the randomizer expects out of a US version of Platinum.

**Comment by DragonARandom** [comment]
Thank you so much! That worked!
