### ISSUE TITLE
[Contribution Idea] Shiny related options

### ISSUE THREAD

**Issue by YahaTheMajin** [Ajarmar/universal-pokemon-randomizer-zx#228]
I was thinking that some shiny related options would be nice,if they are possible.
For example a slider to change the odds of finding a shiny,maybe a slider for opponent mons too,making certain important characters have a shiny like the champion or a certain number of trainers in the whole game.
(also some color change options would be cool,for when we randomize types maybe)
Also shinies could swap with normal mons but that would be kinda pointless if theres a slider,since we could set it to 90% and make normal mons rare,but if theres no slider thats an idea too.

This would make it a bit more exciting in my opinion,especially since randomised playthroughs are usually short,so finding a full odds shiny is near impossible.Plus the fact that trainers never have shinies is a bit dissapointing.

**Comment by MrTablez** [comment]
Hi, I'm incredibly new here, so I can't really speak to what this program is truly capable of doing; but have been mucking around with ROM modification for a while now. If you want these features like RIGHT NOW, I'll link a tool I found from a ROMHacking forum that modifies the pokemons color palettes for NDS games, with options to make colors match their types: https://www.pokecommunity.com/showthread.php?t=345129. 

For GBA and 3DS, the answer is a little more complicated. The only tool I've found that ranomizes sprite palettes for GBA is an Emerald specific Randomizer. After testing, I have confirmed, it most certainly is not compatible with fire red for color randomization. 
![Hmm That Didn't Work](https://user-images.githubusercontent.com/86182321/122998364-caa48480-d361-11eb-9022-51d7d013a86e.PNG)
![Really Didn't Work](https://user-images.githubusercontent.com/86182321/122998377-cd9f7500-d361-11eb-9825-dfabfb1c4dc6.PNG)
(That charmanded is rock type and that rattata is supposedly rock/steel type. Additionally, the only reason I'm not showing the rattata in my party, is because whenever you throw a pokeball, the game crashes and boots you to the title screen.)

To get a non-emerald GBA randomizer, someone would either have to write one from scratch, or possibly cannibalize the color palette changing section of the emerald randomizer found here: 
http://artemis251.fobby.net/downloads/emerald/

The problem with that is, its old. Like, really old. I recently tried to break it open myself for a project I'm working on (proposed here if you're interested, https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/225), and could not compile it from its source code, since one of the libraries it was written using was discontinued for support over a decade ago. 

As far as 3DS games, I genuinely have no experience there. I would think it'd be much harder; since you're not just dealing with sprite palettes anymore, but entire 3d models. I also couldn't find any tools online, but I didn't look particularly hard either.

Now, about shinies. The emerald randomizer I mentioned previously, alludes to the fact that the shiny percentage isn't an easy thing to change, 
"- Mess with the shiny rate
I couldn't find anyone professing to know where to change the rate for shinies, but it'd be cool to set it to whatever you want. :)" (from a readme file in their source code). However, this was written a decade ago, so maybe it's been figured out by now? (That code actually includes an option to make color changed Pokémon appear as their base colors if they're shiny, so maybe you could work backwards from the check if a pokemon is shiny, and find where the shiny creation takes place?) But I myself, haven't seen the option implemented anywhere else, so It'd likely have to be a brand-new endeavor.

**Comment by YahaTheMajin** [comment]
Im aware of these color palette programs but the colors are just a minor addition to what i was suggesting,the main thing are the shinies 
(also i forgot to add that by changing colors we could make the shinies different as well and make the normal ones shiny colored)
By the way those programs dont do a very good job usually,mostly in gen 3 games. The sprites become quite ugly half the time

**Comment by Ajarmar** [comment]
The `Contribution Idea` issue template is meant for ideas you have that you can contribute yourself to the codebase, not for ideas that you want us to implement. We don't take feature requests.

Regardless, if I've misinterpreted your message and you actually meant that these would be things you would contribute yourself, I'd still have to dismiss the suggestions. We already have a feature for adding a chance for Trainer Pokemon to be shiny in Gen 7. In generations before that, it's more or less impossible to do that. As for the other suggestions, I don't really see the point - as you say, palette randomization usually looks pretty bad, and modifying shiny rates doesn't really seem like a randomizer feature to me.
