### ISSUE TITLE
Ultra Beasts Swappable

### ISSUE THREAD

**Issue by White14000** [Ajarmar/universal-pokemon-randomizer-zx#23]
Recently I randomized pokemon ultra moon and completed it. When I entered an ultra wormhole and encountered an ultra beast, I found out that the "Swap Legendaries & Swap Standards" does not work for ultra beasts and instead of getting an ultra beast I ended up getting a random pokemon. I don't really want to bother a lot with this because this is most likely still in development and I'm happy that you guys were able to create this amazing program. Thank you for the attention and keep up the good work!

**Comment by Ajarmar** [comment]
Ultra Beasts not being considered legendaries for this setting is intended, as they are not considered to be legendary in the games. However, they are not entirely regular either, so I agree that the setting might not work in a completely satisfactory way currently; I think we might change it so that when that setting is used, all Ultra Beasts are swapped for other Ultra Beasts.
