### ISSUE TITLE
Horde battles spawn the same pokemon[Help] 

### ISSUE THREAD

**Issue by scliff0rd** [Ajarmar/universal-pokemon-randomizer-zx#237]
Hello, not sure if this is a "me" issue with my randomizing settings.. but I randomized omega ruby and whenever I enter a horde battle, the same pokemon fills the 5 wild encounters. EX: 5 swampert or 5 quagsire or 5 magby etc. When I randomized the game, the wild pokemon were set to be fully random with "none" selected for additional rules. I have changed the catch rate, allow randomized held items, ban bad items, upped the level mod by 10% and allow alternate forms.

Idk why my hordes only give me 5 of the same pokemon, but it could also be horrendous RNG lol but its every horde battle. Any thoughts would be very helpful.

Thanks!

**Comment by tom-overton** [comment]
Don't worry, this isn't a "me" issue; you're running into something that's fairly obscure about ORAS. When you have the DexNav open, you'll see sprites on the bottom screen showing what Pokemon are available in the area. It turns out if the game attempts to put 19 or more sprites on this screen, the game crashes as soon as you load the area. Thus, the randomizer has to be very careful about how it places Pokemon on certain Routes in order to prevent crashes.

Some areas of the game already are basically at the limit, so we can't actually increase the number of species in the area. Routes 102 and 103 are two really obvious ones since they occur super early in the game. Meanwhile, other areas have a lot of room to breathe, so we can add more Pokemon in the horde. I just made a seed for testing purposes and the uncommon horde on Route 112 had five distinct Pokemon in it, for example:
```
Set #122 - Route 112 Uncommon Horde (rate=1)
Gulpin Lv8               HP 70  ATK 43  DEF 53  SPATK 43  SPDEF 53  SPEED 40 
Slurpuff Lv8             HP 82  ATK 80  DEF 86  SPATK 85  SPDEF 75  SPEED 72 
Porygon2 Lv8             HP 85  ATK 80  DEF 90  SPATK 105 SPDEF 95  SPEED 60 
Metapod Lv8              HP 50  ATK 20  DEF 55  SPATK 25  SPDEF 25  SPEED 30 
Squirtle Lv8             HP 44  ATK 48  DEF 65  SPATK 50  SPDEF 64  SPEED 43 
```

I'm guessing you're testing on early routes where we're very limited in how many Pokemon we can add to the area without crashing. That's pretty much what you're seeing. Unfortunately there's nothing the randomizer can really do to get around this; it's an issue with the original game. So I'm gonna close this as there's nothing I can do to help. At least you know *why* it's happening now.
