### ISSUE TITLE
[Bug] bound must be positive / typeThemeTrainerPokes / Weight Types by # of Pokemon

### ISSUE THREAD

**Issue by Sheypex** [Ajarmar/universal-pokemon-randomizer-zx#244]
**Describe the bug**
Randomizing pkmn Alpha Sapphire (USA) v1.4 with Type Themed Trainer Pokemon and "Weight Types by # of Pokemon" fails with "java.lang.IllegalArgumentException: bound must be positive"

**To Reproduce**
Game used: pkmn Alpha Sapphire (USA) with update 1.4,
Settings: [Pkmn_alpha_sap.rnqs](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6801878/Pkmn_alpha_sap.rnqs.txt)  (uses Type Themed Trainer Pokemon and "Weight Types by # of Pokemon")
Produces Error: [error.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6801895/error_2021-07-12-15-40-23.txt)

**Expected behavior**
Should have worked without failing.

**System (please complete the following information):**
 - Operating System: Win 10
 - Java Version: Version 8 Update 291
 - Randomizer Version: v4.2.1

**Additional context**
I tried turning "Weight Types by # of Pokemon" off and it works fine.

**Comment by Sheypex** [comment]
Noticed something more:
Tried to use these settings [Pkmn_alpha_sap.lvl_mod.rnqs.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6809836/Pkmn_alpha_sap.lvl_mod.rnqs.txt) on pkmn Alpha Sapphire 1.4:
* worked fine ✔️ 

**Then:**
Loaded these settings, and without changing the settings after, tried to randomize again:
* didn't work ..? ❌ 
* [error.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6809842/error_2021-07-13-17-01-42.txt)

**Comment by tom-overton** [comment]
You've managed to discover a pretty wild edge case. Your settings (at least in the first error log) ban Gen 1 and 2, which means that there are no Bug or Poison mega evolvables in the pool. Since you have Type-Themed Trainers turned on, this occasionally presents a problem, The reason why you inconsistently crash is because sometimes you have a trainer that is typed to be Bug or Poison that has a Mega Evolution, and sometimes you don't. In the first error log, you're crashing because the Sidney rematch is typed to be Bug.

Unfortunately, actually "fixing" this problem by rerolling the type in these error cases would require a significant rework of how Type-Themed Trainers work, and it doesn't make much sense to do that for such a niche error case. What we've done instead is check that there's a mega evolvable of every type in the pool; if there isn't, then "Swap Mega Evolvables" is not allowed with Type-Themed Trainers. This change will be in the next release, but if you want to prevent these crashes before then, either turn off "Swap Mega Evolvables" or add Gen 1 in Limit Pokemon.

**Comment by Sheypex** [comment]
Interesting, thanks for the quick fix :D
