### ISSUE TITLE
Pokemon Not Evolving?

### ISSUE THREAD

**Issue by PhantomSpiritomb** [Ajarmar/universal-pokemon-randomizer-zx#247]
I was playing a randomized version of Pokemon Ruby and Sapphire with my friend on Discord. However, while we kept playing none of my pokemon were evolving. 

Here's a link to the randomized settings and save file I'm using: 
[Evolution Issues.zip](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6834030/Evolution.Issues.zip)

If at all possible please just look into this and see what might be causing this bug, or if this is on my end.

**Comment by tom-overton** [comment]
Do you have a log for this seed?

**Comment by PhantomSpiritomb** [comment]
> Do you have a log for this seed?

I sadly don't have the log

**Comment by tom-overton** [comment]
OK, I took a look at your settings file and I figured it out. You have Limit Pokemon turned on; specifically, you ban everything that isn't from Gen 3. As part of how we Limit Pokemon, we remove the evolutions from Pokemon that are banned. This is normally totally fine, because they're banned and thus you will never have them. However, through some unknown means, you have a party almost entirely full of Pokemon that your settings ban, hence why most of them won't evolve. I assume you're trying to evolve the Mareep and the Mankey, but they will never ever evolve because of your settings.

To demonstrate that evolution in general isn't broken, the Marshstomp can evolve just fine (since it's from Gen 3):
![Audrey-0](https://user-images.githubusercontent.com/12245827/126117845-654becaf-7ebb-4743-a3f0-d97dcce7ce3e.png)

I really don't know what exactly you're trying to do with your settings or how you ended up in the situation you did, but if you're going to use Pokemon from Gens 1-2 in your party, you need to unban them in Limit Pokemon. Otherwise they won't evolve.
