### ISSUE TITLE
[Bug] (Platinum) Some Randomized Intro Pokemon can cause a crash

### ISSUE THREAD

**Issue by SilverstarStream** [Ajarmar/universal-pokemon-randomizer-zx#254]
**Describe the bug**
On one randomized ROM, once the Pokeball was opened during Platinum's introduction, it caused a crash on a hacked 3DS console using TwilightMenu++. To double-check, I tested the ROM on DeSmuME 0.9.11. The game did not crash on the emulator, and continued through the introduction normally without any Pokemon sprite.

**To Reproduce**
To look into this issue further, I built the randomizer from source. I noticed that randomizeIntroPokemon() looks to write to prefixes "381CF8BDC046" and "08B0F8BD" within arm9overlay[73], specifically for Platinum's constants. After poking around in my randomized ROM, it appeared that the number 238 (Smoochum) was correctly written to both locations. After forcing the randomizer to always use 238 as introPokemon in randomizeIntroPokemon(), I was able to reproduce the error.
I tested further with 327 (Hitmontop), 329 (Elekid), other baby Pokemon, and Jynx. Only Jynx (124) caused the same issue. After Jynx caused the issue, I checked other nearby Pokemon: Scyther (123) and Electabuzz (125), and neither of these numbers caused issues. From my testing this error appears to be settings-independent.
I also tested it with Gen 5; the issue did not appear here with Smoochum.
Here is my log from the initial randomization, for the seed and settings. I did not generate the premade seed file.
[Platinum Ironmon 04.nds.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6880824/Platinum.Ironmon.04.nds.log)

**Expected behavior**
The introduction progresses normally with a randomized Pokemon sprite.

**Screenshots**
For completeness, here is a screenshot from just after the Pokeball is opened on emulator.
![randomizer_issue_scrshot](https://user-images.githubusercontent.com/46911095/127051571-d2139699-0493-40d1-a0df-c177d716235f.png)

**System (please complete the following information):**
 - Operating System: Windows 10 [Version 10.0.19041.1110]
 - Java Version: Java version 8 update 291 (build 1.8.0_291-b10)
 - Randomizer Version: v4.2.1 (and v4.2.2-dev)

Please let me know if there's any more information I can provide.

**Comment by tom-overton** [comment]
Thanks for the very detailed report! If every issue was as detailed as yours, my work would be a lot easier.

You've stumbled into a very interesting edge case involving Gen 4 sprites. When Gen 4 attempts to load a sprite, a parameter is supplied that tells the game to load either the "default" sprite (for male Pokemon, or Pokemon of undetermined gender) or the "female" sprite. Female-only Pokemon like Jynx and Smoochum don't have a "default" sprite; they *only* have a "female" one. The intro code passes the "default" parameter when loading the sprite, which results in exactly what you've discovered; the sprite doesn't show up on emulator, and the game crashes on real hardware. This is not the first time we've ran into this (see 674caaf89799a8470d296dd3c8d1ebac92bc7c0f) so I probably should've caught this earlier.

Modifying the intro code to pass the "female" parameter instead of the "default" one is actually pretty hard, so instead I just decided to ban female-only Pokemon from appearing in the intro as of the next release. For now, you can use v4.1.0, which doesn't randomize the intro Pokemon at all, or you can just reroll the seed if you run into it again.
