### ISSUE TITLE
[Help] My NDSi can’t run a randomized ROM of Pokemon White 2 (Spanish).

### ISSUE THREAD

**Issue by TmsTzz** [Ajarmar/universal-pokemon-randomizer-zx#258]
Hi!
 I wanted to randomize a ROM of spanish Pokemon White 2, but when I try to run it on mi NDSi, nothings happens, because the size of the ROM changes, going from 512MB to 274MB. The original ROM runs perfectly, so I think the problem here is the size of the archive. 

Here are the Random Seed, the Config String, OS, and Randomizer’s version:

- Random Seed: 108542387136372

- Config String: 316IygEAQTuAfEB9AEEAAGoRAABFAAAFABABAABAAAAAAAAAAAA5AS8AQAICTIHBwDGABNQb2tlbW9uIFdoaXRlIDIgKFMpWRDTw+PDOIo=

 - Operating System: Windows 10
 
 - Randomizer Version: 4.2.1

 Here is the log file:
[Pokemon White 2.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6896441/Pokemon.White.2.log)

 Thanks in advance, hope I can play a harder version of W2 soon. See you!

 UPDATE!

 I figured out that I can play, disabling the Soft Reset (I play it on R4), but I can not use the C-Gear (frozes the game).
 If I could randomize the ROM without getting the MB reduction, I can access to the C-Gear.

 That is all. Goodbye!

**Comment by tom-overton** [comment]
Yeah, the DS ROM handling code in the randomizer strips the game of DSi binaries (because, when it was written, the DSi did not exist). So I assume that's what you're running into in regards to the C-Gear.

I'm going to close this issue for now because you figured out a way to get it to run. We know the randomizer is stripping the DSi binaries but it's a very tricky problem to solve for probably little gain. For the record, DS games shrinking in size is expected even with the Gen 4 games, which don't support the DS; a large portion of the average DS ROM is useless empty space that we deliberately strip out to shrink the size of the ROM.
