### ISSUE TITLE
[Bug] Error when Randomizing german Black Edition

### ISSUE THREAD

**Issue by denaggels** [Ajarmar/universal-pokemon-randomizer-zx#259]
Randomizing my german Pokemon Black file results in an Error.

Open Rom
Changing settings doesnt change outcome
Randomize
Error
![Error Message Ajarmar 4 2 1](https://user-images.githubusercontent.com/81873853/128003824-996f50f5-b4ad-4784-867f-2e18a439fcaa.png)

**System (please complete the following information):**
 - Operating System: Win 10
 - Java Version: Most Recent
 - Randomizer Version: 4.2.1

[error_2021-08-03-12-50-56.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/6923527/error_2021-08-03-12-50-56.txt)

**Comment by denaggels** [comment]
just read the latest commits. i guess this will be fixed by banning randomization of roaming pokemon?

**Comment by tom-overton** [comment]
Yep, that's exactly correct. Foreign versions of BW1 are broken because they don't store the roaming Pokemon information in the same place as the US version and I didn't account for this. I fixed it in 8d6abcb10655a1ce42c7cb154653bfaf90776187 by simply banning them from being randomized in foreign versions. Unfortunately, there's no way to specifically turn off roamer randomization in v4.2.1; until the next version comes out, you have the following choices for now:
- Use v4.2.0 with German Black. It should work fine, and because v4.2.1 was a pretty small release, you won't be missing much
- Use v4.2.1, but *don't* randomize Static Pokemon with German Black. This will prevent the roamers from being randomized, which will prevent it from crashing
- Use v4.2.1 with US Black

Sorry for the inconvenience! Hopefully one of these options works for you.

**Comment by denaggels** [comment]
regarding your second point: i did not randomize anything for this bug to occur. so not randomizing statics didnt help
