### ISSUE TITLE
[Bug] Exception when trying to load a game update (Pokemon Y)

### ISSUE THREAD

**Issue by FerdinandoPH** [Ajarmar/universal-pokemon-randomizer-zx#260]
**Describe the bug**
When I select a game update for pokemon y, the app doesn't do anything. An exception error appears in the console. The output layeredFS folder crashes when playing the game with the update

**To Reproduce**
Open a Pokemon Y rom
Click on load update
Select the update file

**Expected behavior**
The update should load.

**Screenshots**

![Captura de pantalla (27)](https://user-images.githubusercontent.com/29411787/128074245-553313b9-7502-4afa-a1e0-220c70aec4f5.png)

**System (please complete the following information):**
 - Operating System:  Windows 
 - Java Version: 8 update 291
 - Randomizer Version: 4.2.1

**Additional context**

**Comment by tom-overton** [comment]
Are you sure that your game update is valid? The issue presented in the console indicates that we couldn't find a title ID in the game update. Is it a CIA file? Did you dump it via GodMode9?

The game crashing in this instance is totally expected so it's not the issue here. I'm trying to figure out if our 3DS filesystem code is wrong or if the update file is bad.

**Comment by FerdinandoPH** [comment]
I dumped the update file from my 3ds, used it in the app and it worked, so I guess that the problem was that the update file I was using before was corrupt. Thank you for your help!
