### ISSUE TITLE
Randomising Sun and Moon

### ISSUE THREAD

**Issue by Haliteboi** [Ajarmar/universal-pokemon-randomizer-zx#268]
**Universal Pokémon Randomizer 4.2.1**
I was randomizing a Pokémon Sun rom, after saving the files and allowing the randomizer to randomize the rom. The screenshot below  and a note page popped up in "additional information".

**To Reproduce**

**Expected behavior**

**Screenshots**
![Randomise save Sun and Moon](https://user-images.githubusercontent.com/89270634/130269944-b1b38a89-01ae-4e62-9fdd-7fb62b204911.PNG)

**System (please complete the following information):**
 - Operating System: 64-bit operating system, x64-based processor
 - Java Version: 8 Update 301
 - Randomizer Version: 4.2.1

**Additional context**
Randomizer Version: 4.2.1
Seed: 161960015055708
Settings String: 316OygEAULRAtQC1wIEAASqhhhECgAAFAA9CQABYgAAAAAAAoAIMkkywRQQ0jIICAAyAwtQb2tlbW9uIFN1bjIE9WrjwziK
Java Version: 1.8.0_301, Java HotSpot(TM) 64-Bit Server VM
ROM: Pokemon Sun
Code: CTR-P-BNDA
Reported Support Level: Complete

java.lang.NullPointerException
	at java.util.TreeMap.put(Unknown Source)
	at java.util.TreeSet.add(Unknown Source)
	at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.pokemonInArea(AbstractRomHandler.java:5326)
	at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.area1to1EncountersImpl(AbstractRomHandler.java:1102)
	at com.dabomstew.pkrandom.romhandlers.AbstractRomHandler.area1to1Encounters(AbstractRomHandler.java:916)
	at com.dabomstew.pkrandom.Randomizer.randomize(Randomizer.java:450)
	at com.dabomstew.pkrandom.newgui.NewRandomizerGUI.lambda$performRandomization$105(NewRandomizerGUI.java:880)
	at java.lang.Thread.run(Unknown Source)

--ROM Diagnostics--
.code: DE47EF73
romfs header: 71757A90
Battle.cro: D582C507
a/0/1/1: 1E3831AE
a/0/1/3: 4DA9DF72
a/0/1/4: FCEBEEE5
a/0/1/5: 4001BBAB
a/0/1/7: 81A28B5B
a/0/3/0: 2F51F38A
a/0/3/1: F7CF2BDC
a/0/3/2: 25353D7C
a/0/3/3: 8D0E205C
a/0/3/4: B4E7E4AC
a/0/3/5: 0D5BA0F6
a/0/3/6: 8C0D486A
a/0/3/7: 9ACCE086
a/0/3/8: F65F8202
a/0/3/9: E0110F4D
a/0/4/2: 4E9DB200
a/0/6/2: 7B1D8B2A
a/0/7/7: 76C0FCE0
a/0/8/2: 9A8FA037
a/0/9/1: 8B6B447D
a/1/0/5: 68242669
a/1/0/6: 618505F1
a/1/5/5: 7E3092FF

**Comment by tom-overton** [comment]
I can successfully randomize Pokemon Sun using this exact seed + settings combo:

[test.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/7023342/test.log)

This error was thrown because when we were reading encounter data from the ROM, we got some improper value for a Pokemon's species ID. Looking at your ROM Diagnostics, I see some notable discrepancies, including in a/0/8/2, where wild encounter data is stored.

Yours:
```
romfs header: 71757A90
a/0/1/4: FCEBEEE5
a/0/3/2: 25353D7C
a/0/4/2: 4E9DB200
a/0/8/2: 9A8FA037
a/1/0/5: 68242669
a/1/0/6: 618505F1
```

Mine:
```
romfs header: EE3DB972
a/0/1/4: 4732336F
a/0/3/2: 7C6240E6
a/0/4/2: B651F900
a/0/8/2: C25E1A15
a/1/0/5: 51FC0767
a/1/0/6: 2F5EFBF1
```

Is this some sort of ROM hack?

**Comment by Haliteboi** [comment]
Hi tom-overton,

Thanks for your reply. This is a Pokemon Sun Rom Hack downloaded for Citra.

**Comment by tom-overton** [comment]
Sorry, but we don't officially support ROM hacks, because they can have their internal data modified in ways that are incompatible with the randomizer, which is exactly what you're seeing here. If you can contact the author of this ROM hack, you can ask them to investigate making it randomizer-compatible. Otherwise, there's nothing that can really be done here.
