### ISSUE TITLE
[Bug] Error randomizing gen 7 games

### ISSUE THREAD

**Issue by Sour-Slug** [Ajarmar/universal-pokemon-randomizer-zx#270]
**Describe the bug**
When going through the steps I normally take to randomize my games for my friends and I, the gen 7 games fail on the last step. Specifically Pokemon Moon and Ultra Moon. I have not tried Sun or Ultra Sun. When I randomize our games I first randomize the game with only changing evolutions. I normally then load that newly randomized evolution rom back in and randomize abilities, and other options I would like to stay the same across all our games. Like trainer class names and Shop items. The reason for the first step is because I run into errors where abilities don't properly follow evolutions if chosen at the same time. Finally I load that second randomized rom back in and randomize starter pokemon, and statics. Change trainer pokemon and wild pokemon. And apply settings like make evos easier and fastest text. I get an error on the last step.

There is probably a much nicer way of doing this. but this gives me randomized games that have all the pokemon be the same across games, but we all get different starters and wild encounters, and battles.

**Expected behavior**
Game will randomize and change wild encounters and trainer pokemon while keeping previously chosen random options.

**System (please complete the following information):**
 - Operating System: Windows 10
 - Java Version: Java Version: 1.8.0_291
 - Randomizer Version: 4.0.2

**Additional context**
I tried my same steps for Pokemon X and it worked fine. It also worked for Pokemon Leafgreen. It also worked once for Moon. But I had to redo it because I forgot to set evolutions to same type. It would no longer work after that. For context I get a worse error on the newest release, where it fails to even read the first randomized game. It reads an already randomized leafgreen fine.

I will link the randomizer output files in order until the error

First Run
[base1.cxi.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/7030051/base1.cxi.log)

Second Run
[base2.cxi.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/7030056/base2.cxi.log)

Final Run with error
[error_2021-08-23-03-01-36.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/7030061/error_2021-08-23-03-01-36.txt)

**Comment by tom-overton** [comment]
Let me note something *very* important: while I did attempt to fix this (or at least I think I did), what you're trying to do is **not** supported by the randomizer. There's no guarantee that future updates won't break this scenario again. We explicitly do not support re-randomizing an already randomized ROM and likely never will. That it works in games like LeafGreen and X is simply accidental. The *only* reason I took a look at this and fixed it is because I believe it has to do with how we handle alt formes, which is something I want to clean up a bit in the future. Since this was related, I figured I'd get to the bottom of this issue and try to understand what's happening.

That all being said, I think this *might* work when the next release of the randomizer comes out? As I said before, we do not explicitly support this scenario so no promises, but I think I understand what the problems were.
