### ISSUE TITLE
Wild Level Mods Not Working - Crystal and FireRed

### ISSUE THREAD

**Issue by ProPokeNoob** [Ajarmar/universal-pokemon-randomizer-zx#28]
Hello! I went to randomize Pokemon Crystal and FireRed and used the Percentage Level Modifier slider under "Wild Pokemon". After playing fully through both runs, neither game seemed to have the levels in the wild increased.

**Comment by tom-overton** [comment]
In regards to Pokemon Crystal, it appears that you're right, at least for certain types of encounters. It looks like the very common grass or sea encounters do *not* respect the setting to raise or lower wild levels, but things like fishing and the bug catching contest encounters *do*.

As for FRLG, can you provide a log file demonstrating this? I tried to replicate the issue on my own end and I'm seeing no issue with the setting. Here's a screenshot of a Pokemon from Route 1 when I enabled a 50% level increase (Route 1 Pokemon usually cap at level 5):
![test-0](https://user-images.githubusercontent.com/12245827/95616551-cf691880-0a1e-11eb-9f25-08c4fc31e9e9.png)

And here's the log file for that seed:
[test.gba.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5356764/test.gba.log)

**Comment by tom-overton** [comment]
I marked this issue as fixed with my commit because it fixes the Gen 2 problems I described above. It will go out with the next release of the randomizer. Like I said before, I don't see anything wrong with FRLG; please note that it was broken prior to 3.1.0, so be sure to use that version or later. If you can provide a log showing the problem for FRLG on 3.1.0 or later, I'll be happy to take a look!

**Comment by ProPokeNoob** [comment]
Awesome, thank you! I probably didn't pay enough attention to the FireRed levels and that's my bad. Keep up the great work :)
