### ISSUE TITLE
[Contribution Idea] Additional options for base form starters

### ISSUE THREAD

**Issue by Poppyanimal** [Ajarmar/universal-pokemon-randomizer-zx#280]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** 
----------------
This would add the options of base pokemon with only one evolution (1st stage of 2) and base pokemon with no evolutions (1st stage with no evos) to the starter selection choices

**What problem would your contribution solve? Please describe:** 
----------------
This would fill the gap present by having basic pokemon with 2 evolutions but no other basic pokemon starter selection options

**Additional context:**
-------------------
I'd also be willing to setup an option for any basic pokemon, regardless of evolutionary length as an option for starters but due to it possibly crowding options I leave that open for discussion.

**Comment by tom-overton** [comment]
The reason why "Basic Pokemon with Two Evolutions" exists is because that's how it is in the base game. It seems really overkill to include one setting for every possible amount of evolutionary stages. I think *maybe* an "only starters that can't evolve" could be fine (hence I'll leave this idea open for now), but even then, I'm not sure.

**Comment by Poppyanimal** [comment]
I see... in that case I'll discard the idea entirely if the only part that isn't a no is an unsure.
