### ISSUE TITLE
I can't use the  Windows launcher.

### ISSUE THREAD

**Issue by NOTDabasaur4** [Ajarmar/universal-pokemon-randomizer-zx#287]
When I try to use the launcher its says "Error: Unable to access jarfile PokeRandoZX.jar" then press any key to exit. Is there a way to fix this or not?
![image](https://user-images.githubusercontent.com/89703523/131226196-a8159a3f-e056-4ac0-ad34-05da5ff03b5e.png)

**Comment by tom-overton** [comment]
We have issue #221 for troubleshooting launcher issues. Your issue is one of the ones we don't *really* know a ton about, but we're pretty sure it's related to file permissions; try moving the randomizer to a different folder. See the first post of the linked issue for more information, and feel free to post there with further issues you run into.
