### ISSUE TITLE
[Contribution Idea] Entrance Randomization

### ISSUE THREAD

**Issue by SilverstarStream** [Ajarmar/universal-pokemon-randomizer-zx#290]
**Is your idea a new setting, a change to an existing setting, or something else?**
This is a new setting for the randomizer, which is taken from other randomizers.
Entrance randomizer usually means that when the player enters a loading zone, they are sent to some randomized location.
I've split the general "entrance randomizer" concept into three settings: map randomizer, gym shuffler, and Elite 4 shuffler.

I'll try to describe the map randomizer as completely and concisely as I can. The randomizer starts with "Locations". Each Location represents some area of the map that is completely separated by loading zones (like a route(s), or a city). The loading zones that connect to other Locations are called "Exits". To create the randomized map, the randomizer takes random Locations and connects them together by their Exits. This is done in a way where all Exits are connected, each pair of Exits that have been connected only connect to each other, there are no small loops, and the game is completable. This creates a new (and hopefully interesting) map for the player to traverse. This setting scales the levels and evolutions of wild Pokemon and trainers in every Location to the badge the player could have.

Gym shuffler changes which gym is found in each city, and maintains game completability by properly shuffling the badge received and other events related to obtaining the badge. This setting scales the gym trainers' levels and evolutions to the badge. Since gym leaders act as a sort of boss, I believe that their team should be carefully selected, so I wrote a text file that the randomizer parses that defines which Pokemon (and its properties) each leader should have for each gym. This would allow for these fights to be easily edited and shared by users. My plan is to have 1 text file for each game, with sister versions sharing. That makes it 12 text files for Gens 1-5 for example, unless more become shared.

Elite 4 shuffler is the simplest and least interesting. It shuffles the rooms of the Elite 4, meaning a random Elite 4 order in games with a linear Elite 4. In games where the Elite 4 order is non-linear, the rooms could certainly still be shuffled but for a minimal effect. This setting scales the levels of each member's team to their position.

**What problem would your contribution solve?** 
Since this is a new feature, this is less about solving a problem and more about bringing in a type of setting from other randomizers to Pokemon. I believe that some players would enjoy these types of settings. This is especially true for the map randomizer, as it fairly drastically changes traversal and which Pokemon are available at what point in the game when wild encounters aren't randomized.

**Unsolved challenges**
I wanted to add a section to mention the issues that still exist with what I've put together so far.

Potential for softlocks: While the map randomization code is (sarcasm) definitely bug-free and accounts for all cases and always outputs a completable map, there is still a possibility that players could softlock. One issue I discovered from testing the map randomizer is that the player is forced to take a step after taking stairs that are part of a screen transition (Gen 4). Since the player would step into a randomized map in an unintended direction, it might force the player to step into a soft-lock, or allow the player to step out-of-bounds with no way to get back in-bounds. I was able to change the stair tiles to normal entrances that don't force a step forward, which should have solved the issue, but I'm not certain that there's not some edge case that could still come up. It just needs to be tested further.
I also haven't tried out-of-order completion. From what I've observed, a lot of story progression and events are tied to multiple values the game keeps track of. These values generally seem to be local to areas, reducing the chances of out-of-order issues, so the game already allows for some out-of-order completion. I'm optimistic that little has to be done for this.

Map construction failure: My map construction algorithm doesn't create a perfectly closed map every attempt, since I want the map to use every Location and have no loose Exits. It also has rules to prevent something like needing Surf to progress without being able to access it. When it detects either of these conditions, it stops the map generation and tries again until it succeeds. Last I checked it has about a 70% success rate for any given attempt.

Fantina's Gym: In Platinum, Fantina's gym has a darkness effect that hinders the player's navigation. This darkness effect is practically removed once Fantina is defeated. From my testing, this effect seems to read whether the player has the 3rd badge, and doesn't seem to be tied to any event value. I still need to figure out where in the ROM this check is to solve this. It doesn't hurt gameplay in a very significant way, but it is something janky that should be taken care of.

**Additional context:**
To be up-front, I've already written the code for these three features, but only for Platinum so far. I realize that you would typically want me to propose an idea first and then implement it after some discussion. However, I wasn't aware of ZX until somewhat recently and was already building on the original Dabomstew fork (honestly ZX isn't the easiest to find and I think it's not a very well-known fork, but that's not a discussion for here). Since I'm close to finishing this feature for Platinum, I wanted to figure out how I would release it.
Right now I see two options for releasing what I've worked on: either a stand-alone application that would maintain compatibility with the randomizer, or adding it as a setting to the randomizer, potentially as my own fork.
I'm leaning towards adding it as a setting to the randomizer, for a few reasons. My code heavily relies on the existing randomizer's codebase (how RomHandlers are set up, any decryption/unpacking that is handled, and certain functions that were already written). Also, users would likely want to randomize multiple aspects of the games in addition to entrances, which would be better to have all in one program.

Like I mentioned, right now I've only worked on Gen 4, and specifically only Platinum. Ideally I've prepared the code as best I can so that generations that aren't 4 can be easily added. Though I have not looked into how other gens handle entrances, so as new gens get added, I imagine bits of what I've written will have to be refactored.
Also, I think that it will take me quite a while to finish up the other gens for this feature. I also don't know which games I *won't* end up doing. For example Gen 7 almost certainly won't receive any map or gym randomization, since its locations are so heavily tied to story progress and there aren't traditional gym locations.

I wanted to write this issue to get feedback, suggestions, and a bit of guidance. I'm also curious about how much help and collaboration I would be able to get developing for the rest of the gens. Whether that's people working on other gens so the full feature is completed faster, or getting help when I get stuck from people more knowledgeable about the specifics of the ROMs, or if I'm more or less on my own.

Thank you for reading this, I realize it's a lot to read and I appreciate your time. I'm more than happy to answer any questions about what I've worked on or about any problems you might see.

**Comment by tom-overton** [comment]
Apologies for the long delay on responding to this: I wanted to make sure Ajarmar and I were on the same page before I started typing things up.

First off, this is very impressive work. Well done! I didn't think that this would be done for a long while. As for answering some of your questions and concerns, let's start up front with the big one: should this be part of ZX, or should it be a standalone application (either a fork or an entirely separate application)? In our opinion, it makes more sense to release it as a standalone application for the following reasons:

- **Only needs to work with one game**: We are a *universal* randomizer, so there's an expectation that features that we add will work across a variety of games. You have Platinum working, but users are generally going to expect that other games besides Platinum work too. This even applies to stuff like the Gen 7 games, since users might not be aware of the technical and design challenges that would come with entrance randomization. Adding this feature to UPR is committing up front to an enormous amount of work in supporting as many games and generations as possible, while releasing it as a standalone application means that you can add games at your own pace.

- **Only needs to work with one region**: This is sort of a downside with being a *universal* randomizer; people expect that things will work in all regions and revisions of a particular game, or at the very least don't break. We haven't really been the best at meeting these expectations. Our official stance is that the English versions are the only ones with full support, and we have occasionally broken non-English versions in releases because we simply do not test them often. In the current v4.2.1, static randomization is broken on some versions of BW1 because I didn't test roamer randomization with non-English versions. Being a standalone application means that you don't have to care about all of this; you can just refuse to load anything that isn't a US version (or whatever your preferred version is). If you start caring about other regions, then your work becomes rapidly multiplicative in nature, so my guidance here is to just pick one region and stick with it. If I were writing UPR from scratch today, I would simply only support the US versions.

- **Better support and release capabilities**: You've probably noticed that we don't really release all that often. If there's a bug with entrance randomization that needs to get fixed, it's hard to say when that fix will actually be made available to users. Being a standalone application means that you can release whenever you want. It also means that any issues or bug reports that people file will be relevant to entrance randomization; you won't have to sift through all the noise on our own issues tab.

- **Allows you to deviate pretty dramatically from convention**: A particular thing that gave Ajarmar and I pause is your plan to define gym leader's Pokemon and properties in text files. It's such a major departure from how the randomizer currently works that we're not really sure if some users will really comprehend it or understand how to read/change it. The only things that the randomizer takes as input right now as settings and names files, so adding a whole new type of file for one setting might be a little confusing to users. However, as a standalone application, you're free to set your own conventions.

- **Lack of experience/knowledge from UPR ZX devs**: Frankly, Ajarmar and I don't really know anything about how entrances and warps work in any of the games, so you likely wouldn't get much help at all. As an example, neither of us have an idea as to where to start in regards to the problem with Fantina's gym. We could potentially do some research, but we're not the fastest or most reliable devs (as should be noted by the fact that we're responding to this 22 days later, sorry about that!), so I doubt it would be very helpful. Making a standalone application means that you can potentially attract people who actually know about entrances and warps.

I've been saying "standalone application" this whole time, but as I said before, that can just mean a fork of UPR or UPR ZX. Using the RomHandlers, decryption, unpacking, etc. is easy with a fork. It also preserves the ability to randomize other aspects of the game too. However, you could also make it totally standalone and devoid of any randomization other than entrance randomization, too. If I had to pick one, I think the former approach is likely better for users.

I'm going to close this request because as discussed above, I think it makes more sense to release this outside of UPR ZX than as a feature within it. To get entrance randomization into a state that we're comfortable with (i.e., working across multiple games/potentially across different regional versions) would take a *long* time, maybe even years, and neither Ajarmar nor I really have a lot of knowledge or passion in this area. We can't really offer a lot of technical support or guidance on the feature, so it feels a little strange to have it be a part of this branch when the maintainers of said branch don't really have a firm grasp on it. Feel free to ask any questions or provide any comments that you want in here, though! This is a super impressive feature and I'm excited to see what comes of it.

(little P.S.: what happens when someone gets to a late game area pretty early? Can they catch a high-level wild and just crush the game? Will the trainers there slaughter them? I don't really have an answer for fixing this or a good way of handling it, but my feedback is to think on that; maybe gym trainers aren't the only things that need scaled levels)

**Comment by SilverstarStream** [comment]
Hey, I appreciate you getting back to me. It was definitely concerning to me having to wait for so long on a response, but I kept reassuring myself that you were just formulating a response since my post was on the lengthy side. Turns out I was right!

To summarize this post, I'll be bringing the first incarnation of entrance randomization for Platinum to a fork of ZX soon™. Actually this is what I determined I would probably do, as I thought about it more over the past few weeks. I still need to migrate from Dabomstew's repo to ZX, and up to now I've circumvented the UI and just worked from standard output, so I need to get that working. Turns out doing this worked in my favor since ZX changed the UI library from Dabomstew's.

To respond to some of the points:
* **Only needs to work with one game:** You're absolutely right about not being able to support every game, or at least not most games reasonably soon. I would love to have these features working across as many games as possible, but it will take a long time, as was pointed out. My own fork would certainly be better suited for incremental releases as I fix bugs and include more generations.

* **Only needs to work with one region:** Thanks for bringing this up, I'll keep this in mind. Other regions are something that I've always been aware about having to deal with eventually. I think I'll only reasonably be able to handle non-US regions if other people help with testing, or maybe they open a ROM editor and report on some values.

* **Allows you to deviate pretty dramatically from convention:** I made sure to mention the text file thing since I figured it might cause issues with whatever conventions you and Ajarmar want to have for the ZX program. The reason I wanted to use text files in the first place is because it feels like defining those values within the randomizer code is clunky, and I think some users would appreciate the potential for customization. But the convention thing doesn't matter within my own fork, for sure.

Addressing players finding routes "out-of-order": Route trainers and wild Pokemon get scaled when routes are randomized, so I've already taken care of that, mostly. It's separate from gym shuffling, where gym shuffling scales the gym's trainers. It's still entirely possible for a player to go into a route that has been scaled for late game and either break the game or get crunched. I don't have a great solution for this.
For Nuzlockers and challenge runners, I would say they should consult the spoiler log to know which routes to avoid, and use a self-imposed level cap so they don't break the game.
For those that don't fall into that category and don't want to consult the spoiler log, it's not devastating to enter a route, lose to one trainer, and then try a different path. If they want to catch an overleveled Pokemon and steamroll at least a portion of the game, that's on them.
To all of what I just said, I would love to have something in the modified ROM that can just deal with those problems. Maybe some kind of in-game dynamic scaler like in Crystal Clear, instead of one-time scaling done by the randomizer. Considering how little documentation seems to exist for most aspects of most generations, developing this would probably be hell to figure out, and not worth the effort*. Letting people play as they want seems like my best solution.

*Actually I can think of one way for dynamically scaling trainers with the current tools, in Gen 4. Though, it would be annoying to get working, and it could run into ROM limitations. Also I don't know where to begin with dynamically scaling wild Pokemon. I really doubt I'm going to explore this.

Thanks again for the response. I mostly wrote this up to put my own thoughts about everything out there.

**Comment by tom-overton** [comment]
Yeah, part of the delay was legitimately us crafting a good response, but both Ajarmar and I are sort of taking a break from the randomizer at the moment too, so it just took us a while to even begin crafting a response. Sorry about that!

Glad you've come to a decision in the meantime though! ZX changed the UI to work better with IntelliJ, which is what we both use, so yeah, you probably can't port over UI code from Dabomstew's original branch without some modification.

Responding to your some of your responses (lol):

- **Multiple regions**: In my experience, it's really difficult to get testing on these sorts of things. We have a group of people we send release-candidate builds to in order to test the randomizer before we release publicly, and nobody has ever tried to test non-US versions when we send it to them. Each game/generation is sort of unique in how different the non-US versions are from the US version, so it's a bit of a wild card how much extra work it would take to support entrance randomization in any given non-US version. For example, if you get to HGSS, I would strongly advise just skipping the Japanese version and maybe the Korean version too. The US and European versions of HGSS have the same script and text offsets, which means that you can *usually* get something working in all European versions if you get it working in the US version. However, the Japanese version has different script and text offsets, and the Korean version has the same script offsets but different text offsets. I'm 100% sure there's an undiscovered bug in ZX related to this somewhere. 

- **The text file stuff**: Yeah, that makes total sense. I can only imagine how gnarly it would be to define that stuff in Java code. We have some stuff defined in text files already (namely, the genX_offsets.ini config files) which get bundled into the final .jar, so you could *theoretically* do something similar with your text files. However, that would lose the customization angle unless users crack open the .jar themselves and edit them, but we probably don't want to encourage that. As you point out, it's totally a moot point in your own fork where you can do whatever you want, but I figured I'd offer that up in case it ever comes in handy. If you ever want to define something in a text file and *don't* want it to be user-editable, check out how the config files are handled.

- **Route/wild scaling**: Ah, great to hear you already got this (mostly) handled. I don't think there's a truly perfect solution outside of a dynamic scalar like you said, but what you have is probably good enough for the vast majority of people. I'm not sure what ROM limitations you're referring to, but we ran into some similar issues where we wanted to expand the arm9 executable. Ajarmar ended up coming up with a very clever way to expand it, [which you can read about here](https://docs.google.com/document/d/1OE8MP2_eST5GHABq1sQglDfam4lxsxqr27Luu-Z-pEY/edit). If that's not the limitation you were talking about, then oops, oh well. Still, it may come in handy at some point, so I figured I'd bring it up. You can also look at `extendARM9` in the randomizer code to see how we use it.

I hope the knowledge I provided here helps in some way. I'm excited to see your entrance randomizer in action! I'll check in on your fork every now and then and see how it's progressing. If you have any other questions or comments, feel free to reply here.

**Comment by SilverstarStream** [comment]
I've been thinking about some potential problems so I want to ask them while I'm thinking about them, even if it might be a little bit before I actually need to address them.

What do you do to build a release jar? Are there any settings I should be aware of?

In your opinion, should I add a new tab for entrance randomization settings, or should I just add the checkboxes under Misc. Tweaks? I don't like the idea of adding a barren tab that just has 3 checkboxes, but the settings are a little too significant to be put under the next-best category of Misc. Tweaks. Maybe opinion questions are a bit silly, but I'd appreciate some insight.

If a user wants to use an existing settings file, are there any problems from putting it in a different version of the randomizer with different selectable settings? How has/does the randomizer handled that type of issue?

**Comment by tom-overton** [comment]
To build the release jar, go to File -> Project Structure. In the "Artifacts" tab, make a new artifact (hit the + button), then make it look something like this:
![image](https://user-images.githubusercontent.com/12245827/136166497-29647eb9-6364-4e16-8d48-c0e9a43628b4.png)
Note that you'll also need to either rip out the code that looks for "-please-use-the-launcher", or you'll need to include the script launchers alongside the .jar. Otherwise, the randomizer will yell at users every time they boot that they didn't use the launcher.

I think making a new tab is fine. Load a Gen 1 ROM in the randomizer and it will have three things in the Items tab, so it wouldn't be the first time this happened.

If you load a settings file/string that's from an *older* version of the randomizer, we'll show a warning but load it. You'll need to make sure that the new settings you added are reflected in SettingsUpdater.java or the randomizer is likely to blow up in this scenario. If you mean a *different* version, like say a fork, there is literally zero precedent and what will likely happen is that the randomizer just crashes. The way the settings string currently works would make this basically impossible to support.

**Comment by SilverstarStream** [comment]
I figured out my issue. I just had to try launching ZX without the launcher to see that it had the scaling I didn't want. It seems that launching the jar by double clicking it scales it based on my local settings between Java and Windows. And it seems like launching the jar from the ZX launcher using `java -jar` keeps consistent scaling.

**Comment by tom-overton** [comment]
Interesting, I had no idea that using the launcher or not would affect the UI in any way. It should be noted that we've had troubles with high-DPI screens before; it just seems to be a limitation of the Swing UI. So if weird stuff happens with the UI on high-DPI screens, that's unfortunately kind of expected.
