### ISSUE TITLE
[Bug] Limit Pokemon setting Breaks some Evolutionary lines even with Relatives enabled.

### ISSUE THREAD

**Issue by InfinityD4** [Ajarmar/universal-pokemon-randomizer-zx#293]
The Limit Pokemon Feature removes evolutions in a haphazard way(It Removes all of them instead of just removing cross-gen evolutions) and this that causes several unexpected issues when playing with the include cross-gen relatives option on.

Examples:
Pichu can Evolve into Pikachu but can't further Evolve into Raichu.
Oddish can't Evolve into Gloom, Ralts can't evolve into Kirlia, Togepi into Togetic, Magby being able to evolve into Magmar or Magmar into Magmortar but not both unless gen 1 is selected.

This seems to be an issue with the randomizer not thinking about Cross-Gen Evolutionary Relatives that aren't directly linked.
Though in some cases this works as a feature, Such as how it prevents Eevee from evolving into the other Eeveelutions or only allows Snorunt to evolve into Froslass.

to Reproduce:
Open UPR-ZX
select a Gen 3+ game
Check Limit Pokemon
Select Gen 2/4/6
Check all "Include Related Pokemon" Boxes
Randomize and save.
View randomized Game's pokemon evolution data in rom editing tool of your choice.
or attempt to Evolve Eevee into a evolution from an unselected Generation.

Expected Behavior: Inclusion of ALL Pokemon in that evolutionary family, not just ones that directly evolve to/from a pokemon in the selected generation. Such as adding in all the Eeveelutions alongside Eevee as long as Gen 1 Relatives is selected.
Although as mentioned previously some of this behavior could be seen as expected and in my opinion is worth keeping in, but made optional via additional checks for Branched Evolutions and Lines that span more than two generations.

<img width="607" alt="Capture1" src="https://user-images.githubusercontent.com/90650460/133155840-4d0217de-35e3-4402-8d6a-32796f0ffceb.PNG">
<img width="592" alt="Capture2" src="https://user-images.githubusercontent.com/90650460/133155841-edabcbc7-cf46-40af-bc7d-33edd9489534.PNG">
<img width="604" alt="Capture3" src="https://user-images.githubusercontent.com/90650460/133155842-9abf4653-bce3-4e16-bf92-76557e70a123.PNG">
<img width="617" alt="Capture4" src="https://user-images.githubusercontent.com/90650460/133155843-4020a410-4067-4204-adce-2e2d0571a530.PNG">

**Comment by tom-overton** [comment]
I fixed this via 85ebbc75af711207702ee386c405621127ad3512 and ed3d24abef0fd398b25f95e0b60b3be9b966baf9. To be more specific, I just ripped out the whole "related Pokemon to" stuff because it was more confusing than helpful. If you turn on Gen 2 and then related Pokemon from Gen 1, should Magmortar be included? How about if you do that, but also turn on related Pokemon from Gen 4? Is Sylveon "related" to Pokemon in Gen 2 despite the fact that it evolves from a Gen 1 Pokemon?

Now, you just specify what generations you want enabled, and then optionally you can turn on evolutionary relatives. This solves the inconsistency you pointed out: either *both* Oddish and Gloom will be disabled, or they will both be enabled. To be honest, I wasn't sure if we should even make this optional, but we as developers simply never use this feature, nor do we really know anyone who uses it. Since we don't know what people who use Limit Pokemon actually want, we just left it as an option.
