### ISSUE TITLE
[Help] Clarification on a setting

### ISSUE THREAD

**Issue by H7n911** [Ajarmar/universal-pokemon-randomizer-zx#300]
**Describe your problem clearly:** 
I Caught Latios and I have his mega stone when I mega evolve him and finish the battle he returns to his normal form, is the in-battle transformation not included in the don't revert alt forme and if so why is that?

**Comment by tom-overton** [comment]
That's correct, it's not included. To understand the goal of the setting, consider what happens if you capture Mega Latios in the wild. You wouldn't want him to suddenly become normal Latios, right? Yet that's *exactly* what happens without the setting; the game doesn't "like" it when you have Megas in your party outside of battle and will actively try to change them back to normal. The setting simply patches the game to prevent it from reverting Megas outside of battle. In-battle transformations, like Latios Mega Evolving into Mega Latios, or Ditto transforming into another Pokemon, are completely unaffected by this setting. I'll add a note saying as such to the tooltip text.

**Comment by H7n911** [comment]
Thank you tom for the quick answer. I did check the tool tip earlier and it
said “NOT transformed in battle” which made me mad because i had to waste
your time due to my inability to read.

One thing I don’t understand is the idea that mega evolution weren’t like a
regular stage evolution, and the mega stones could’ve been like evolution
stones such as moon stones etc. Maybe it’s just me but trying to mega
evolution every battle is just obnoxious beyond belief.

Initially i thought the don’t revert option included the in-battle
transformation but unfortunately it doesn’t. I looked all over the internet
for a solution to no avail, mind you this problem could be something that
the community doesn’t find to be a big deal but personally i like the
convenience of not having to mega-evolution every battle!

Of course you guys don’t take requests so I didn’t want to ask you for a
simple change but if you have the time to include an option to include
those in-battle transformations that would be appreciated!

Also a big thank you for all of you incredible people for updating and
adding new features to the original Universal Randomizer, you guys did this
out of the kindness of your hearts I cannot thank you enough!!!

**Comment by tom-overton** [comment]
No worries about missing the tooltip; they're not the most discoverable thing in the world. As for your idea, that's actually something I've never thought of before, but it's an interesting idea.

Unfortunately, in Gen 6, this idea is very close to impossible. Every Pokemon has something that we call a "forme number," which indicates if they're an alt forme or not (and if they *are* an alt forme, which alt forme they are). For example, Mega Latios has a forme number of 1, while regular Latios has a forme number of 0. I bring this up because of how evolutions work in Gen 6 and lower; you *cannot* change forme numbers via evolution. So while I could hack the game to make Latios evolve into anything with a forme number of 0, I *cannot* hack the game to make him evolve into Mega Latios, as that has a different forme number. The only way to get that working would be to make extensive code modifications so that you *could* change forme numbers via evolution, and to be honest I don't even know where to begin with that.

However, what you're proposing *is* possible in Gen 7, and can be accomplished using [pk3DS](https://projectpokemon.org/home/forums/topic/34377-pk3ds-xy-oras-rom-editor-and-randomizer/)! Gen 7 added the ability for evolutions to change forme number, so we can add an evolution to Latios to make him evolve into Mega Latios. Open up the evolution editor and add an evolution to Latios like so (pay attention to the "1" in the box next to the item; that indicates that it should be forme number 1, aka Mega Latios):

![image](https://user-images.githubusercontent.com/12245827/134822646-72f15fc8-e8cb-4730-8342-6497db80a8e7.png)

Adding an evolution like this would break some things in the randomizer that would need fixing, so I'll politely decline to implement this in the randomizer itself (plus, as you noted, we don't take requests). However, hopefully this helps you hack it in your own ROMs!

**Comment by H7n911** [comment]
I understand Tom and thank you for the awesome response. Maybe in the
future Gamefreak would make the mega-evolution a stage evolution, it would
certainly make things more convenient. Have a good day!!!
