### ISSUE TITLE
[Bug] Alternate Formes don't respect similar strength rule

### ISSUE THREAD

**Issue by mikester112** [Ajarmar/universal-pokemon-randomizer-zx#333]
**Describe the bug**
Alternate Formes don't respect similar strength rule (Ultra Sun). I walked into some tall grass and immediately encountered a mega-metagross and according to the log it replaced a Yungoos this is despite setting things to use similar strength. I also found a few similar replacements in the log. Also, it would probably be a good idea to have separate alternate form toggles for regional variants and megas as while I don't want to see megas in the wild I do want to see the regional variants. I've uploaded both the settings I used and the log.

[AF.zip](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/7490867/AF.zip)
[New Folder (5).log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/7490865/New.Folder.5.log)

**To Reproduce**
Randomize with alternate formes enabled

**Expected behavior**
To not have my first encounter be a mega-metagross

**System (please complete the following information):**
 - Operating System: Windows 10
 - Java Version: 8
 - Randomizer Version: 4.2.1

**Comment by tom-overton** [comment]
There's no bug here, though it's very easy to see why you might think so. When you walk into the first patch of grass in all the 3DS games, there is a forced static encounter with some weak earlygame Pokemon. Since it's a static encounter, your wild Pokemon settings have zero effect on it; it's affected by your static encounter settings. And your static encounter settings do *not* have similar strength Pokemon enabled:
![image](https://user-images.githubusercontent.com/12245827/140902340-8f9f45c6-c4a1-4b5f-961d-cbbb54840b25.png)

You can actually see in the logs that the Yungoos => Metagross-Mega switch happens in the Static Pokemon section. Your static Pokemon settings totally allow this sort of thing to happen, so there's no bug here. On the other hand, Mega Metagross doesn't appear *anywhere* in the Wild Pokemon logs, which is exactly what I would expect given your settings.
