### ISSUE TITLE
[Bug] cant load the app in windows 10 x64

### ISSUE THREAD

**Issue by Littlemac123** [Ajarmar/universal-pokemon-randomizer-zx#342]
im running the .bat. and that shows up

**Screenshots**
https://cdn.discordapp.com/attachments/247557068490276864/912823541949407262/unknown.png

**System (please complete the following information):**
 - Operating System: windows 10 x64
 - Java Version: "1.8.0_241"
 - Randomizer Version: PokeRandoZX-v4_2_1

**Additional context**
I love you <3

**Comment by tom-overton** [comment]
This error occurs because you have 32-bit Java installed. You can fix it by installing 64-bit Java. For more information, see [the Java section of our wiki](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java).

Oracle for whatever reason makes 64-bit Java annoyingly hard to get on Windows. If you want to confirm you have 64-bit Java, open the Command Prompt (open the Start Menu, type "cmd", then press Enter) and run `java -version`; if it says "64-bit" in the response, then you're good.
