### ISSUE TITLE
Launcher doesnt work at all.

### ISSUE THREAD

**Issue by Helm12** [Ajarmar/universal-pokemon-randomizer-zx#349]
When i open the launcher all i see is "press any key to exit.." 

Open the "launcher_windows" and i get the error.And no "launcher-log.txt" is formed. 

 - Operating System: Windows 10
 - Java Version: Java SE 17.0. 1
 - Randomizer Version: v4.2.1

I have tried running as administrator and checking the permissions but to no avail.I didn't mess with the launcher or anything ,just downloaded and tried to open it ,thats all.

**Comment by jknox202** [comment]
I have the same problem here. I reinstalled the latest version of Java but didn't have any luck with it. For reference I am also on Windows 10 with the latest version of the randomizer.

**Comment by Helm12** [comment]
> I have the same problem here. I reinstalled the latest version of Java but didn't have any luck with it. For reference I am also on Windows 10 with the latest version of the randomizer.

I still have it ,no ideea what causes it tbh.I tried other versions of java too ,to no avail.

**Comment by jknox202** [comment]
Okay it took me some time, but i got a fix that worked for me. 

It turns out I did not have 64-bit Java, which you can find "Windows Offline (64-bit)" and download here

https://java.com/en/download/manual.jsp

Then I had to find the address of the newly installed Java, which for me was here "C:\Program Files\Java\jre1.8.0_311\bin"

Using that address we go to "System Properties" > "Environment Variables", and I then add the address in the Path section in the "System Variables" table. So "Edit" , then "New", copy paste the address (C:\Program Files\Java\jre1.8.0_311\bin) in and click "Move up" until it is at the top of the table. 

After that I just exit cmd and load up again and the program loaded as intended.

You might need to uninstall any older versions of Java still on your computer, I did and used this program "Java Uninstall Tool" which I found here

https://java.com/en/download/uninstalltool.jsp

**Comment by Helm12** [comment]
I know its a bit late ,but that didnt work for me ,nor other solutions i have tried since ,but what did?
installing java 7.
