### ISSUE TITLE
[Bug] (Black 2) Exiting the Pokemon menu crashes with Fastest Text.

### ISSUE THREAD

**Issue by SilverstarStream** [Ajarmar/universal-pokemon-randomizer-zx#365]
**Describe the bug**
I had a crash similar to [this user](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/63#issuecomment-729386181), where leaving the Pokemon menu (pressing B, viewing a summary) crashes Black 2 on my 3DS with TwilightMenu++ (latest update). I realized that the crash correlated to enabling the "Fastest Text" option.

I was curious, so I changed a few variables besides Fastest Text. Specifically: which version was used, using a clean or AP-patched ROM, and using an emulator or hardware.
(I used this AP-patching tool: https://gbatemp.net/download/retrogamefan-nds-rom-tool-v1-0_b1215.35735/)
Black 2 crashes with fastest text enabled from a clean ROM.
White 2 did not crash with the same conditions.
Black 2 did not crash with fastest text if the base ROM was AP-patched, and did not crash from a clean ROM that did not have fastest text.
Neither Black nor White had crashes.
Finally, the crash only occured on hardware, it did not crash on emulator.

I was also curious about AP:
TwilightMenu's DS Mode prevented the AP from kicking in on just BW2's randomized ROMs.
Black and White had active AP even in DS mode. AP-patching White's ROM before randomization stopped AP.
None of the randomized clean ROMs had active AP on emulator.

I didn't play very long on any of the ROMs, just long enough to check whether the Pokemon menu would crash and whether AP was active.

**To Reproduce**
1. Randomize a clean Black 2 ROM with "Fastest Text".
2. Run the randomized ROM with TwilightMenu++.
3. In-game, enter the Pokemon menu, then leave it.

Here's my randomizer logs:
[logs.zip](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/7804528/logs.zip)

**System (please complete the following information):**
 - Operating System: Windows 10
 - Java Version: Java version 8 update 311 (build 1.8.0_311-b11)
 - Randomizer Version: v4.2.1

**Additional context**
I'm mostly submitting this Issue to tie up the loose end from #63 and to point to possible solutions. Also to share some information about using the randomizer with hardware. Please let me know if there's any more information I can provide.

**Comment by tom-overton** [comment]
Ajarmar and I looked into it, and it seems the problem is that Twilight Menu isn't applying the AP patch automatically to the randomized ROM because the header checksum is different. I tried this with a flashcart on real hardware (which doesn't need any antipiracy patch), and it worked fine with Fastest Text.

I'm not sure if there's a really good solution other than Twilight Menu fixing whatever thing causes the antipiracy to kick in. Twilight Menu's solution of checking for the appropriate header checksum in order to apply the antipiracy patch isn't going to work when randomized, since the checksum is going to change every time. I guess the best solution for now really is just to manually AP patch the game.
