### ISSUE TITLE
I can't make a randomization of Pokemon black spanish version

### ISSUE THREAD

**Issue by Imoke2001** [Ajarmar/universal-pokemon-randomizer-zx#366]
Whenever I try to make a randomization of pokemon black, spanish version, I get an error of arrayOutOfBounds at the moment of randomizing the static pokemon. At the begining, I thought it would be a secondary problem, and decided to remove the randomization of static pokemon, but it also gave an error when randomizing without using the "randomize static pokemon" option.
This has happened for over 5 timer, having redownloaded the randomizer and with different pokemon black spanish versions

![image](https://user-images.githubusercontent.com/71631665/148104203-521c55d7-d8ca-4f7a-9dba-753717c3c4f4.png)
![image](https://user-images.githubusercontent.com/71631665/148104256-67cffdda-3a6f-41bd-a88f-60c2a5871903.png)

System information:
 - Operating System: Windows
 - Java Version: 8
 - Randomizer Version: 4.2.1

**Comment by tom-overton** [comment]
Yeah, this is a known issue with non-English versions of BW1 in version 4.2.1. It will be fixed in the upcoming 4.3.0, which should hopefully be out soon. For now, please use 4.2.0 with BW1; you won't actually miss anything, and your Spanish ROM will be supported just fine. Sorry for the inconvenience!
