### ISSUE TITLE
[Contribution Idea] Preserving type specialties for type-theme trainers?

### ISSUE THREAD

**Issue by Emilinrose** [Ajarmar/universal-pokemon-randomizer-zx#367]
So to explain, when i used the randomizer with "type theme" enabled, not only did it give type themes to ALL the trainers, but the themes themselves were random. Roxanne had dragon types, etc.

An additional setting to preserve in-game type themes is possible.i have a small, forgotten program for GBA games on my computer called the "reasonable randomizer", by Lat10s, which has several good ideas that could be incorperated here.

this would allow more variety while not completely breaking the game.

this link leads to the randomizer i'm talking about, 

[https://www.reddit.com/r/PokemonROMhacks/comments/159cta/pokemon_3rd_gen_reasonable_randomizer/](https://www.reddit.com/r/PokemonROMhacks/comments/159cta/pokemon_3rd_gen_reasonable_randomizer/)

**Comment by tom-overton** [comment]
I'm not sure this is as cut-and-dry as it may seem. Here are some caveats that immediately came to mind:
- What type specialty is Agatha? Is she Poison-type or Ghost-type? If she's Ghost type, wouldn't that mean she would exclusively have the Gastly line in Gen 1?
- What type specialty is Lance? Should we say he's a Dragon-type trainer because that's what they "intended" him to be? What about in Gen 2, where he has three Dragon Pokemon, but a full team of Flying Pokemon? Should he be a flying-type trainer then?
- With regular trainers, it's even more nebulous. While it makes sense for Bug Catchers to be Bug-type trainers, but what about Aroma Ladies? Should they be Grass-type trainers, since they *tend* to use Grass types? What about in Gen 4, where they use Combee? What about in ORAS, where one random Aroma Lady has a Goodra?

There are just so many potential ways to do the randomization of trainer Pokemon that is intentionally compliant or intentionally non-compliant with how trainers tend to work in the vanilla game, and at some point it's just going to get confusing if there are too many options. In our opinion, this is one such case; it doesn't add a lot, and it's full of ambiguity.
