### ISSUE TITLE
[Help]  Randomizer doesn't even open for me.

### ISSUE THREAD

**Issue by AntonioCamargo** [Ajarmar/universal-pokemon-randomizer-zx#372]
I downloaded the file and as soon as I double clicked the launcher it asked me with what program I wanted to open with.
I didn't choose anything just clicking outside of the options, but it auto went to Adobe Acrobat DC, and now I don't know what to do anymore.

![help](https://user-images.githubusercontent.com/72630268/149645641-6388bc40-6423-49f3-982f-a917bb8a995a.PNG)

**Comment by tom-overton** [comment]
1) You should probably be using [the current version of the randomizer](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.2.1), which is v4.2.1. This should already fix your problem, since we no longer use a JAR-based launcher.
2) If you want JARs to be associated with Java again, right click a JAR, then select Open With -> Choose Another App. Pick Java, then check "Always use this app to open .jar files"
