### ISSUE TITLE
[Bug] 4.3 bug

### ISSUE THREAD

**Issue by mightymarkdean** [Ajarmar/universal-pokemon-randomizer-zx#389]
Error: Unable to access jarfile PokeRandoZX.jar
Press any key to exit...

its in a folder with all the permissions. even tried admin mode
also downloaded new Java

**Comment by tom-overton** [comment]
Did you download the release from [here](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.3.0)? We frequently see this issue when people accidentally download the randomizer's source code instead of the randomizer itself. You can tell that you downloaded the source code because there will be a folder called "src" in the thing you downloaded.

**Comment by mightymarkdean** [comment]
it worked thanks
