### ISSUE TITLE
[Bug] Can't start with National Dex for Platinum rom

### ISSUE THREAD

**Issue by baggypantsman** [Ajarmar/universal-pokemon-randomizer-zx#391]
Hi, I was using this program primarily just to give the National Dex at the start of a Platinum rom (no randomization), but it doesn't seem to work. If I start with the Kanto starters for example, you get the Pokemon but still have the Sinnoh dex. The only other settings I changed were adding Gen 6 base stats & move stats, giving running shoes at the start and using lower-case Pokemon names which all did work.

I'm on Windows 11 with the latest version of Java and v4.3.0 of the randomizer, and the particular Platinum rom is 3541 if that's important.

Thanks for any help!

**Comment by baggypantsman** [comment]
I didn't! Just tried it now and it works totally fine. Thank you!

**Comment by tom-overton** [comment]
You're welcome! Sorry for the confusion/annoyance. Because of the way you obtain the PokeRadar in DPPt (at the same time as the National Dex), we unfortunately have to do something very silly to ensure the player can get the radar. We *could* just give you the National Dex at the very start, but if we did, then the PokeRadar would be unobtainable.
