### ISSUE TITLE
Building Universal Pokemon Randomizer ZX Wiki Page

### ISSUE THREAD

**Issue by katykat5099** [Ajarmar/universal-pokemon-randomizer-zx#394]
The Wiki Page for building the randomizer is outdated.

Part of the Wiki tutorial talks about using Java 1.8 as a setting to build to randomizer, but it now uses Java 17. So I think it should be updated.

**Comment by tom-overton** [comment]
I'm not sure if there's a misunderstanding here. You don't need Java 17 in order to build the randomizer; Java 1.8 works fine. In fact, we deliberately stuck to Java 1.8 to prevent us from using newer language features; we want users to be able to use the randomizer with only a Java 1.8 runtime installed. So I don't think we want to change this aspect of our build instructions.

**Comment by katykat5099** [comment]
> I'm not sure if there's a misunderstanding here. You don't need Java 17 in order to build the randomizer; Java 1.8 works fine. In fact, we deliberately stuck to Java 1.8 to prevent us from using newer language features; we want users to be able to use the randomizer with only a Java 1.8 runtime installed. So I don't think we want to change this aspect of our build instructions.

OK, that's strange. I tried to build it using 1.8 but it said that I was using an outdated version and required a newer version. I do not remember word for word what it said, but essentially I had to use 17.
