### ISSUE TITLE
[Help] How to randomize Gen 6 on v1.5

### ISSUE THREAD

**Issue by Sonicdevil** [Ajarmar/universal-pokemon-randomizer-zx#406]
This is much less a problem and just a very genuine question that I personally can't seem to find the answer for it anywhere, especially with the research I've done leading to other pokemon randomizers. Is there any way to run a randomizer on an updated version of the game (I personally am doing a randomized pokemon X and would like to know if it is possible on v1.5) and if is possible, how to do it? I followed a guide made by the the4thgengamer on youtube on how to use this and he did it the way that requires you to use 1.0 by deleting update data off of your 3ds. This is very much for the good first issue label as I only just modded my 3ds a day ago when I'm writing this and don't know if there was a better guide to have used or even if I'm just stupid and can go straight to 1.5 without any issues

**System:**
 - Operating System: Windows 11
 - Randomizer Version: 4.3.0

**Comment by tom-overton** [comment]
Yeah, you can load a game update into the randomizer and use that to make something that works for v1.5. We have a whole section on the wiki about here: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#3ds-game-updates

But to summarize, first load Pokemon X in the randomizer, then select the "Load Game Update" option under settings:
![image](https://user-images.githubusercontent.com/12245827/160177788-73420fd1-128b-48a6-a4f6-1a9ca177f80a.png)

Then just select a CIA of your game update. You'll know it works if you see the game information updated like so:
![image](https://user-images.githubusercontent.com/12245827/160177874-aaede780-d237-4067-8cc5-0210a852c754.png)

And that's it really. The important thing is that **the version of the game loaded in the randomizer matches the version of the game that you're going to play**. If you're going to play v1.0, make sure v1.0 is loaded in the randomizer. If you're going to play v1.5, make sure v1.5 is loaded instead. I'm guessing the tutorial you saw deleted their game update because they assumed that a lot of people were playing on emulator and didn't have the update on hand. But as long as you load the v1.5 game update, everything will work fine. Let me know if any of that is confusing or you have any questions.

**Comment by Sonicdevil** [comment]
Nope! Your explanation was perfect, thank you very much for the quick help!
