### ISSUE TITLE
[Help] I Have lastest java installed and it still does work

### ISSUE THREAD

**Issue by voidchaos23243** [Ajarmar/universal-pokemon-randomizer-zx#407]
**Describe your problem clearly:** 

**System (please fill in the following information):**
 - Operating System: windows 
 - Randomizer Version: lastest

So i have java installed on my pc and its acting like i dont and says no java cmd

**Comment by tom-overton** [comment]
Can you show the specific error that you're seeing?
Furthermore, can you run `java -version` in a command prompt (you can open one by hitting Start, typing "cmd.exe" and pressing Enter) and report what it says?

**Comment by voidchaos23243** [comment]
when i run java -version it just says java not a cmd

**Comment by voidchaos23243** [comment]
![image](https://user-images.githubusercontent.com/84739355/160185288-50ed78b6-2418-443c-92fc-3b23d1c05e50.png)
java -version also did not work

**Comment by tom-overton** [comment]
This means you don't have Java installed on your computer. Take a look at our [Java](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) wiki page and grab a 64-bit version of Java.

**Comment by voidchaos23243** [comment]
i do have it downloaded

**Comment by tom-overton** [comment]
When you double-click PokeRandoZX.jar, what happens?

**Comment by voidchaos23243** [comment]
ive got video proof of me downloading 64 bit java and ur app not working

**Comment by voidchaos23243** [comment]
command promt which is a screen shot above

**Comment by voidchaos23243** [comment]
> ![image](https://user-images.githubusercontent.com/84739355/160185022-00820dcf-76a1-4c29-899b-e14613d2c876.png)

**Comment by voidchaos23243** [comment]
ur app is busted java is installed on my pc.

**Comment by voidchaos23243** [comment]
it says to use the launcher_windows.bat 
![image](https://user-images.githubusercontent.com/84739355/160196629-3a1fe6ce-d7ab-430f-99b7-262bb128835c.png)

**Comment by tom-overton** [comment]
Alright, thank you for showing the JAR is working. Try doing the following in a command prompt:
`where javaw`
`where java`
We suspect that your Java installation *only* has the former, which is why the launcher isn't working for you, but double-clicking on the JAR *does* work.

**Comment by voidchaos23243** [comment]
where do i put these

**Comment by voidchaos23243** [comment]
![image](https://user-images.githubusercontent.com/84739355/160197686-574fdba2-2a26-44c0-ab2f-ea8e919cad6c.png)

**Comment by tom-overton** [comment]
OK, your Java install is *very* strange if neither of those things could be found. Do you have a folder on your computer called C:\Program Files\Java? If so, is there anything in there?

**Comment by voidchaos23243** [comment]
where would i find that

**Comment by voidchaos23243** [comment]
![image](https://user-images.githubusercontent.com/84739355/160199284-d7ac74f2-f27b-4da6-a41e-7c6aee8043e1.png)

**Comment by voidchaos23243** [comment]
javaw is in the bin folder

**Comment by tom-overton** [comment]
Yep, we know what the problem is. You were right; you *did* have Java installed. But your install is a bit weird and it didn't set a variable called PATH correctly. Fixing it is a bit tricky but I'll try to walk you through it.

First, open the start menu and type "environment variable". It should make something called "Edit the system environment variables" appear; click on that:
![image](https://user-images.githubusercontent.com/12245827/160199631-9fa44e52-c8d3-4974-a1bc-64411b91ef12.png)

It should open a window like this. Click on the "Environment Variables..." button:
![image](https://user-images.githubusercontent.com/12245827/160199712-2f5c24f9-60d6-4d1e-bf0c-d2a24dadd25e.png)

It should open a window like this, which might be confusing. But focus on finding the word "Path" in the "System variables" section. Click on it, then press the "Edit..." button:
![image](https://user-images.githubusercontent.com/12245827/160199871-cb2ae3a5-edca-401f-a95a-357ec4a7a4d2.png)

In the window that appears, click the "New" button, then type `C:\Program Files\Java\jre1.8.0_321\bin` and then press Enter. When you're done, it should look something like this:
![image](https://user-images.githubusercontent.com/12245827/160200111-6924df31-5ab9-4f94-a606-3e994ce0789e.png)

Now just keep hitting OK to close every window we opened as part of this. At this point, you should be able to run `java -version` in the command prompt and have it work. That will make launcher_WINDOWS.bat function properly.

Sorry that it took so long to figure this out! It is *very* strange for a Java installation to *not* change the PATH like it did in your case.

**Comment by voidchaos23243** [comment]
![image](https://user-images.githubusercontent.com/84739355/160200939-c42ec3bf-63d4-439b-a52f-7d464ee59a2c.png)

**Comment by tom-overton** [comment]
What happens when you run `echo %PATH%` in the command prompt?

**Comment by voidchaos23243** [comment]
some stuff about sys32 comes up

**Comment by voidchaos23243** [comment]
u want ss?

**Comment by tom-overton** [comment]
It would be helpful to see the whole thing, yes.

**Comment by voidchaos23243** [comment]
![image](https://user-images.githubusercontent.com/84739355/160201275-5ced09ff-171a-4d93-9c68-2e2306815441.png)

**Comment by tom-overton** [comment]
Did you follow all of the steps I listed above to add Java to your Path? If you did, then Java *should* appear in there.

**Comment by voidchaos23243** [comment]
![image](https://user-images.githubusercontent.com/84739355/160201383-77016ec5-4378-4df1-b540-ac4980fb536e.png)
is that right?

**Comment by voidchaos23243** [comment]
i had to type the variable name Path but idk if it worked

**Comment by tom-overton** [comment]
Can you close and reopen the command prompt and then run `echo %PATH%` again? You have to reopen the command prompt to get it to pick up the new environment variables. What you have *looks* correct, though

**Comment by tom-overton** [comment]
If Java *still* doesn't show up with `echo %PATH` when you close and reopen the command prompt, then perhaps restarting the computer might make it work too. The point is that we just need to get the changes that you made to show up in the command prompt, then everything should work.

**Comment by voidchaos23243** [comment]
could you help me tomorrow as its getting kind of late
do you have a support discord?

**Comment by tom-overton** [comment]
No, we don't have a support discord, sorry. We just tend to answer questions here. And no worries about having to call it quits for the night; just try restarting your computer over night and seeing if Java now shows up in `echo %PATH`

**Comment by voidchaos23243** [comment]
ok ill message this forum

**Comment by voidchaos23243** [comment]
hey quick question if i can post a dump of a cia of omega ruby on here could u randomise it

**Comment by voidchaos23243** [comment]
now i get this error 
![image](https://user-images.githubusercontent.com/84739355/160226535-f4aa0d9d-f544-407a-ac30-551b83032c6a.png)

**Comment by tom-overton** [comment]
We really have no idea why this is happening to you. If you right-click and then select "Run as Administrator" does it work?

A few people discuss the problem here, so if running this as an administrator works, then perhaps one of these solutions would work too: https://superuser.com/questions/911910/double-clicking-batch-file-windows-cannot-find-file

**Comment by voidchaos23243** [comment]
its still also saying i dont have java

**Comment by tom-overton** [comment]
What comes up when you run `echo %PATH%`?

**Comment by voidchaos23243** [comment]
still says java aint there

**Comment by voidchaos23243** [comment]
ill just close the ticket and get my friend to randomize it for me with his pc

**Comment by tom-overton** [comment]
OK, then open a command prompt and run `setx path "%path%;C:\Program Files\Java\jre1.8.0_321\bin"`. Then Java should be added to your PATH

**Comment by voidchaos23243** [comment]
ok you can close this ill make another ticket if i have an issue
