### ISSUE TITLE
Pokémon XY Trash Can Encounters not Randomized

### ISSUE THREAD

**Issue by AllThatJazz139** [Ajarmar/universal-pokemon-randomizer-zx#414]
Playing on O2DS Console Using Luma and LayeredFS Randomized Pokemon X version. Checked all trash cans in the lost hotel where I encountered Garbador and Rotom, which are typical encounters in the vanilla game. All other encounters appear to be randomized except these. Currently played up to the Lost Hotel trash cans where I first noticed this, cannot confirm for Pokémon Village.

I didn't save a log file however I believe I chose Similar Strength, Global Mapping, Only switch Legendaries for Legendaries for my wild Pokémon settings.

Playing on a Tuesday which changes the encounter tables for Lost Hotel Trash Cans if that matters.

**Comment by tom-overton** [comment]
Yep, this is something I was already aware of, though I suppose I didn't put it on the "Known Issues" page. I guess my thought process was "nobody will bother checking that and filing an issue about it," but I'm glad to be proven wrong!

Around the time we were working on v4.0.0, I investigated this and could not find where in the ROM these encounters were actually set, so I just gave up. Because you brought it up again, I'll take a second look now, but it may result in the me giving up again. No promises, but I'll definitely give it the old college try.

**Comment by AllThatJazz139** [comment]
Ah, That makes sense. The encounter rate is so low in the Lost Hotel that in my nuzlocke I happened to make it to the trash can before I came across a wild encounter. Finding a Garbador was a surprise since I know that at least trubbish spawned there, when I noticed it was tuesday and I later found a rotom in the trashcans I was immediately suspicious. 

I hope you are able to find the source of the encounter table in the ROM, though I will admit its not something I would exactly remember either lol.

**Comment by tom-overton** [comment]
Fixed it as part of the linked commit, and it will be included in the next release. Thanks for filing a report and motivating me to fix this!

![image](https://user-images.githubusercontent.com/12245827/161927114-d6218cee-4007-4f11-8690-b08380629192.png)
