### ISSUE TITLE
[Contribution Idea] Option to Pull from TM / Level Up / Egg Move Learnsets for Trainers / Important Trainers

### ISSUE THREAD

**Issue by Nuclearstomp** [Ajarmar/universal-pokemon-randomizer-zx#418]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** 

New setting under Foe Pokemon. An additional option to randomly add prior tms / egg moves / level up moves to a mon's movepool for trainers so that they aren't always the same. Perhaps a random % chance a trainer will have a different move or multiple different moves. Maybe even an option to restrict it to just important trainers.

**What problem would your contribution solve? Please describe:** 

Adds additional replay and surprise factor. Good for making trainer battles in general more challenging and engaging as most mons movepools end up pretty mediocre.

**Additional context:**

Just something I thought would be good to add to the randomizer after a recent playthrough.

**Comment by tom-overton** [comment]
Thanks for filing this contribution idea. The good news is that we're actually planning on implementing this ourselves for the next release in the randomizer. Since we already have some ideas on how to implement it, we'd rather just handle it ourselves rather than attempt to force all of our ideas onto you. Because of that, I'm going to close this contribution idea, but I hope you're looking forward to seeing this in the next release!
