### ISSUE TITLE
[Bug] Readjusting Level crashes while saving

### ISSUE THREAD

**Issue by PanCave** [Ajarmar/universal-pokemon-randomizer-zx#430]
**Describe the bug**
Hello together!
I know UPR ZX doesn't support randomizing ROM hacks or corrupted dumps. But when I randomize a clean ROM using 4.4.0 Release of UPR ZX and then load that randomized ROM to change foe and wild pokemon levels, it crashes while saving.

**To Reproduce**
1. Open Black 2 (german) ROM and randomize.
2. Reopen randomized ROM and adjust level slider.
3. Try saving.

**Expected behavior**
I thought UPR ZX would just override the levels. Maybe it did, I don't know.

**Screenshots**
![grafik](https://user-images.githubusercontent.com/8067572/167262209-af08f980-27e5-497d-814c-adabdc724467.png)

**System (please complete the following information):**
 - Operating System: win10 64-bit
 - Java Version: 8 Update 151
 - Randomizer Version: 4.4.0

**Additional context**
[error_2022-05-07-17-19-38.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/8645516/error_2022-05-07-17-19-38.txt)

**Comment by tom-overton** [comment]
Hey, sorry for the delay on responding to this. The issue is that you're applying the "Run Without Running Shoes" patch twice. I tried doing what you described *without* applying the "Run Without Running Shoes" patch twice, and it worked fine. Hope that helps!

My advice, if you're loading already randomized ROMs into the randomizer a second time, is to change as little as possible the second time. So *only* change the foe and wild Pokemon levels the second time; don't touch anything else.
