### ISSUE TITLE
[Bug]

### ISSUE THREAD

**Issue by Joni10101** [Ajarmar/universal-pokemon-randomizer-zx#434]
When I try to open launcher _WINDOWS it does not run. It just says "Press any key to exit . . ." in the cmd. I have reinstalled Java even though I have Java 64 bit and the newest version. I have tried every way that the Master Issue #93 suggests to fix this problem but nothing works. If I try to run PokeRandZK,jar for a split second a window appears and then it just closes again. Please help as soon as possible.

**Comment by tom-overton** [comment]
Let's try to troubleshoot this one step at a time.
1. Are you using v4.4.0? You mentioned issue #93, but that's not the current troubleshooting issue. #221 is. Perhaps there's something in that issue more applicable to your case?
2. Can you start the randomizer without using the launcher? Try double-clicking on the randomizer JAR and seeing what happens. If it works, it will complain that you didn't start it with the launcher, but at least that will help narrow down the problem

**Comment by kcblack42** [comment]
I'm having the same issue here. I can open the rando without using the launcher but it whines at me, especially for gen5 games (though i might just have a corrupted file or something). I haven't tried anything beyond gen 5, but I have been able to successfully randomize gen 4 games by direct launching.

![image](https://user-images.githubusercontent.com/105865047/169301959-12ccea4e-d714-4b5c-98ec-0cef68569881.png)

**Comment by tom-overton** [comment]
@kcblack42 This indicates that you have 32-bit Java installed. You need 64-bit Java installed in order to use the launcher (using the launcher is only *required* to randomize the 3DS games, though as you noted, you can randomize earlier games if you just ignore the randomizer whining at you). See our [Java wiki page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) for more info, or go here to download 64-bit Java: https://java.com/en/download/
