### ISSUE TITLE
[Help]  I'm confused with how to set this on Exagear.

### ISSUE THREAD

**Issue by Tappy-tech** [Ajarmar/universal-pokemon-randomizer-zx#435]
After launching launcher_windows.bat file, I get the error with creating JVM. Can someone clarify the steps? Wiki is also confusing. 

 - Operating System: Realme XT, Windows 7 on Exagear, ColorOS 11 as a real OS.
 - Randomizer Version: How can I find it?

**Comment by Ajarmar** [comment]
Sorry, but we don't have any experience using Exagear and we don't have the capacity of looking into it. I'd recommend that you check that your Java installation seems to be fine (i.e. that you are able to run other Java programs), otherwise please use the randomizer on (non-emulated) Windows/Mac/Linux.
