### ISSUE TITLE
[Bug] starter screen bug in platinum

### ISSUE THREAD

**Issue by Baat01** [Ajarmar/universal-pokemon-randomizer-zx#437]
**Describe the bug**
when I randomize starters using an already randomized rom in which I randomized the starters, I get a black screen and a freeze when I'm clicking on the prof rowan's suitcase
the rest of the rom is fine, I'm used to bypass this issue by using my save file in another rom non randomized and then edit my pokemon via pkhex to get my starter that i checked in the randomization log
It doesn't appear in frlg or bw/bw2, I don't know for the other roms but it may only be a platinum/dpp only bug

**Comment by tom-overton** [comment]
We don't provide support for loading modified ROMs into the randomizer; this includes already randomized ones. The reason this happens is because of changes we have to make to the ROM in order to make the game display the right graphics and play the right cry for randomized starters. Attempting to apply these changes twice creates invalid code.
