### ISSUE TITLE
Bad CRC32

### ISSUE THREAD

**Issue by DragonARandom** [Ajarmar/universal-pokemon-randomizer-zx#438]
I have started getting a red notice saying "[Bad CRC32]" within the ROM information of the randomizer. I was not getting this issue last month and it seems to not have an issue with DS and GBA games, but with X and Y an USUM it seems to not want to randomze. I don't know what might be causing this and I am not making much sense with quick searches. This notice shows up with EVERY ROM I have, but it does not seem to effect all games. 

I am using v4.3.0

**Comment by tom-overton** [comment]
This just means that the ROM is not considered a clean, unmodified, and official ROM. You should still be able to load them and use them just fine; the randomizer is just warning you that they are not clean. I'll change the error message in a future version of the randomizer in order to make this a little more clear.
