### ISSUE TITLE
[Bug] 3DS games wont import

### ISSUE THREAD

**Issue by MetaMaxis** [Ajarmar/universal-pokemon-randomizer-zx#441]
**Describe the bug**
Any time i try to open a 3DS game to randomize, it just stays like this, for hours and never progresses 
![image](https://user-images.githubusercontent.com/105760028/168937045-a123a0da-4991-4889-a811-8bc93df97724.png)

**Expected behavior**
It worked once, correctly, and i WAS able to import a game from the 3ds and randomize it, but i needed to make a second file, and it now doesn't work correctly. I didn't download anything or change my rom, so I'm just stumped. 

**Screenshots**

**System (please complete the following information):**
 - Operating System: Windows 10
 - Java Version: x64 or 64x i forget how its written, the one they recommend you to get here. 
 - Randomizer Version: 4.40

**Additional context**
Somewhat pressing issue, as I'm doing a sleeplocke for my channel on thursday. Would like to know how to fix it.

**Comment by tom-overton** [comment]
Can you explain a bit more what your workflow is? I'm not sure what you mean by "It worked once, correctly". What does that mean? Does that mean it worked with a previous version of the randomizer? Does that mean it worked with one game (for example, ORAS) but not another (for example, USUM)? What does "worked" even mean in this case; the randomizer produced a successful CXI or layeredFS? Can you create a log file for this "working" case?

I also don't know what you mean by "make a second file;" are you loading a different game into the randomizer? The same game? The same game, but randomized?

**Comment by MetaMaxis** [comment]
Two days ago, I opened the randomizer, clicked Open ROM, and the loading screen lasted only a few second and (in this case "worked" means it allowed me to randomize the file and progressed past the Loading box) it let me randomize the game file like any other when i did a test of X to see if I could randomize 3DS games, and if they took longer. 

Today, I went back to randomize more filed in preparation for the sleeplocke, and now when I repeat the process of clicking Open ROM, it only stays on that loading screen. I was going to make more randomzied files, since if I failed one run, I'd need to restart with a different run (one that was randomized differently)

**Comment by tom-overton** [comment]
Thanks, that makes it much clearer. I'm guessing that that two days ago, it was v4.4.0 as well? Since you said you hadn't downloaded anything in the original post.

This issue is sort of weird in that we've never been narrow down a particular solution. I put some logging in the randomizer to try and figure out what's going on; in the command prompt, you should see some lines like this:
```
NCCH: Reading exefs...
NCCH: Done reading exefs
NCCH: Reading romfs...
NCCH: Visiting file btl_ai.garc
```
And so on. Can you send over the *entire* contents of what's being printed to the command line? It might be too big for Github, in which case you can use an external site like pastebin.com. I want to see what file, if any, the randomizer is "stuck" on.
