### ISSUE TITLE
[Help] I can't use the launcher_WINDOWS.bat because it shows Invalid maximum heap size: -Xmx4608M

### ISSUE THREAD

**Issue by silver028** [Ajarmar/universal-pokemon-randomizer-zx#442]
**Describe your problem clearly:** 

**System (please fill in the following information):**
 - Operating System: windows 10
 - Randomizer Version: v4.4.0

**If your problem is that you can't randomize a game:**
If you get a popup saying that there has been an "unhandled exception", please attach the error log as an attached file to this issue.

**Comment by tom-overton** [comment]
This is a pretty common problem; it indicates that you have 32-bit Java installed instead of 64-bit Java. You can see our [Java wiki page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) for more info. I believe [this link](https://java.com/en/download/) should let you download 64-bit Java for Windows, but if it doesn't explicitly say "64-bit", then take a look at the Java wiki page for links to other versions of Java.
