### ISSUE TITLE
[Contribution Idea] Set Player Name

### ISSUE THREAD

**Issue by Zach-Meadows** [Ajarmar/universal-pokemon-randomizer-zx#456]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** 
Adding an option for players to SET their default name, instead of typing it in each time. This would replace the "Random name" feature that is default set in most games when no text is put in.

**What problem would your contribution solve? Please describe:** 
saving time when it come to randomizing new roms and naming your character each time.

**Additional context:**

**Comment by tom-overton** [comment]
Sorry, but I don't think this is a particularly good fit for the randomizer for a variety of reasons:
- Only the first four gens actually offer support for this. Starting from Gen 5 onwards, the player is *required* to enter a name in the keyboard. I even checked the Switch games for completeness's sake. The belief that "most games" have a random name feature is wrong; it's actually only about half of them.
- The way this is implemented in certain games makes it very difficult to replace it with a user-supplied string without shifting the ROM. I know for a fact that in Gen 3, the only edits you can make are ones that preserve the length of the string; for example, you can change "GREEN" to "KAIZO". But you cannot increase the length of these strings without shifting things around, and the longest default name in FRLG is only six characters; if I wanted to name myself "Jeffrey", I couldn't
- Even accounting for that, you'd still need to make code patches for every single game. The way the random name thing works is that it's, well, random. You would need to change the code to make it not random, requiring many code patches to live in the randomizer.

Ultimately, this seems like something far more suited to a specific in-game patch that exists outside of the randomizer, rather than something built directly into it. It seems like a *lot* of effort to write multiple code patches and get this working across all the various games for the very niche benefit of not having to type your name in-game.
