### ISSUE TITLE
[Bug] the java VM not working  

### ISSUE THREAD

**Issue by Reanimga** [Ajarmar/universal-pokemon-randomizer-zx#457]
Whenever I try to run the launcher_WINDOWS.bat file it says "Invalid maximum heap size: -Xmx4608M
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit."

**Comment by tom-overton** [comment]
This is a pretty common problem; it indicates that you have 32-bit Java installed instead of 64-bit Java. You can see our [Java wiki page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) for more info. I believe [this link](https://java.com/en/download/) should let you download 64-bit Java for Windows, but if it doesn't explicitly say "64-bit", then take a look at the Java wiki page for links to other versions of Java.
