### ISSUE TITLE
Generate multiple seeds option

### ISSUE THREAD

**Issue by Jaytrox19** [Ajarmar/universal-pokemon-randomizer-zx#464]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** 
A new exporting option, which allows to create multiple (custom amount) randomized ROMs. Ideally it opens a dialog beforehand with checkboxes for saving the log files as well as the seed codes, which makes the individual "post-saving" dialogs obsolete.

**What problem would your contribution solve? Please describe:** 
Many challenge runs require a large amount of seeds due to restarts on faint, e.g. the "Ironmon" challenge. Currently you need to create each seed individually, which is a tedious task when you burn through them rather quickly (a good amount of runs end at the very first fight)

**Additional context:**
Since i was unsure about my abilities to code this, i already did some work and managed to get a working prototype. Needs some more work for a flawless implementation, but the core feature is up and running, exporting ROMs with user chosen names that end with incremental numbers, starting at whatever has been chosen (or 1 when none were given)

**Comment by sornerol** [comment]
Oddly enough, I came here to suggest the same thing when I noticed this issue had just been opened.

I've been tinkering with getting a working prototype going and just committed my quick-and-dirty proof of concept to https://github.com/sornerol/universal-pokemon-randomizer-zx/tree/bulk-randomized-roms.

![batch_rando](https://user-images.githubusercontent.com/47842483/173933981-40756f4c-6be5-4da3-94e7-c9bb32deff85.png)

**Comment by Jaytrox19** [comment]
Haha, thats awesome.
I had a quick look at your repo and as far as i can tell, you only did some GUI work so far without any actual implementation?

**Comment by sornerol** [comment]
My apologies. I forgot to push my latest commit. I just now pushed it.
In terms of my implementation, there's definitely some work to be done before it's ready for general usage. I have it working well enough for my purposes. I didn't want to invest much more time into it until I knew the main developers were interested in such a feature.

**Comment by Jaytrox19** [comment]
Ah, i see. Looks good to me so far.

Something i do wonder about tho, the way you generate the file names... doesnt it produce filenames like "_PathToFolder_\Firered.gba.0", so adding the numbers behind the file extension?

Apart from this, i did quite some String manipulation to continue counting from a given digit, e.g. if i want to start with "Firered91.gba" it continues from there, so "Firered92.gba", "Firered93.gba" and so on.

As you said though, its only a quick and dirty prototype, I am just giving you some things to consider if the devs agree to adding the feature :)

Looks to me like you got this covered, i hope (and they probably will) agree to add this.

**Comment by sornerol** [comment]
Thank you for the feedback. Yes, right now the file names are generated as "filename.gba.0." This is one of the issues that would need to be fixed if this feature were to be added (I play using an everdrive, so it works well enough for my usage).

**Comment by Ajarmar** [comment]
Batch randomization is already possible by using the randomizer's CLI and using a script (in fact, I think the ironmon crew have such a script available in their discord), but I can see the benefit of having it available in the GUI to make it easier to use since most users don't know how scripts work. However, it will have to be under a few conditions - I hope you'll excuse that I'll be a bit picky about this, but for this addition to be worthwhile it needs to offer the same functionality that a script does while also being easier to use.

1. The GUI is already quite cluttered, and I prefer not to have any major changes to the area at the top of the GUI. For that reason, the batch randomization option should be part of the "Settings" menu (as a button that opens up a new window where you can make the necessary configurations).
2. The "batch randomization" window should have at least the following options:
    - Enable/disable batch randomization
    - Amount of randomized games to generate
    - Starting index for filenames
    - Enable/disable generating a log for each seed
3. When the seeds are being generated, there should preferably be some sort of progress indicator showing how far it's gotten (e.g. a string saying "Generating seed x out of y")

What do you think? I guess the question goes to both of you, since it seems like both of you were planning on implementing it. Would you be interested in implementing this?

**Comment by sornerol** [comment]
I just learned of the existing batch randomization functionality a few minutes ago while watching an ironmon stream. For me, I think I would prefer to just use the CLI. That said, I do still think it would be a nice feature to have in the GUI, and I would be happy to implement based on your feedback.

However, since @Jaytrox19 is the one who posted the issue, I will ask if they are interested in implementing first. If not, I can get started on implementing based on the requirements above.

**Comment by sornerol** [comment]
Since I haven't heard anything from Jaytrox, I've gone ahead and started working on this. I hope to have a PR ready for review in a couple of days.
