### ISSUE TITLE
Include existing option to evolve into megas/alt formes in gen 6 [Contribution Idea]

### ISSUE THREAD

**Issue by UTDZac** [Ajarmar/universal-pokemon-randomizer-zx#465]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** 
This is a change to an existing setting. Right now there exist a setting that is only visible in gen 7 and higher Pokemon games. I'm suggesting a change to allow this for gen 6 and higher.

**What problem would your contribution solve? Please describe:** 
This change would be something that is enabled for the base rules for XY and ORAS Ironmon challenges, allowing players to evolve their Pokemon into a larger pool of Pokemon (would include megas). This is helpful to make the more difficult challenge modes doable for gen 6.

This was brought to my attention by someone who is currently using this setting to play gen 6 games (Kaizo ORAS) so they have the option to evolve into mega evos for a chance at a better pool of Pokemon. They made this change themselves on their own build.

**Additional context:**
(Not sure how best to link the affected line of code, I think this is the right spot to change anyway.)

The following line in NewRandomizerGUI.java
`peAllowAltFormesCheckBox.setVisible(pokemonGeneration >= 7);`

can simply be changed to
`peAllowAltFormesCheckBox.setVisible(pokemonGeneration >= 6);`

which will allow the user the choice of being able to include this if they so choose.

**Comment by tom-overton** [comment]
I think there might be some confusion here, so let me make some things clear. In the Generation 6 games, a Pokemon cannot change formes upon evolution. For example, let's say you have a Charmeleon; internally, the game thinks of that as species 5, forme 0. In an unrandomized game, Charmeleon evolves into Charizard; how does the game internally keep track of this? Well, it just says "Charmeleon evolves into species 6"; it doesn't keep track of the forme at all. Thus, when you evolve, you keep whatever forme you had before; our Charmeleon will turn into species 6, forme 0, aka Charizard. It is impossible for a Charmeleon to turn into species 6, forme 1, aka Mega Charizard X.

We hide this setting in Gen 6 because it simply doesn't work in that game. One would need to make extensive changes to the game's code in order to make it work. You mentioned that someone else has already made this change; if so, then one of two things has happened here:
1. They enabled this setting without realizing it's non-functional in Gen 6, in which case all they've really done is broken the randomizer's evolution logic.
2. They actually edited the game's code to make this work, in which case they should get in touch with us immediately.

Given the wording of this post, I assume the former is what happened here, but I'll leave this open just in case it's the latter.

**Comment by UTDZac** [comment]
Ah, thank you for that detailed responses and clarification. I was also baffled a bit when they told me they had changed it to make something happen. I hadn't seen it in action myself, so I agree, I think it is the former. I will let them know.

Appreciate it!

**Comment by MercRiin** [comment]
Alright, first of all thanks a lot for clarifying!

I'm curious tho, are there any ressources on how to mod Gen6 Games? like specifically ORAS (but i assume XY would work just the same once you figure it out)

Also, did people put time into specifically modifying the Evo Mechanics for Gen6 already or did just noone bother yet?

I personally just feel like including the possibility of Megas through Evo, maybe through a patch like the QoL patches or something, would just make the whole run that much more interesting.

**Comment by tom-overton** [comment]
I might have accidentally instilled some false hope, so let me be frank: making this work in Gen 6 is an absolutely ridiculous amount of work. There's a reason that no one has done it; it's because it's insanely difficult. It might not even be feasible whatsoever. There's also a reason why, in my original reply, I said that if someone got this working, "they should get in touch with us immediately"; because such a person would be a technical genius.

This is simply not happening unless someone who is unbelievably dedicated to this specific cause puts in weeks, if not months of work into making this happen. This is not a project where someone with no modding experience will be able to pick it up and finish it over a weekend.

I'm going to close this issue for now, since this is not happening any time soon. If you really, *really* want to try this (which I highly advise you ***not*** to do!), download [Ghidra](https://ghidra-sre.org/) and start familiarizing yourself with the game's internals.
