### ISSUE TITLE
Invalid Maxmimum Heapsize

### ISSUE THREAD

**Issue by StealthHawkDude** [Ajarmar/universal-pokemon-randomizer-zx#468]
Whenever I launch the .bat file I get an error. I tried updating my java but that didn't seem to fix it, and this doesn't allow me to randomize 3ds games.

Version 4.4 of randomizer

I got Java version 8 update 33 which is the latest available on my system
![image](https://user-images.githubusercontent.com/107808153/174492421-2c6941b3-1e6a-4d06-b1b8-84dfe7603147.png)

**Comment by tom-overton** [comment]
This is a pretty common problem; it indicates that you have 32-bit Java installed instead of 64-bit Java. You can see our [Java wiki page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) for more info. I believe [this link](https://java.com/en/download/) should let you download 64-bit Java for Windows, but if it doesn't explicitly say "64-bit", then take a look at the Java wiki page for links to other versions of Java.
