### ISSUE TITLE
[Bug] Universal randomizer unable to open!

### ISSUE THREAD

**Issue by awhite2002** [Ajarmar/universal-pokemon-randomizer-zx#472]
Invalid maximum heap size: -Xmx4608M
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Press any key to exit...

The text above is the message that I get when I trey to open the bat file that is required to open. However, the file after I extract is not a bet file which I think may be the issue. Even after this new version and update I am still getting this same message after I try to open the universal randomizer and the other file says that I can't upload any of the 3ds game files onto it so its basically the same problem as before. This bug needs to be fixed.

**Comment by tom-overton** [comment]
This is a pretty common problem; it indicates that you have 32-bit Java installed instead of 64-bit Java. You can see our [Java wiki page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) for more info. I believe [this link](https://java.com/en/download/) should let you download 64-bit Java for Windows, but if it doesn't explicitly say "64-bit", then take a look at the Java wiki page for links to other versions of Java.
