### ISSUE TITLE
Need a "No Early Wonder Guard" option for wild pokemon encounters [Contribution Idea]

### ISSUE THREAD

**Issue by Kycrio** [Ajarmar/universal-pokemon-randomizer-zx#473]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** 
New setting

**What problem would your contribution solve? Please describe:** 
Forced early-game static encounters that you MUST DEFEAT to progress become impossible if the opponent is Shedinja. The Spearow bridge in S/M & US/SM is a wild pokemon that must be defeated to progress. 

**Additional context:**
Started up my first randomizer of Pokemon Ultra Sun, got Sceptile as a starter. Before you can get Pokeballs, you have to fight the Spearow on the bridge. It randomized to Shedinja, and since I only have normal and grass moves, I can't beat Shedinja. Would be faster to randomize a new game than to try and get to Struggle to beat it.

**Comment by tom-overton** [comment]
Hey, thanks for suggesting this idea. We're actually thinking of splitting static Pokemon that you can catch from static Pokemon that you *cannot* catch, and this early Spearow is one such example of the latter category. For non-catchable statics, we can give them more Trainer Pokemon-esque settings like No Early Wonder Guard.

Rather than having you implement something that we're eventually going to get rid of, we'll just punt on this idea for now and implement it once we separate catchable and non-catchable statics.
