### ISSUE TITLE
Make "Prefer Same Type" option for randomized movesets a slider [Contribution Idea]

### ISSUE THREAD

**Issue by JkHowling** [Ajarmar/universal-pokemon-randomizer-zx#475]
One of the only things keeping me from using this over PK3DS for gen 6+ randomizers is the fact that there's no customizable options for randomizing STAB preference on movesets. PK3DS provides the option of setting your own percentage, and I don't see why this couldn't be an option here.

Instead of forcing a mere 40/60 stab/non-stab preference, let us slide on increments of 5 or 10% maybe. Gives people more options and control over their level of randomization in terms of learnsets, rather than "either you get entirely random, mostly random with maybe a tiny bit of stab sometimes, or vanilla."

**Comment by Ajarmar** [comment]
Hi, sorry for the delayed response. We'll pass on this, as I think this setting risks being more confusing than useful; it's hard to intuitively understand what a "good" STAB ratio is, so users might self-sabotage on accident because they think 40% seems too low. The 40/60 ratio was chosen through testing, and if you look at learnsets in the regular games it's actually not uncommon to see that kind of ratio. (That's not to say that you _have_ to think 40/60 is perfect, but to say that it's "maybe a tiny bit of stab sometimes" is far from correct)

Thanks anyway!
