### ISSUE TITLE
[Bug] Invalid maximum heap size -Xmx4608M

### ISSUE THREAD

**Issue by 999999090** [Ajarmar/universal-pokemon-randomizer-zx#479]
**Describe the bug**
I don't know if someone already said something like this, but looking it up didn't yield any results, so I'm reporting this issue. Instead of the usual issue people seem to see with Xmx4096M, it says Xmx4608M instead. I tried reinstalling Java, deleting older versions of Java, and reinstalling the randomizer, but nothing seems to work. Is there something I am missing?

**To Reproduce**
1. Install Java and the randomizer
2. Double click on 'launcher_WINDOWS.bat'
3. See error

**Screenshots**
![image](https://user-images.githubusercontent.com/108588994/177011683-b7d60d3b-2849-456f-9d0e-25ec38491881.png)

**System (please complete the following information):**
 - Operating System: Windows 10 Home
 - Java Version: Java 8 Update 333
 - Randomizer Version: 4.5.0

**Additional context**
I don't know if it would save time, but the settings already say I'm using a 64-bit operating system, so it's not that causing the issue.

**Comment by tom-overton** [comment]
This is a pretty common problem; it indicates that you have 32-bit Java installed instead of 64-bit Java. You can see our [Java wiki page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) for more info. I believe [this link](https://java.com/en/download/) should let you download 64-bit Java for Windows, but if it doesn't explicitly say "64-bit", then take a look at the Java wiki page for links to other versions of Java.

The reason why you're seeing 4608 instead of 4096 is because we bumped the amount of memory that the randomizer requests a while back.
