### ISSUE TITLE
[Bug] HP can underflow upon evolution

### ISSUE THREAD

**Issue by valiant-code** [Ajarmar/universal-pokemon-randomizer-zx#480]
**Describe the bug**
HP can underflow when evolving to a pokemon with lower max HP.

**To Reproduce**
1. Have an unevolved pokemon with very very low HP
2. Evolve it to something with lower max HP
3. See pokemon with current HP value of 65000

**Expected behavior**
Probably Max HP should never go down upon evolution.

**Screenshots**
https://www.twitch.tv/videos/1520867695

**System (please complete the following information):**
(I don't know I'm just filing this bug after seeing it on a stream)
 - Operating System: 
 - Java Version:
 - Randomizer Version: 4.4.0

**Additional context**
Random Seed: 272576952669963
Settings String: 318WRIEEjIAAAMABgCRAAKeBnsEiAEAFAACCQAuEgAAAAAABRi45ATkAYYICTIGBAIyEwUQRmlyZSBSZWQgKFUpIDEuMVqS+hQq2hqb

**Comment by tom-overton** [comment]
This is now documented on the Known Issues page: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Known-Issues#all-games

There is no real way to fix this given how fully random stats is designed. The "correct" thing to do would be to never let max HP drop upon evolution, but this would be a pretty big deviation in how users expect this setting to work. If this randomizer was being written from scratch in 2022, I would certainly make it so that max HP could never drop, but given the way this setting has worked for the last ten years, I don't want to break how users expect it to work.
