### ISSUE TITLE
[Contribution Idea] Option to have lowercase trainer/npc names, locations names, etc

### ISSUE THREAD

**Issue by OverlordEclipse** [Ajarmar/universal-pokemon-randomizer-zx#492]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** 
This idea originates from the current lowercase pokemon names, however, I believe that adding an option to correct the names of various different places and people would be great.
**What problem would your contribution solve? Please describe:** 
This option would help fix the annoyance of seeing a randomly capitalized word in the middle of a sentence is similar to what the lowercase pokemon names option does.
**Additional context:**
I greatly like the lowercase pokemon names option and would like to be able to play a pokemon game where the trainers and locations are the same. I don't truly expect for this to be implemented as it seems like an annoying process for something that isn't that big of an issue.

**Comment by tom-overton** [comment]
Sorry, we'll pass on this one. The lowercase Pokemon setting exists because their names are stored in an easy-to-understand table; it's easy to just go through the whole thing and fix them all up. However, people and place names are interspersed throughout the in-game text, and we would have to do some sort of heuristic to look for ALL CAPS words in sentences, which I'm sure might break. Ultimately, it's more trouble than it's worth.
