### ISSUE TITLE
I have a problem. when I open it through the zip file it says it is unable to access the file, even when copied it to anther folder, and when I extracted the zip file, it says it's couldn't create the java virtual machine

### ISSUE THREAD

**Issue by Erez357** [Ajarmar/universal-pokemon-randomizer-zx#495]
I have a problem. when I open it through the zip file it says it is unable to access the file, even when copied it to anther folder, and when I extracted the zip file, it says it's couldn't create the java virtual machine

_Originally posted by @Erez357 in https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/221#issuecomment-1185726204_

**Comment by Erez357** [comment]
![dgmj](https://user-images.githubusercontent.com/109368144/179271893-2094605a-b742-4d11-be5d-aad7b1350c97.png)
![v](https://user-images.githubusercontent.com/109368144/179271905-fe5604c4-47af-48e2-b59d-8e42806472bb.png)

**Comment by tom-overton** [comment]
Your second screenshot indicates that you have 32-bit Java installed instead of 64-bit Java. You can see our [Java wiki page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) for more info. I believe [this link](https://java.com/en/download/) should let you download 64-bit Java for Windows, but if it doesn't explicitly say "64-bit", then take a look at the Java wiki page for links to other versions of Java.
