### ISSUE TITLE
Request: Want an option to remove the extra berries added into Gen 4 as of v4.5.0+

### ISSUE THREAD

**Issue by UTDZac** [Ajarmar/universal-pokemon-randomizer-zx#497]
With the release of Randomizer ZX 4.5.0, the bad item table for HGSS was update to remove [29 specialty berries](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Items/_compare/9121ab84fd75bf8cbf5fdb2580eb64122dc80bff#diff-767ff835e4b02089661bfa7564a6de056cfaa130e94b69e8011a2cb1564de260L159-L187), effectively allowing them to appear in the normal pool of randomized items. While this is a good addition to line up gen4 with other gens, it has had a negative effect on many of the IronMon challenges (notably Kaizo and Survival).

I've spoken with a handful of IronMon community members, streamers, and other runners of who are unhappy with the addition of these extra items. The most common reason being that this change dilutes the pool of items, and as a result lessens the odds of getting more important items like potions and elixirs in order to survive a run.

While I don't know the full intent of this bad item pool change, I do know that it has impacted quite a few people in the ironmon community. So much so that many are choosing to not use the v4.5.0 and go back to v4.4.0 to play the game. 

### Suggestion:
Allow a checkbox option to remove these specialty berries if the option for ban bad items is checked. It's possible there may be a better way to go about it, but this accomplishes the goal in the simplest manner.

I suppose a contribution idea that I wouldn't mind exploring would be the ability to adjust the entire list of what items are considered "bad items," allowing for more control over the balance of the item pool and the option to build challenges/rulesets around this.

**Comment by DrDoktor** [comment]
author doesnt do requests

**Comment by tom-overton** [comment]
The intent behind removing those berries from the bad item pool is pretty simple; they're good items. Imagine a scenario where your best Pokemon has a 4x weakness to a particular type, and a gym leader has a Pokemon that can outspeed and one-shot your Pokemon with a move of that type. Wouldn't a weakness-reducing berry help in this scenario? When choosing "Sensible Items" for Trainer Held Items, we would put these types of berries on Trainers, so they were *already* considered useful, too.

In general, we're pretty permissive as to what we consider to be a non-bad item. Something like Toxic Orb might seem pointless for most playthroughs, but it is highly valuable on a Pokemon with Poison Heal or Guts. Lagging Tail might seem like purely a detriment, but you can use it to power up moves like Avalanche, or you can Trick it onto an opponent. Nuggets literally don't do anything, but you can sell them for money. In fact, we consider the Shards in Gen 7 non-bad items despite them having no use until the postgame. The reason? They sell for 500 dollars, which is a decent chunk of change earlygame.

Hopefully, that gives you a bit of insight into our philosophy behind what is considered a non-bad item. We generally like let many relatively niche items through, and we're also fine with players just selling items they don't want. What's happening here is that certain challenge runs (Ironmon included) place restrictions on what items you can use and where you can acquire them. This dramatically changes what is considered a "bad item", since many things that are useful in more casual play become completely useful. What use is a Nugget when you can't buy anything? What value does a Max Revive bring when you aren't allowed to use it?

It's impossible for us to cater to every sort of challenge (since more and more are invented every single day), so we simply choose not to do so. With that in mind, I simply don't think a checkbox option to remove these berries is a good idea at all. Regular users will simply be confused as to why the option exists in the first place, and for users intending to do challenge runs, it may open the floodgates to all kinds of requests. If berries can be banned by the randomizer, why not [Toxic Orb](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/pull/129)? Or [the various Incense items](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/pull/130)? Or why not abilities like [Impostor and Innards Out](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/pull/460)? As Ajarmar said in response to that last one:
> We prefer not to accept additions like that because we don't really want anything to do with the balancing process of the various rulesets out there. With people always making new rulesets, and communities surrounding these rulesets not always agreeing on what should or shouldn't be part of them, it's not worth the trouble for us to involve ourselves in that.

With that in mind, I'm going to close this issue, since there's simply no way we would ever implement something like this in the randomizer. If you want to open a separate issue for the contribution idea you mentioned, feel free to do so.

**Comment by UTDZac** [comment]
Thank you so much Tom for taking the time to write all of this out. I understand the difficulty and balance of making a decision such as this, and I respect your stance. We will figure something out on our end and make it work.

As always I, and the community as a whole, really appreciate you and all the work you've done on this project.
