### ISSUE TITLE
Update Settings file option not listed

### ISSUE THREAD

**Issue by VictorKruger** [Ajarmar/universal-pokemon-randomizer-zx#500]
Hello,

I'm attempting to load a settings file which then throws the error:

`The settings file is old and must be updated. Press Settings -> "Update Pre-3.0.0 Settings File" to update.`

However when I follow the directions there isn't an option in the settings menu.
![Settings listing](https://user-images.githubusercontent.com/69117382/179680039-869affb4-effc-4b88-8a37-1c55b1fd59cf.png)

[Java Output.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/9138096/Java.Output.txt)

[kaizo-ironmon-plus-randomizer-settings.rnqs.txt](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/9138100/kaizo-ironmon-plus-randomizer-settings.rnqs.txt)

System:    Kernel: 5.15.0-41-generic x86_64 bits: 64 compiler: N/A Desktop: Cinnamon 5.2.7 
                 wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una base: Ubuntu 20.04 focal 

java --version
openjdk 17.0.3 2022-04-19
OpenJDK Runtime Environment (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1)
OpenJDK 64-Bit Server VM (build 17.0.3+7-Ubuntu-0ubuntu0.20.04.1, mixed mode, sharing)

Please let me know if you need any other info.

**Comment by tom-overton** [comment]
We removed this way back in v4.1.0 due to being very outdated. However, it's clear that we forgot to remove the thing telling you to use this option; let me fix that now. To upgrade your settings string, grab an older release like [v4.0.2](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases/tag/v4.0.2) where this option still exists.
