### ISSUE TITLE
[Contribution Idea] Dynamic move names

### ISSUE THREAD

**Issue by super-rude-duck** [Ajarmar/universal-pokemon-randomizer-zx#505]
**Is your idea a new setting, a change to an existing setting, or something else? Please describe clearly:** So basically, I like the idea of randomizing types for moves since it opens up so many new avenues of play and it makes the game feel a lot more fresh. But the issue I can't deal with is the muscle memory and how continually jarring it is when things like FLAMEthrower does fighting damage. For me it's important that there is some logic to it and that it makes some kind of sense, that it's not just some totally nonsensical random thing. So basically my idea was to add an extra toggle for when you randomize moves to change the move names to fit the new type. For example of Icicle Spear becomes fighting type it might be named Aura Spear or something. Something where if you know pokemon well the name will clue you in to what it is, and fit thematically. Ofc it would still have the original graphical effect, but you can't win em all.

**What problem would your contribution solve? Please describe:** The issue above where it's so jarring when moves have different types than their names clearly indicate. I understand that probably most people don't have this issue, but for me this would be a game changer. Hence why I'd be willing to do it.

**Additional context:** I'm a mid tier JS/TS webdev (4 years experience) but I can probably figure out how to do this in java, how hard could it be?

**I understand that I am expected to implement this change myself in the randomizer's codebase: [ X ]**

**Comment by NARFNra** [comment]
I think I would appreciate this a lot, personally, as it's always been somewhat of an issue for me playing with that option. It seems like it'd be relatively easy to actually handle the implementation, but would mostly be troublesome in that you'd need to make a giant list of adjectives and define the swap points for each move, respecting game move length limitations, etc.

It reminds me of a really old experimental randomizer I used to toy with that renamed Pokemon similarly, with occasionally silly results.

**Comment by Ajarmar** [comment]
Thanks for the submission, but we'll pass on this for the following reasons:

1. I think this has the risk of making the game _more_ confusing since some things are just not going to make sense no matter what you do. Flamethrower will still have a chance of burning the opponent even if it's a Fighting move, and the move description will still mention fire. Additionally, it may make the moves much harder to recognize - sure, you get to know the type from the name, but if you can't recognize the actual move easily then you can't know its other effects.
2. Icicle Spear -> Aura Spear is a nice example for this since it just works without any problems, but there are many move names that would be far more problematic to make recognizable after the name is changed. For example, what about: Inferno, Thunder, Blizzard, Hurricane, Glaciate, Incinerate, Submission, Strength, Psychic, Lunge? These are just a few examples - as of Ultra Sun/Ultra Moon, there are 728 moves in the game, and there are many where trying to change their names to match a different type is just not intuitive at all.
3. There's quite a bit of similar move names in Pokemon. How are you supposed to tell Ice Beam and Signal Beam apart if their names change? And what if they are given the same type?
