### ISSUE TITLE
When randomizing movesets, Crystal has the option to guarantee a certain number of starting moves, but Gold/Silver do not

### ISSUE THREAD

**Issue by Zander251** [Ajarmar/universal-pokemon-randomizer-zx#506]
As the title says, when randomizing a ROM of Crystal, I have the option of guaranteeing that every Pokémon starts out with up to 4 moves if I choose to randomize movesets. However, the same option does not seem to be available when randomizing Gold and/or Silver, and I'm wondering if there is a reason for this or if it's just an oversight. 

![Crystal](https://user-images.githubusercontent.com/110001421/181106324-5c2795ec-ed9f-4267-a939-10169a0e8a87.png)
![Gold](https://user-images.githubusercontent.com/110001421/181106142-4032e3e6-dd9b-4a2b-bf3e-4e9c88761076.png)
![Silver](https://user-images.githubusercontent.com/110001421/181106236-4031746f-ad00-4fd9-bdd7-ce93a099b09a.png)

**Comment by tom-overton** [comment]
Yeah, this is intentional. Trying to enable an increased amount of starting moves in Gold/Silver will overflow the space available for Pokemon movesets. For whatever reason, Crystal has enough room here to make everything fit. Fixing this would require doing a bit of reprogramming as to how Gold/Silver handle movesets, and it's not really worth it considering it works fine in Crystal.
