### ISSUE TITLE
[Help] keep getting the Invalid maximum heap size: -Xmx4608M command prompt

### ISSUE THREAD

**Issue by Takenwallet** [Ajarmar/universal-pokemon-randomizer-zx#507]
So every time i try to open the client version _WINDOWS i get the invalid max heap size popup in command prompt, but idk what to do about it

java version "1.8.0_341"
Java(TM) SE Runtime Environment (build 1.8.0_341-b10)
Java HotSpot(TM) Client VM (build 25.341-b10, mixed mode, sharing)

this is my Java version

**Comment by tom-overton** [comment]
This is a pretty common problem; it indicates that you have 32-bit Java installed instead of 64-bit Java. You can see our [Java wiki page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) for more info. I believe [this link](https://java.com/en/download/) should let you download 64-bit Java for Windows, but if it doesn't explicitly say "64-bit", then take a look at the Java wiki page for links to other versions of Java.
