### ISSUE TITLE
RBY: "Unchanged" settings still randomizes the Pokemon in the New Game intro

### ISSUE THREAD

**Issue by HeyItsLollie** [Ajarmar/universal-pokemon-randomizer-zx#53]
If you load R/B/Y into the randomizer, and then save with zero randomizer features enabled, the New Game opening will still display a randomized pokemon.
![UPRZX](https://user-images.githubusercontent.com/30498581/98140696-769f7980-1f11-11eb-90d4-0514e74589fa.png)

While this is obviously a small and negligible randomization, it makes me wonder if anything else ends up getting patched in an "Unchanged" randomizer rom.

**Comment by tom-overton** [comment]
This is something that ZX has left untouched from the original Universal Pokemon Randomizer, and from my reading of the code, I believe this is actually *by design*. The intro Pokemon is changed by a method in each RomHandler called "applySignature." The name is a little vague, but I believe it to mean "apply proof that the game has been run through the randomizer". In other words, there is no mechanism to opt-out of this change, and I can see the reason it was originally done. The idea is to be able to *immediately* tell that the game has been randomized, and the intro is a pretty good place to do that.

Your concern about wondering what else has been changed in an "Unchanged" ROM is valid, but in this particular case, it seems like there's no issue here.
