### ISSUE TITLE
[Bug] When randomizing wild pokemon, Unowns cannot be encountered in games where they could have appeared in the wild naturally 

### ISSUE THREAD

**Issue by jtigues** [Ajarmar/universal-pokemon-randomizer-zx#537]
**Describe the bug**
You can never encounter an unown outside of the maps where they would naturally appear. 

**To Reproduce**
1. Randomize wild pokemon in a game where wild unowns would exists naturally (FRLG, HGSS, DPPt, ORAS), generate log
2. Go to a route where unown has been rolled as one of the random encounters. Cannot be one of the places unown would normally appear in that game (Ruins of Alph, Tanoby Chambers, etc.)
3.  Try to find unown (never happens)

**Expected behavior**
The randomizer is technically working perfectly fine, I would imagine one of two solutions:
1) ignore unown when randomizing wild pokemon for the mentioned games
2) adjust the logic for the various games which checks if you are in the expected unown zone to always return true (no single script across games though from what I could tell sadly)

**System (please complete the following information):**
Windows 10
Randomizer version 4.5.1
Java 1.8.0.333

**Additional context**
The games with naturally occurring unown have logic that when you would encounter an unown, the player's current/most recent "unown map zone" (i.e. which room in the tanoby chambers/ruins of alph etc.) is pulled to determine which letter of unown you would find. Additionally, a check occurs if the player has not yet been to or is not currently in one of the map IDs where you could normally find unowns, and if it returns false the encounter will fail to generate.

**Comment by Mortiam** [comment]
I'm currently playing Pokemon Crystal. Unown was assigned to Route 44. I could find it there no problem, once I solved the first puzzle in the Ruins of Alph.

**Comment by jtigues** [comment]
Sorry for the late reply, forgot this was raised. But interesting, didn't think to check the Gen 2 logic, was mostly focused on Gens 3 and 4.
In HeartGold specifically, we've had folks even have Unown be the Ruins of Alph spawn, but it still never showed up. Maybe they just didn't do the puzzle though, can't say I know for sure. Will check if I can find some unowns in a seed.

In Fire Red/Leaf Green it's more noticeable since you can't even unlock the chambers until after the elite 4.

**Comment by tom-overton** [comment]
Thanks for filing this. I tested this out by replacing literally every wild encounter with Unown. In GSC and HGSS, Unown won't show up until you finish one of the puzzles in the Ruins of Alph, so in my test, I didn't see *any* wild Pokemon until I did a puzzle. To fix this, I just banned Unown from being a wild encounter in those games. For FRLG, the randomizer *already* banned it from showing up as a random encounter in those games, since trying to spawn an Unown outside of the Tanoby Ruins can crash the game.

For every other game, Unown works fine, so I didn't do anything. I didn't test if every single Unown letter can show up outside of Solaceon Ruins in DPPt, but I don't really care; *some* Unown letters work fine, so whatever.

**Comment by Mortiam** [comment]
Does that mean the Pokedex can't be completed any more in those games?

**Comment by JackTDB** [comment]
Good timing for this issue to be revisited, as I have recently started searching for all unown forms in my Platinum game.
What I am finding after many excruciating hours is that only 20/28 of the unown forms are able to found in the (randomized encounters) wild. This somewhat makes sense, as the solaceon ruins are ordered so that 6 main hallway rooms each only have F, R, I, E, N, and D unown encounters in the vanilla game, and the "deadend" rooms have the remaining 20 unown. In addition, the room at the end of the Maniac Tunnel (unlocked only by finding 26 unown forms supposedly) has the ? and ! unown forms. Fittingly, the 8 unown forms I was missing were F, R, I, E, N, D, ?, and !, which, unless I have been astronomically unlucky, proves that there is a discrepancy.
While "_some_ Unown letters work fine", which, to any normal person, would be acceptable, unfortunately the final Solaceon Ruins room is inaccessible without 26/28 of the unown forms. In addition, the Ruin Maniac Cave changes and gets different possible encounters according to how many found Unown there are, finally becoming "Maniac Tunnel" at 26/28 unown, so further encounters are inaccessible without finding at least 26 unown.
Attempting to go to a "FRIEND" unown room and leaving the Ruins without entering a different room does NOT alter the encounterable wild unown forms appropriately; the other 20/28 are still encounterable and the respective singular unown form is not the only one findable, contrary to what was proposed in the "Additonal Context" of the inital post in this thread.
Because I am high on copium and wasted time, I am going to continue to seek Unown encounters after having visited a "FRIEND" room last in hopes _MAYBE_ the encounterable unown forms are the 20 + 1 forms, through some fluke of game logic I cannot conceive of. If something happens, I will update, but nonetheless, I believe this issue must be solved for the sake of the DPPt games.

**Comment by tom-overton** [comment]
Fixed the issue brought up in the previous two comments with the above-referenced commit. This makes it so that, if Catch Em All mode is enabled, Unown will *not* be randomized in GSC, FRLG, DPPt, and HGSS; they will appear in their vanilla locations. If Catch Em All mode is *disabled*, Unown won't show up in the wild, and the only way to obtain it is for it to appear as a static encounter or for you to evolve into it.

I consider this matter closed. Please don't ask for this to work outside of Catch Em All mode.
