### ISSUE TITLE
[Bug] 

### ISSUE THREAD

**Issue by camrlegere** [Ajarmar/universal-pokemon-randomizer-zx#546]
I downloaded the latest version of the randomizer, unzipped the files, and attempted to open the randomizer by clicking on "Launcher_WINDOWS" and was met with "Invalid maximum heap size: -Xmx4086" "Error: Could not create the virtual machine". Attached is a screenshot of the error message and a screenshot of the files I received from the website.

![Screenshot (51)](https://user-images.githubusercontent.com/114545490/192667116-f3405f83-8253-4b32-8854-b39e807d9669.png)
![Screenshot (52)](https://user-images.githubusercontent.com/114545490/192667141-1f78d9a3-0250-4b11-a111-e68189cc7912.png)

**Comment by tom-overton** [comment]
This is a pretty common problem; it indicates that you have 32-bit Java installed instead of 64-bit Java. You can see our [Java wiki page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) for more info. I believe [this link](https://java.com/en/download/) should let you download 64-bit Java for Windows, but if it doesn't explicitly say "64-bit", then take a look at the Java wiki page for links to other versions of Java.
