### ISSUE TITLE
[Bug] Error Code "Invalid Maximum Heap Size: -Xmx4608M

### ISSUE THREAD

**Issue by Citrinites** [Ajarmar/universal-pokemon-randomizer-zx#550]
**Describe the bug**
I tried launching the windows launcher on windows 10, got the above error code. Unsure what to do.

**To Reproduce**
1. I'm not quite sure why this is happening.

**Expected behavior**
I expected this to not happen.

**Screenshots**
![image](https://user-images.githubusercontent.com/114840774/193434061-7531f6f4-cd50-4b48-948d-44bed5c9718c.png)

**System (please complete the following information):**
 - Operating System: Windows 10
 - Java Version: 8-341
 - Randomizer Version: 4.5.1

**Comment by tom-overton** [comment]
This is a pretty common problem; it indicates that you have 32-bit Java installed instead of 64-bit Java. You can see our [Java wiki page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) for more info. I believe [this link](https://java.com/en/download/) should let you download 64-bit Java for Windows, but if it doesn't explicitly say "64-bit", then take a look at the Java wiki page for links to other versions of Java.
