### ISSUE TITLE
Invalid maximum heap size: -Xmx4608M

### ISSUE THREAD

**Issue by Victor8Caba** [Ajarmar/universal-pokemon-randomizer-zx#557]
Hello, I open the launcher and appears the follow message:

Invalid maximum heap size: -Xmx4608M
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
Press any key to exit...

**Comment by funnypersoniguess** [comment]
https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/550
i had the same issue they answered it here.

**Comment by tom-overton** [comment]
This is a pretty common problem; it indicates that you have 32-bit Java installed instead of 64-bit Java. You can see our [Java wiki page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) for more info. I believe [this link](https://java.com/en/download/) should let you download 64-bit Java for Windows, but if it doesn't explicitly say "64-bit", then take a look at the Java wiki page for links to other versions of Java.
