### ISSUE TITLE
Stuck on Loading for forever.

### ISSUE THREAD

**Issue by DeltaLucario** [Ajarmar/universal-pokemon-randomizer-zx#56]
So, I wanted to Randomize Pokemon Ultra Sun and I know the file works because I've used it in Citra. When I load it in, it sticks on loading. I know that it isn't my internet because I've let it sit for four hours with around 500mbps(?) downloads and 50mbps uploads. I've left it to sit for multiple hours and it never stopped doing the loading. The file is big, but not four hours to open it big. Anyone else know how to fix it or experience this?

**Comment by tom-overton** [comment]
Are you using the latest version of the randomizer (as of the time of this writing, 4.0.2)? If you aren't, can you try again with that version instead?

**Comment by DeltaLucario** [comment]
> Are you using the latest version of the randomizer (as of the time of this writing, 4.0.2)? If you aren't, can you try again with that version instead?

I am using that one, but when I open it it says I need to open using Launcher.Jar so I try to do it but the Launcher.Jar never opens.

**Comment by tom-overton** [comment]
The launcher should create a file called `launcher-log.txt` when you try to start it. Have you tried reading it, and if so, what does it say?

**Comment by tom-overton** [comment]
What you're describing may be because the launcher might not have permission to write files. I tried to update the launcher to more gracefully handle not being able to write its own logs. Can you try the launcher here? Just replace the launcher you currently have with the launcher.jar in here:
[launcher.zip](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5753644/launcher.zip)

**Comment by tom-overton** [comment]
Closing all issues related to the launcher not working because #93 is the home for that sort of thing now. @DeltaLucario go there and try the workarounds listed.
