### ISSUE TITLE
Is there a way to go beyond the 50% level modifier for trainers pokemon, wild encounters etc?

### ISSUE THREAD

**Issue by Pemseles** [Ajarmar/universal-pokemon-randomizer-zx#579]
Now i'm masochistic and would love for the ability to go beyond the 50% level boost offered by the already existing modifier option, but, after looking through the code, i'm not entirely sure how to do this. If i'm not mistaken this probably wouldn't be a setting you'd want to add to the main application, so instead i'd like to be able to do this myself. I'm not entirely sure how to modify the values in the code to go beyond this seemingly hard-coded 50% limit.

**Comment by UTDZac** [comment]
While there doesn't appear to be a way to do this on the application itself using the slider, you can do it using this workaround and using a bit of math.

If you want a **60%** increase, for example, then do this:

1. First revert all settings back to default
2. Change the Foe Pokemon and/or Wild Pokemon % level modifier by **6%**
3. Randomize a single ROM
4. Load this ROM back into the randomizer
5. Now apply all of the settings you want, and add that **50%** level boost

The result of doing a 6% boost and then a 50% boost results in a TotalBoost = `1.06 * 1.5` = `1.59` which is close enough to a 60% increase, thanks to rounding. So instead of doing 6% you can try other numbers to get the desired outcome by repeating steps 1-4 any number of times.

**Comment by Pemseles** [comment]
I don't have the time to test this right now, but I'll report back this weekend or something when I'm gonna start a new playthrough of Pokemon White 2
