### ISSUE TITLE
[Help]  Whenever I try to run launcher_WINDOWS, there is a popup

### ISSUE THREAD

**Issue by howdoirunrandomizer** [Ajarmar/universal-pokemon-randomizer-zx#587]
- Operating System: Windows 11
 - Randomizer Version: 4.5.1

![image_2022-12-24_130429857](https://user-images.githubusercontent.com/121345324/209437494-b1ebc0bf-246f-4499-8ca5-92e6c5d725c6.png)

I have attempted to uninstall and reinstall Java many times, and have extracted all the files done everything in order but it doesnt seem to help at all.

**Comment by tom-overton** [comment]
This is a pretty common problem; it indicates that you have 32-bit Java installed instead of 64-bit Java. You can see our [Java wiki page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java) for more info. I believe [this link](https://java.com/en/download/) should let you download 64-bit Java for Windows, but if it doesn't explicitly say "64-bit", then take a look at the Java wiki page for links to other versions of Java.
