### ISSUE TITLE
[Bug] The don't revert temporary alt formes doesn't work

### ISSUE THREAD

**Issue by Sanderk35** [Ajarmar/universal-pokemon-randomizer-zx#610]
Like the title says the don't revert temporary alt formes doesn't work in gen 7. When I mega evolved and the battle ended diancie was not mega anymore and meloetta wasn't in piroutte form anymore.

**Comment by tom-overton** [comment]
Ah, I think this is a misunderstanding on how this setting works. If you mega evolve *during* a battle, you will revert afterwards. Same for other temporary form changes like Pirouette Form Meloetta.

This setting is designed for when you *catch* these temporary forms, either in the wild or as static Pokemon, and then save and reload your game. Let's say, for example, you run into a wild Mega Diancie. You catch it, then save your game and reload it. Without this setting, that Mega Diancie will be reverted to regular Diancie upon reloading your save. *With* this setting, it will remain Mega Diancie, even after the reload.

What you're describing doesn't exist within the randomizer right now, and even if it *did*, that would be a separate setting. So I'll close this issue out, since there's no bug here. However, I will go and see if we can get some better wording on this setting, since your misunderstanding here is a totally valid one.
