### ISSUE TITLE
Breaks Compatability In DSi enhanced games in Twilight Menu++

### ISSUE THREAD

**Issue by Fackey** [Ajarmar/universal-pokemon-randomizer-zx#63]
Apparently it deletes the DSi binaries of the rom (???) I'm not sure how it works.

**Comment by DatXFire** [comment]
Hi!

I'm not sure what the specific problem you are encountering is, if you could be more specific about the issue it would be helpful. For reference, on the latest version of TwilightMenu++ and nds-bootstrap on my New 3DS, I am able to load and play a randomized Black 2 ROM just fine.

**Comment by Fackey** [comment]
![20201117_204502](https://user-images.githubusercontent.com/28023417/99476354-054ec600-2916-11eb-987f-5f7f1a8a43ae.jpg)

**Comment by DatXFire** [comment]
Thanks! This is probably a result of how the randomizer handles the ROM, but the good news is that you can just set TwilightMenu++ to run games in DS Mode instead of DSi mode, and all you miss out on are features you wouldn't be using in randomizer anyways like video chat on the Xtransceiver, and using different WiFi password encryptions. I'm not sure exactly if fixing this is something that is in the scope of this project, but changing to DS mode should be good enough for now.

**Comment by Fackey** [comment]
I worked! Thanks.

Although now it crashed when I try to look at a Pokemon's summary...

**Comment by DatXFire** [comment]
Weird, I'm able to view the summary of my starter just fine, although the randomizations I picked were fairly simple since it was just to test. The hard thing with issues like this is that the TM++/nds-bootstrap implementation is very fragile, so it's difficult to troubleshoot. I would first suggest making sure you're on the latest versions of TM++ and nds-boostrap if you aren't already. Worst case scenario is that there's a setting of some kind that it just crashes with, but I think it would be very unlikely to be fixed if that were the case. You may try some different settings out or see if the problems persist on the vanilla game for you, it's hard to say.

**Comment by Fackey** [comment]
Thanks! I'm going to close the issue now.
