### ISSUE TITLE
Invalid maximum heap size: -Xmx4096M

### ISSUE THREAD

**Issue by ametzger1027** [Ajarmar/universal-pokemon-randomizer-zx#66]
I don't understand what a heap size is. I believe I have downloaded the latest java installation for 64x windows. I was wondering if you guys could help me trouble shoot on how to fix this. 
This is the exact error message i got: 
Invalid maximum heap size: -Xmx4096M
The specified size exceeds the maximum representable size.
Error: Could not create the Java Virtual Machine.
Error: A fatal exception has occurred. Program will exit.
I have gotten all of my files ready to use for the randomizer, I just cant open it. Any help would be greatly appreciated.

**Comment by ametzger1027** [comment]
Update, I went to the java control panel and it says Java 32-bit, but I have already downloaded the java 64 bit an I have a 64-bit processor and operating system.

**Comment by tom-overton** [comment]
It doesn't matter what processor and operating system you're using; if you have 32-bit Java installed, the randomizer simply won't work with 3DS games. Try uninstalling your 32-bit version and installing the 64-bit version instead. I believe this is the correct link for windows: https://javadl.oracle.com/webapps/download/AutoDL?BundleId=243737_61ae65e088624f5aaa0b1d2d801acb16

As for what the heap size is, it's simply a measure of how much memory the randomizer is capable of using. Randomization of the 3DS games takes more memory because they're much larger games. Note that if all you want to do is randomize the GB, GBA, and/or DS games, you can simply run the PokeRandoZX.jar using 32-bit Java and it will work just fine, since they don't need the expanded heap size.

**Comment by ametzger1027** [comment]
Thank you so much. It is working now!!!!
