### ISSUE TITLE
Problem(?) with Nincada When Base Stats/Abilities Are Randomized and They Follow Randomized Evolutions

### ISSUE THREAD

**Issue by wwtepicfail** [Ajarmar/universal-pokemon-randomizer-zx#7]
I was doing a _Pokémon Black_ randomizer using v3.1.0, the latest release as of this post. I found a wild Nincada at Level 4 on Route 1 that seemed promising; it was at least better than my starter, a Gastly.

` 92|Gastly       |GHOST/POISON     |  93|  44|  35|  54|  48|  36|Drizzle     |--          |Ice Body    |Safari Ball (common), Helix Fossil (rare)`
` 290|Nincada      |BUG/GROUND       |  23|  90|  30|  58|  45|  21|Quick Feet  |--          |Rattled     |`

I continued to use this Nincada. I was somewhat excited to see what kind of evolution it could be, as there was a chance it could have been a three stage evolution chain. When I leveled it up to Level 20, it evolved to a Claydol - this is something I did not mind seeing. However, when I checked its stats and ability, they changed completely. It ended up way worse than I thought.

` 344|Claydol      |GROUND/PSYCHIC   | 153|  56|  88|  35|  21| 148|Motor Drive |Insomnia    |Scrappy     |`

I intentionally left an open slot in my party to see what Shedinja would have been. It was still a Shedinja, despite what the log had to say:

` Nincada         -> Claydol and Barboach`

Barboach did not share any base stats, which is completely reasonable:

` 39|Barboach     |WATER/GROUND     |  84|  43|  32|  16|  61|  53|Storm Drain |Forecast    |Anger Point |Black Belt (common), Bug Gem (rare)`

The Shedinja does not share anything; also reasonable. Keep in mind that I previously caught a Shedinja on Route 1 as well:

` 292|Shedinja     |BUG/GHOST        |   1|  54|  12|  74|  58|  36|Wonder Guard|--          |Wonder Guard|Dread Plate (rare)`

I have no idea if what occurred is intentional or what. I know that certain evolutions cause base stats and abilities to change completely, like with Eevee or Slowpoke. Although my memory is foggy, I do not remember seeing Nincada having its ability or base stats to change when evolving to its Ninjask replacement.

**Comment by tom-overton** [comment]
Your point about Eevee and Slowpoke is very related to this, since this issue is caused by the same thing that causes their evolutions. The settings that enable stats and abilities to follow evolutions _intentionally_ ignore split evolutions because there's no real way to make it work with them. If we arbitrarily selected one of the split evolutions to carry forward the stats and abilities, then the evolutions we _didn't_ select would feel awkward; it would be as if there was only one "correct" choice. Meanwhile, if we decided that _all_ of the split evolutions should carry forward the stats and abilities, then they wouldn't really feel unique at all.

The reason why Claydol had a completely different ability and completely different stats compared to Nincada is because in Gens 3-5, Nincada is internally a split evolution. However, it is not _logically_ a split evolution; it is a single evolution that just so happens to create a brand new Pokemon in your party if the conditions are right. So there's definitely something we can do to make the Ninjask evolution a little less unpredictable. I'll take a look and see if there's some way to fix this before the next release.

As for why Shedinja wasn't randomized, this is something I'm a lot less certain about. In the Gen 3 games, the game reads the evolution data to decide the species for the Shedinja, so our randomization is honored by the game; if you were instead playing Emerald, you _would_ have gotten a Barboach instead of a Shedinja. However, by the time Gen 5 came around, they clearly stopped caring about what was actually in the evolution data, so Shedinja gets created via some unknown mechanism. This is a lot harder to promise a fix for simply because I don't know what causes the problem in the first place. Note that in the 3DS games, Nincada is no longer a split evolution internally, and evolving a Nincada with randomized evolutions enabled doesn't even create a Shedinja at all. So this evolution is definitely a weird, hardcoded case in the majority of Pokemon games.

**Comment by wwtepicfail** [comment]
I see now. Thanks, Tom.
