### ISSUE TITLE
Can't figure out how to run the application/launcher

### ISSUE THREAD

**Issue by Zahikusa** [Ajarmar/universal-pokemon-randomizer-zx#71]
Hey, I just cloned your project and am trying to run the launcher at ``...\universal-pokemon-randomizer-zx\src\launcher.java``.
In the Readme you metion that one has to:
> Just double click launcher.jar and it will start the randomizer program.

My problem there: I don't have any ``.jar`` file lying around. And when I try to run the ``launcher.java`` file from command line, it just says:
> Error: Unable to access jarfile ./PokeRandoZX.jar

![image](https://user-images.githubusercontent.com/32354342/100519997-bc133780-319b-11eb-9c85-e0b8e68dcd56.png)

I think I'm just to stupid to figure out how to get this to work.. Am I maybe missing any preconditions? My Java version is 11, I set my Java environment variable and I've already done quite some googling to try and troubleshoot this..

Would be extremely happy for any help! :)

**Comment by tom-overton** [comment]
I'll definitely try to help set up your development environment, but first I want to say: if your goal is *just* to run the randomizer and not to read or edit the code, I would highly recommend you [download a pre-built release from our releases page instead](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/releases).

As for your development environment, you're not missing any prerequisites, so don't worry. The launcher is a *very* simple program; it just runs the following command:
```
java -Xmx4096M -jar ./PokeRandoZX.jar please-use-the-launcher
```
The launcher has two goals:
1. Make sure that the user has enough memory to randomize the 3DS games
2. Make sure that the user used the launcher

It is actually possible to launch the randomizer *without* using the launcher, but we normally prevent you from randomizing the 3DS games if you do that. The "please-use-the-launcher" parameter is what we use to determine that you used the launcher.

Your problem is that you don't have PokeRandoZX.jar in the same folder as the launcher. If you want it to work, you'll need to build it yourself from the rest of the randomizer codebase. However, we recommend that you just skip using the launcher entirely when developing. IntelliJ has the ability to specify command-line arguments in the Run/Debug Configurations window, and you can configure it with the "please-use-the-launcher" parameter like so:
![image](https://user-images.githubusercontent.com/12245827/100523108-a46b8d00-3162-11eb-9f9e-1be98da2d870.png)

If your configuration matches mine, you should be able to run the randomizer with all the bells and whistles enabled without needing to use the launcher at all.

**Comment by Zahikusa** [comment]
Thank you alot for this indepth explanation! I'm sure this could be helpful for some other passers-by in the future aswell.

My intention was actually to just run the randomizer - I overlooked the release-page.
But now I also have the means to potentially tinker around with the codebase, that's cool :)
