### ISSUE TITLE
some features are missing when i put french rom in the randomizer

### ISSUE THREAD

**Issue by Baat01** [Ajarmar/universal-pokemon-randomizer-zx#73]
particulary the ones with the statics pokemon from pokemeon hearthgold and soulsilver
also the one for fastest text but it's not a huge miss 
here is the us version
![image](https://user-images.githubusercontent.com/75745165/101984149-d8c16c00-3c7f-11eb-9540-4020ebd0a3b2.png)
and here is the french version
![image](https://user-images.githubusercontent.com/75745165/101984175-03132980-3c80-11eb-82f6-44f6b67a9b04.png)
I've verified and it is also the case for soulsilver

I don't know if there is the option in pearl,diamond, and platinum, but it is the same case for those game in french
![image](https://user-images.githubusercontent.com/75745165/101984260-7452dc80-3c80-11eb-9ef6-20e79a4bedf9.png)
I've tried for other generation, and the option is here for all the game I've test in french version(black,white, white 2,black 2,x,y,rubis,saphire,emerald,fire red and leaf green)
it may just be a known issue that I'm unaware off

**Comment by Baat01** [comment]
also it's not a bug or anything but in hearthgold soulsilver the 5 kimono girl have 6 pokemon when you put important and boss trainer + 5 pokemon while some of the admin of new team rocket doesn't have more pokemon (archer and ariana)
I found that weird, and more difficult than the elite 4 giving that we can't heal after battle,especially during nuzlocke.
that's just a personnal opinion, but i think it would be better to put them in regular trainer or just one of them in special trainer, and put archer and ariana in important trainer
but that's just the opinion of a salty nuzlocker who wipe and lost everything to them

**Comment by tom-overton** [comment]
Commits 73beb24da803a31e0056ace76429edbdff4d07db, 3d050b4c15974935b1eb87e6cbdd556b7f050e2a, and d92b716e952f76f75a784656f20ad8350fa0db51 add static Pokemon support to almost every non-US version of all the Gen 4 games. Once v4.1.0 releases, you'll be able to randomize static Pokemon in the French versions of Diamond, Pearl, Platinum, HeartGold, and SoulSilver.

As for the fastest text tweak, that's a far more "invasive" change to the game. It would require a lot of testing for me to feel comfortable making that change, so I decided to shelve it for now. Not saying we'll *never* add support for fastest text for the non-US games, just that it requires a lot of testing.

And lastly, RE: important trainers. Funnily enough, the Kimono Girls weren't considered "Important" before v4.0.2, but we changed them in response to some feedback. Guess you can't please everyone. In the DS games, being an "Important" trainer serves a dual purpose in marking the trainer as "okay" for double battle, which is why Archer and Ariana in the Radio Tower aren't considered "Important"; if you make them a double battle, they can crash the game. I don't see much of a reason to change the Kimono Girls back to un-important, but I'll make a wiki page at some point documenting who the important and boss trainers are because it's not really fair to players to get surprised by trainers who suddenly have a ton of Pokemon out of nowhere.

**Comment by Baat01** [comment]
RE : important trainer : well that's very funny, I wasn't aware of that update, guess you can't please everyone too. a wiki page to document important/boss trainer would be great, and I think I could have just put less pokemon for important trainer (plus the wiki page will help me doing this that will be awesome if you can do this)
knowing that important trainer have a dual purpose also explain everything, I imagine that more trainer crash the game in double battle,wich is why (i think) you restricted it to important and boss trainer
