### ISSUE TITLE
Launcher Will Not Open

### ISSUE THREAD

**Issue by MAY045** [Ajarmar/universal-pokemon-randomizer-zx#78]
Ive got the 1.8 version of Java with 64 bits but no matter what I try the launcher will not open. Also the launcher log has not appeard in my folder if that helps. The pictures bellow show my java version and the aftermath of trying to open the launcher.
I am working on macOS v11.1

<img width="652" alt="Screenshot 2020-12-20 at 17 12 46" src="https://user-images.githubusercontent.com/76403161/102719611-d34ecc00-42e6-11eb-83bb-c29f1fe06c21.png">
<img width="248" alt="Screenshot 2020-12-20 at 17 12 56" src="https://user-images.githubusercontent.com/76403161/102719616-d8138000-42e6-11eb-8238-ea7fb6a4e7d5.png">
<img width="452" alt="Screenshot 2020-12-20 at 17 13 39" src="https://user-images.githubusercontent.com/76403161/102719619-db0e7080-42e6-11eb-828c-81f0e417d2f0.png">

**Comment by tom-overton** [comment]
Hmmm, your Java version looks good. Can you try running it via the command-line like so?
```
java -jar ./launcher.jar
```

**Comment by jamiejigsaw** [comment]
I have a similar issue i have the latest 64bit java, yet when i double click the launcher, nothing loads, if i use the pokerandozx it loads the program but can't be used because i wasn't used from the launcher?

**Comment by xembel** [comment]
@jamiejigsaw do you still have the issue? If so, does the launcher create a filed named "launcher-log.txt" when you try to launch it?

**Comment by jamiejigsaw** [comment]
Hi,

Yes still having the issue.
It doesn’t create a new file it just has the little blue loading circle next to the mouse and then nothing happens.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by xembel** [comment]
Do you have an antivirus running? In my case the launcher was unable to create launcher-log.txt, because the antivirus was blocking it, I was getting this message. Had to give the launcher.jar permission to write. 
![image](https://user-images.githubusercontent.com/76751946/103315249-55e13500-4a25-11eb-956a-323d739f6491.png)

**Comment by jamiejigsaw** [comment]
YES! That made it work!, thank you so much!

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tom-overton** [comment]
Fascinating! I had no idea that antivirus might prevent the launcher from functioning. Thanks for letting me know; I'll see if there's a way to get around that.

**Comment by tom-overton** [comment]
What you're describing may be because the launcher might not have permission to write files. I tried to update the launcher to more gracefully handle not being able to write its own logs. Can you try the launcher here? Just replace the launcher you currently have with the launcher.jar in here:
[launcher.zip](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5753663/launcher.zip)

**Comment by Roney23** [comment]
> I have a similar issue i have the latest 64bit java, yet when i double click the launcher, nothing loads, if i use the pokerandozx it loads the program but can't be used because i wasn't used from the launcher?

Same problem here except I completely turned off my antivirus and still nothing. The blue loading bar also only appears for about 0.5s.

**Comment by tom-overton** [comment]
Closing all issues related to the launcher not working because #93 is the home for that sort of thing now. @MAY045 and @Roney23  go there and try the workarounds listed.
