### ISSUE TITLE
Alternate forms in Gen 5 and 6

### ISSUE THREAD

**Issue by NeptuneCykes** [Ajarmar/universal-pokemon-randomizer-zx#80]
While playing through gen 5 we've seen that alternate forms don't get full compatibility on TMs/HMs even when Full Compatibility is checked while creating the new ROM.

Also we don't know if this is also a thing in gen 5, but we have encountered that Giratina Origin form and Shaymin Sky Form do not maintain their forms after being caught, instead, they revert to their normal form.

**Comment by tom-overton** [comment]
Can you upload a log of the TM/HM thing for either Gen 5 or Gen 6? In my own testing, this works fine:
![gen5](https://user-images.githubusercontent.com/12245827/103479410-47c34980-4d82-11eb-99b9-de458db1f025.png)
![gen6](https://user-images.githubusercontent.com/12245827/103479412-4a25a380-4d82-11eb-8918-5d94eabf21a6.png)

**Comment by tom-overton** [comment]
I can't repro your other issue in Gen 5 either. I caught this Giratina-O and he remained in his Origin Forme even after being captured. Can you please provide a log of the seed where you're seeing this?
![giratina](https://user-images.githubusercontent.com/12245827/103479630-e13f2b00-4d83-11eb-8aee-74e65834bbc2.png)

**Comment by NeptuneCykes** [comment]
From my experience, Giratina-O stays the same after catching but the moment you equip (unequip if it comes with an item), it reverts back to its normal form, my guess is that game checks if its holding the Griseous Orb or not and if not, then reverts back.

As you can see in this image, you cannot teach Surf to Meloetta-P, but I was able to teach Strength, and in the next image, it cannot learn either Brick Break, which is a move that should be able to learn normally, so I don't think the issue is typing based of the move, rather than just random compatibility.

![e5622141dc97bcc65829870fca014dd2](https://user-images.githubusercontent.com/72678770/103691361-55e9b380-4f96-11eb-8b02-d1c706983c1a.png)

![0dc31a1e32ca6731fcb9e8f0d9b7c309](https://user-images.githubusercontent.com/72678770/103691734-f7710500-4f96-11eb-80be-481687db3742.png)

The log where those captures where taken from is this one
[MeloettaP tm non compatible.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5772255/MeloettaP.tm.non.compatible.log)

**Comment by tom-overton** [comment]
Thanks for the log. It made me realize that you were using BW2 instead of BW1. The bug you found with Meloetta is specific to BW2; if a Pokemon is an alt forme, its TM/HM compatibility (and its move tutor compatibility too) is not written correctly. The reason this bug happened is because the Pokestar Studios exclusive enemies appear in the list of Pokemon *before* alt formes, and we were accounting for this in every case *except* for TM/HM and move tutor compatibility. This has been fixed and will be included in the next release.

As for Giratina-O and Shaymin-S, we decided to ban these two formes from appearing in the wild. We try to avoid scenarios where a Pokemon can change formes after you catch it without offering you a way to return it to how it was before, and these two formes in particular have too many headaches associated with them to support them properly. You can still access these formes by using their associated transformation item, though. Thanks for bringing to our attention that they were a little messed up.
