### ISSUE TITLE
Launcher won't open at all

### ISSUE THREAD

**Issue by thederpycorgi** [Ajarmar/universal-pokemon-randomizer-zx#82]
I am trying to open the launcher but every time I go to open it, it does the spinning circle as if it is loading but then stops and nothing happens. If I try opening PokeRandoZX, that opens perfectly fine but then I am unable to randomise 3DS games which is what I am trying to do. I have the most up to date Java in 64 bit and everything else works fine, but for some reason the actual Launcher never opens. It is saved as an Executable Jar File in case that is important.
 
Thanks

**Comment by jamiejigsaw** [comment]
This is the exact same issue i am having

**Comment by tom-overton** [comment]
What you're describing may be because the launcher might not have permission to write files. I tried to update the launcher to more gracefully handle not being able to write its own logs. Can you try the launcher here? Just replace the launcher you currently have with the launcher.jar in here:
[launcher.zip](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5753665/launcher.zip)

**Comment by jamiejigsaw** [comment]
I tried the launcher with the anti-virus turned back on and it had the same issue as before.

Sent from Mail<https://go.microsoft.com/fwlink/?LinkId=550986> for Windows 10

**Comment by tom-overton** [comment]
Huh, oh well. What the launcher does (launch another java process without really doing anything else) probably looks reasonably suspicious to an antivirus program so I'm not surprised it can cause issues. At least this is now another potential way of troubleshooting issues.

**Comment by tom-overton** [comment]
Closing all issues related to the launcher not working because #93 is the home for that sort of thing now. @thederpycorgi go there and try the workarounds listed.
