### ISSUE TITLE
Gen 7 - when not using any "Allow Alternate Formes" options, alt formes still appear for trainers

### ISSUE THREAD

**Issue by wlyles** [Ajarmar/universal-pokemon-randomizer-zx#84]
As far as I can tell based on the log files after a few runs, when you haven't checked any of the various "Allow Alternate Formes" checkboxes, alternate formes will still appear but only as trainer Pokemon. 

This was tested on Ultra Moon with version 4.0.2 of the randomizer.

As an aside, I discovered this when trying to find a way to have "permanent alternate formes" (such as Alolan formes) but not "temporary alternate formes" (such as mega evolutions). Is it possible to include these "permanent alternate formes" but not the "temporary" ones when randomizing? I'd prefer to be able to encounter regional variants and the like without also encountering things such as permanent mega evolutions.

**Comment by tom-overton** [comment]
Can you provide a log demonstrating this? I've done a couple of runs myself and everything looks fine to me; I'm not sure what it is that's out of place.

**Comment by wlyles** [comment]
Attached is some sample output. I can't attach the .rqns file for my settings, so I'll just attach a few relevant screenshots instead. I can add more if needed.

A search for "-A" to pick up alolan formes shows 75 hits. 61 of them are on lines 60-690, which is where trainer information is logged. The other 11 hits are for fixing an impossible evolution for Graveler-A and the original pokemon being replaced for statics and totems. We also get 29 hits in that trainer section when searching for "Rotom-" to find alternate Rotom formes, as well as 32 hits for "-Mega" (two of which apparently also show up to replace totem pokemon, which hasn't happened in previous attempts - seems the same issue is affecting totem pokemon). Not a single alternate form, alolan or otherwise, appears in the encounter tables.

[solo.cxi.log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5736737/solo.cxi.log)
![foe-pkmn](https://user-images.githubusercontent.com/11062984/103030033-d24cb300-450f-11eb-90ee-c030904ce5e2.png)
![wild-pkmn](https://user-images.githubusercontent.com/11062984/103030039-d547a380-450f-11eb-9a14-7d0d70f2a35e.png)

**Comment by tom-overton** [comment]
The reason why I wasn't seeing anything is that I wasn't using Type Themed Trainers, which is the only place in which the bug appeared. It turns out that in this specific circumstance, we were using the wrong list of Pokemon to pick replacements. I fixed that in the above commit, and it will be included in the next release of the randomizer.

As for some of the other things you mentioned:
- Totem Pokemon had alt formes because you turned on the "Allow Alternate Forme" option for them. In my own testing, I don't see any issue with how this setting works; when it's on, it includes alt formes, and when it's off, it doesn't.
- There's no setting that would let you have Alolan forms without all other alternate formes. Alternate formes are an "all or nothing" thing at the moment. It should be noted that even with the setting *off*, you will still see cosmetic forms like the various Unown letters or both of the East/West Sea Shellos/Gastrodon.
