### ISSUE TITLE
Some of the Randomizations don't work in ultra sun

### ISSUE THREAD

**Issue by aqualad33** [Ajarmar/universal-pokemon-randomizer-zx#87]
the randomization will run successfully on an ultra sun .3ds file, the logs will be properly generated however
1. in game the shops will not be randomized (will still sell the same items as the original copy).
2. TMs will be shuffled however the TMs will still be the same moves (ex: TM99 is Nature's Madness in the gameName.cxi.log file however it is dazzling gleam in game).
3. Move tutors are not randomized (similar to tms, verified this issue when comparing against the gameName.cxi.log file)

using ultra sun .3ds file version 1.2, generating .cxi file from Universal Pokemon Randomizer ZX v4.0.2

Edit: it appears that TMS randomize properly when exporting and applying a layer file instead of generating a cxi.

**Comment by tom-overton** [comment]
If you're playing version 1.2, you'll need to load the 1.2 game update CIA into the randomizer in order for everything to work. What's happening is that your update is overwriting the randomized game files, causing the randomization to revert. The reason why outputting as a layeredFS file is making it work is because the priority for loading any given file is layeredFS > game update > base game.

We go into detail on our wiki about [3DS game updates](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#3ds-game-updates), but the short answer is you need to do one of two things to make this work.
1. Load the 1.2 game update into the randomizer (the option is under the Settings button)
2. Delete the 1.2 game update from your 3DS/Citra. We have [a guide on the wiki about this](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Randomizing-the-3DS-games#managing-game-updates)

I should note that if you opt for loading the game update into the randomizer, you can't output as CXI; this is a technical limitation with how 3DS game updates work and will never be changed.

**Comment by aqualad33** [comment]
ah, makes sense. In that case I'll just stick to using the LayeredFS file. Two Questions though.
1. If the priority works that way shouldn't I be fine just loading the .3ds file into the randomizer if I output it as LayeredFS? If not what other things could work improperly?
2. If I have to load the game update separate from the .3ds file how do I find it? Is it the thing that the guide mentions is downloadable from nintendo's website?

**Comment by tom-overton** [comment]
1. Yes, when you output as LayeredFS, the idea is that you load the original, unrandomized .3ds in Citra. The randomized files in the layeredFS will override the original files and the randomization will work.
2. If you installed the 1.2 update in Citra, you installed it by using the update CIA. Assuming you still have the update CIA, you can just load the same file in the randomizer. If you *don't* have the update CIA anymore, then the only way to legally acquire it is to download it on your 3DS and dump it, though the download is free.

**Comment by aqualad33** [comment]
Gotcha, I just made a copy of my 3ds file and overwrote that. Thanks I'll close the issue.
