### ISSUE TITLE
[Bug] Pokémon X/Y Swap Mega Evolvables Quirk

### ISSUE THREAD

**Issue by sora10pls** [Ajarmar/universal-pokemon-randomizer-zx#9]
[As noted in an issue in pk3DS over 4 years ago](https://github.com/kwsch/pk3DS/issues/26), the battle with Successor Korrina atop the Tower of Mastery requires the player to Mega Evolve their Pokémon in order to progress the story.

Currently, if "Swap Mega Evolvables" is not checked when randomizing, this can lead to a softlock.
Attached is a view of the edited data in pk3DS after randomizing with this fork of UPR.
![image](https://user-images.githubusercontent.com/17801814/94344338-95465280-ffec-11ea-8aad-ef9b1411dc88.png)
Because Elgyem can't Mega Evolve or make use of the Lucarionite, Korrina will insist the player Mega Evolves. Since they're unable to, this leads to a loop of going into battle, not being able to Mega Evolve, losing, and repeating this process until you reset your game.

pk3DS handles this quirk by doing one of the following:
Is "Swap Mega Evolvables" checked?
* If yes, replace with another Mega Evolvable species with its respective Mega Stone.
* If no, ***do not modify the encounter.*** Keep it as Lucario holding Lucarionite.

On an unrelated note to this issue, thanks for your work on the project. It's pretty astounding that this is possible, and you guys even managed to work out field item randomization, scripted encounter randomization (e.g. bush/ceiling swarms) and even in-game trades for Gen 6, none of which pk3DS ever touched! Congrats on the recent release :)

**Comment by Ajarmar** [comment]
Interesting, I wasn't aware of this. In the context of this randomizer I think it makes the most sense to just always restrict the randomization of the Lucario to the subset of Pokemon that won't softlock the game (because presumably the user will want Lucario to be randomized just like any other Static Pokemon, even if it's from a limited pool of Pokemon), so that's how I'll solve it here.

Thanks for pointing this out (and for the kind words). Incidentally, do you know if it causes any issues if Korrina cannot Mega Evolve her own Pokemon?

**Comment by sora10pls** [comment]
I haven't necessarily tested removing Korrina's Mega Lucario from the battle, though I doubt the game cares about what she does. In the past I've done a run where she had 6 Pokémon and never got to Mega Evolve hers (slot 6), and the story advanced fine.

**Comment by Ajarmar** [comment]
Fixed in 906b131031453634d70138a77ad4deae3599ef52, will be included in next release
