### ISSUE TITLE
"Launcher does not work" Master Issue

### ISSUE THREAD

**Issue by tom-overton** [Ajarmar/universal-pokemon-randomizer-zx#93]
We've seen a lot of "Launcher does not work" issues, so instead of having them scattered across multiple issues, I'm collecting them here.

#### When I double-click Launcher.jar, nothing happens

First, try disabling your antivirus if you're running one.

#### I tried disabling my antivirus, but Launcher.jar still does nothing

Try moving the randomizer folder to a different location on your computer. If you're on Windows, it's picky as to where unsigned applications are allowed to write data, so moving it out of places like your User folder may make it work. Other OSes probably don't work similarly, but it can't hurt to try.

#### I still can't get Launcher.jar to work even after moving it around

If you have python installed, try using the launcher.py in this .zip file. Extract the .zip and move launcher.py to the same directory as PokeRandoZX.jar. **This launcher is not officially supported**, and should only be used if the previous two troubleshooting steps failed to work:
[launcher.zip](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5763093/launcher.zip)

#### I can't get launcher.py to work, or I just don't have python installed

Open a command prompt, navigate to the same directory as PokeRandoZX.jar, and run "java -Xmx4096M -jar ./PokeRandoZX.jar please-use-the-launcher". This is literally all the launcher actually does.

#### Even when I use the command prompt, nothing happens

Then your problem isn't with the launcher. Make sure you've read our [wiki page on Java requirements](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java).

If you're responding to this issue, let me know what (if anything) worked for you. We want to make the launcher work for as many people as possible, so we need to know what problems people are encountering and what workarounds fix it.

**Comment by Benjamin-318** [comment]
I'm running into a problem. Once I download the file and they open up in Winrar I extract them to my desktop but I only get folders or the launcher file that redirects me to Winrar with the exact folder. I can't open up launcher with Java. I downloaded the latest version for Java and Winrar. Do you know what I do wrong or how I can open the launcher ? 

I read through this issue but my problem doesn't seem to be in there.

**Comment by tom-overton** [comment]
Just from your text description, I really don't know what's going on. Can you provide a screenshot of the extracted folder?

**Comment by Benjamin-318** [comment]
I found the solution for the problem. The icon of the downloaded program was that of Winrar. Even when the files where extracted. Manually opening them with Java didn’t seem to help. So I tried “searching for another app”. Then select Java as opening app but instead of just pressing OK I now checked “Always use this app when opening … files”. After that my icon changed from Winrar to Java and the randomizer is now able to launch.

Maybe this info is useful for someone who has the same problem.

Keep up the good work!

Van: Tom Overton<mailto:notifications@github.com>
Verzonden: zondag 7 februari 2021 12:04
Aan: Ajarmar/universal-pokemon-randomizer-zx<mailto:universal-pokemon-randomizer-zx@noreply.github.com>
CC: Benjamin-318<mailto:benjamin-318@hotmail.com>; Comment<mailto:comment@noreply.github.com>
Onderwerp: Re: [Ajarmar/universal-pokemon-randomizer-zx] "Launcher does not work" Master Issue (#93)


Just from your text description, I really don't know what's going on. Can you provide a screenshot of the extracted folder?

**Comment by Crajabzul** [comment]
I've gone through most, if not all of the "launcher issue" threads and not found a solution to my personal issue. When I try running "launcher.jar" or "PokeRandoZX.jar", a brief command prompt pops up, then instantly closes, giving me no errors. I've made sure I have the proper version of java, as well as changing it so that the program that it should be opening with is the 64bit java.exe.

**Comment by Ajarmar** [comment]
@DragonEmpyrean @Crajabzul For both of you: try opening a command prompt in the folder with the randomizer/launcher (on Windows, you can do this by holding Shift and right-clicking in the folder, then selecting "Open command window here"). Then type in `java -jar launcher.jar` and press Enter. Do you get an error message in the command prompt, and if so, what does it say?

**Comment by Crajabzul** [comment]
Kinda nuts I had to launch it through PowerShell, but it worked. Thanks for the help @Ajarmar

**Comment by DragonEmpyrean** [comment]
@Ajarmar i did get the program to open but now the patch for randomizer won’t work lol

**Comment by Beastly181** [comment]
@Ajarmar Hey so i used powershell and used that command in the folder. It said i dont have access to launcher,jar. Any help?

**Comment by Beastly181** [comment]
@Ajarmar solved the problem

**Comment by AlphaReps** [comment]
> @DragonEmpyrean @Crajabzul For both of you: try opening a command prompt in the folder with the randomizer/launcher (on Windows, you can do this by holding Shift and right-clicking in the folder, then selecting "Open command window here"). Then type in `java -jar launcher.jar` and press Enter. Do you get an error message in the command prompt, and if so, what does it say?

omg I love you so much I've been trying for so long if I knew you in real life you'd get a big high five

**Comment by Ajarmar** [comment]
Closing this since we have switched to a new launcher. (The equivalent issue for the new launcher is [here.](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/issues/221))

**Comment by patmad525** [comment]
Please help me! Everytime I try to open the launcher nothing happens. And when I try to use the PokeRandoZX.jar I can't randomize 3ds games. What can I do?

**Comment by Chozen2516** [comment]
> Please help me! Everytime I try to open the launcher nothing happens. And when I try to use the PokeRandoZX.jar I can't randomize 3ds games. What can I do?

the same is happening to me too

**Comment by JoaxGG** [comment]
i did EVERYTHING it said and nothing worked launcher.jar is still not working
and the pokerandozx.jar doesnt allow 3ds randomization either. any other fix? everyother source just points to this
