### ISSUE TITLE
Shedninja error

### ISSUE THREAD

**Issue by dantelewandoski** [Ajarmar/universal-pokemon-randomizer-zx#96]
When I was evolving a Nincada into a ninjask and shedninja(having a pokeball) on pokemon XY it just kept breaking and told me to save dump sorry for not having a picture to show the exact error but it happened twice and it only happened with this specific evolution.

**Comment by tom-overton** [comment]
If you have the log file for this randomization, can you please post it? If you *don't* have the log file, can you at least tell me if you randomized evolutions or not?

**Comment by dantelewandoski** [comment]
> If you have the log file for this randomization, can you please post it? If you _don't_ have the log file, can you at least tell me if you randomized evolutions or not?

https://docs.google.com/document/d/1bbDlWMX8dGu-rDTgu06BC4L4IxEw8XIS_22GyUIp0aU/edit?usp=sharing


https://drive.google.com/file/d/1Gt3VxwlTJYgcREUtMUx5t_FsNuSlF1HD/view?usp=sharing

I personally never use Random evos I am just doing an X CEA and this happened added my settings I used as well

**Comment by tom-overton** [comment]
Thanks for the log and settings! I'll take a look.

**Comment by dantelewandoski** [comment]
> Thanks for the log and settings! I'll take a look.

thank you was just werid that it was fine when I evolved into Ninjask but would crash If i evolved into both Ninjask and Shedninja

**Comment by tom-overton** [comment]
Thanks for the bug report! I didn't realize it until investigating this, but a real 3DS handles certain instructions *slightly* differently than Citra, a 3DS emulator we often use for testing. In this specific case, that difference is precisely what causes this crash. If you're wondering why it only happens when you make a Shedinja, it's because we rewrite parts of that code so that randomized evolutions work. Unfortunately, that rewrite used an instruction that crashes on a real 3DS but works fine on Citra. I have fixed the issue, and it will be included in the next release of the randomizer. Until then, though, avoid creating a Shedinja to prevent a crash. Sorry about that!
