### ISSUE TITLE
Loads forever when trying to open ROM

### ISSUE THREAD

**Issue by afterbvrner9** [Ajarmar/universal-pokemon-randomizer-zx#98]
I've updated to the latest version of Java, I've installed the launcher.jar you posted from the #93 issue, restarted my computer, and yet the issue is still not resolved. I think I'm missing something, but I do not know what. The ROM in question is a .3ds file, so maybe that's the issue? I would love to hear your feedback.

Thank you for reading and I hope to hear from you soon.

**Comment by tom-overton** [comment]
Let's try to remove the launcher from the equation entirely. I'm assuming you're on Windows since you didn't specify; feel free to correct me if I'm wrong. In the randomizer folder, hold Shift on your keyboard and right click on any empty space to bring up this menu:

![image](https://user-images.githubusercontent.com/12245827/104236948-2ad6e800-540c-11eb-82b3-6c3b1976491e.png)

Select "Open PowerShell window here" (depending on your version of Windows, this may instead be "Open Command Prompt here". This is totally fine, just click that instead). In the window that opens up, paste the following command:

```
java -Xmx4096M -jar PokeRandoZX.jar please-use-the-launcher
````

This should start the randomizer. Now try loading your ROM again. If it still doesn't work, then the launcher isn't the problem at all; let me know what happens.

**Comment by afterbvrner9** [comment]
Thank you for your response, however, I was still getting an infinite load from opening the rom. I pasted the command into the Windows Powershell, but as soon as I did and pressed enter I saw it said: 

Picked up _JAVA_OPTIONS: -Xmx512m

I don't know how I am getting this error when I have updated the Java Runtime Environment Settings to -XMX4096m.
Is there a solution to this?

**Comment by tom-overton** [comment]
Ahhhh, this classic issue. We've seen it before, and we have something on our wiki about how to fix it: https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/About-Java#when-i-try-to-randomize-the-game-it-fails-and-i-see-something-like-picked-up-_java_options--xmx512m-in-launcher-logtxt

Somewhere in your environment variables, you are limiting Java to 512 MB of memory; this is causing you to run out of memory when trying to open a 3DS game image. You'll need to track down that variable and delete it. The instructions on that wiki page will guide you through it; let me know if you have questions.

**Comment by afterbvrner9** [comment]
It worked! You were awesome, thank you for the help I really appreciate it! Issue was fully resolved.

**Comment by tom-overton** [comment]
You're welcome! I'm glad it worked!
