### ISSUE TITLE
BST following Mega Evolution causes wrong distribution for regular Evolution

### ISSUE THREAD

**Issue by Salzkorn** [Ajarmar/universal-pokemon-randomizer-zx#99]
[Example log](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/files/5796398/moon.log)

Of note is the Cyndaquil -> Pignite -> Lopunny-Mega evolution line:
```
NAME            |  HP| ATK| DEF|SATK|SDEF| SPD
Cyndaquil       |  71|  11|  48|  71|  30|  78
Pignite         |  96|  15|  65|  96|  41| 106
Lopunny-Mega    | 100|  44|  71|  28| 167| 171
Lopunny         |  83|  36|  59|  23| 138| 141
```
Notice in particular the SATK and SDEF changes.

The settings are that BSTs should follow both regular and Mega Evolutions, so I would expect all four of the above to have the same distribution. Instead, Lopunny-Mega takes after regular Lopunny, which breaks the rule for regular Evolutions.
I could see this being a known issue, but couldn't find documentation for it anywhere, so felt it safer to report.

I'll also note that, while I haven't tested this, the same behavior might occur with Abilities following both kinds of Evolutions.

**Comment by tom-overton** [comment]
This actually is documented in its [own section on the Important Information page](https://github.com/Ajarmar/universal-pokemon-randomizer-zx/wiki/Important-Information#quirks-involving-the-follow-mega-evolutions-settings-in-gen-7).

As that section says, "Follow Mega Evolutions" takes precedence over "Follow Evolutions". This applies to stats (as you've found), but also types and abilities. Now *why* does this happen? It has to do with how UPR historically ensured that things followed evolutions; it randomizes the evolution chain before it randomizes things like stats and abilities. When it comes time to randomize stats, the stat distribution of the base Pokemon is decided randomly, and then it follows the evolution chain forwards to ensure they all get similar distributions. Other things like typing and ability work similarly.

When we added Mega Evolution support, we simply tacked it on at the end of this process *after* all the regular evolutions were handled. This works fine in Gen 6, where it is impossible to evolve into Mega Evolutions, but breaks in Gen 7, where it *is* possible. In your case, Lopunny-Mega's stats *were* randomized to match Pignite's by the regular evolution step, then they got overwritten to match Lopunny's in the Mega Evolution step.

We can't simply reverse the order in which these two steps happen, because Mega Evolutions are only possible with the final Pokemon in an evolution chain. Instead, we would have to reverse the order in which the evolution step itself occurs. In other words, we would start with the final Pokemon in the chain (including Mega Evolutions), distribute their stats, and follow the chain backwards. As an example, in your case we would start with Lopunny-Mega, then go to Lopunny *and* Pignite, then go to whatever evolved into either of them. So why don't we do this?
1. This whole thing applies to Gen 7 and *only* Gen 7, and we didn't see rewriting a core piece of randomization functionality just to support one gen as a good use of time.
2. The player only gets the ability to Mega Evolve in the postgame for Gen 7, meaning that the value of the "Follow Mega Evolutions" setting is significantly lower than in Gen 6.
2. From you log, here are two different evolution chains:
Palpitoad -> Camerupt
Charmander -> Combusken -> Camerupt-Mega
If we made "Follow Mega Evolutions" and "Follow Evolutions" work simultaneously, then Palpitoad would have a similar stat distribution to Combusken, despite the fact that they are barely related. Depending on how the randomization works out, you could end up with many evolution families that have the same stat distribution, typing, or ability, which would be somewhat boring.

It's for these reasons we just decided not to do this work. Instead, we just documented it on our wiki. Perhaps I'll go and edit the tooltip for "Follow Mega Evolutions" to at least hint at this weirdness within the randomizer itself, though. Hopefully that explains the thought process behind why I'm not going to fix this.

**Comment by Salzkorn** [comment]
My bad on not seeing the documentation! I actually looked in the wiki, but on the Evolutions page, since it explicitly has a "Follow Evolutions" section.

I figured the issue was something like this (and agree it's too much work), and I'd appreciate an addition to the tooltip. Thanks for the explanation!
